label ch2_main:
    $ currentDay = "Tirsdag"
    scene bg sayori_bedroom
    play music t8
    "TIRSDAG"
    "i stod op og tog tøj på"
    s "godmorgen mc,har du sovet godt?"
    mc "ja,det har sovet mega godt"
    s "det da godt"
    mc "og tak for at lade mig overnatte hos dig,elsker dig højt som min bedste ven"
    s "du ved altid hvordan du får mig til at smile"
    mc "jeg er ret sulten lad os spise morgenmad"
    s "god ide min søde ven"
    "i gik ud i køkkenet for at tage noget at spise"
    scene bg kitchen
    "sayori tog noget yougurt og myslig frem meget mere fornuftige valg in du havet mandags"
    mc "det flabedt sagt lasse"
    "jeg siger blot bare sandheden"
    "i begyndte at spise jeres morgen mad,hvilket betyder at u spiser det lige nu"
    "bare så i ved det"
    s "jeg elsker bare yougurt"
    mc "det gør jeg også,det smager altid godt og er sundt"
    "i gik ud af huset"
    scene bg street
    s "ups jeg glemte mit bælte,jeg taber bukserne hehe hvor pinligt,jeg henter tager lige hjem for at hente det"
    mc "okay,jeg venter på dig her"
    s "tak det sætter jeg pris på"
    "hun gik hjem for at finde bæltet,hvor dulled kan hun lige være,og hvorfor går hun i bukser"
    mc "det ved jeg heler ikke,det ret dulled"
    "det er det ja,pludseligt kom rekter jacob frem og så dig og kom hen til dig"
    mc "oh hej rekter jacob"
    da "hej mc,godt at se dig,um hvad venter du på?,skal du ikke til skolen?"
    mc "jo,jeg venter bare på sayori"
    da "tja det typisk hinde at være lidt sendt på den,det sødt af dig at du altid er der for hinde"
    mc "tak jeg kan meget godt lide hinde"
    da "det forstår jeg godt,hun er en god pige"
    "der kom lidt vente stilhed"
    da "når jeg må heler tage afsted,ses,og helst ungå at komme forsendt til timen"
    mc "vi skal nok komme til tiden ses"
    "rekter jacob gik ind i sin bil og kørte afsted igen"
    "pludseligt kom sayori frem igen med bæltet på"
    s "såden,prøv at forstille dig at jeg tabte bukserne i klassen,hehe det vil være pinligt"
    mc "haha ja,men lad os komme afsted,det også lidt for dulled lige nu"
    "i tog straks hen mod skolen"
    scene bg school
    "foran skolen så i helpy oh hilste"
    mc "hej helpy"
    h "oh hej mc,godt at se dig"
    s "det også godt at se dig,jeg går bare ind i klassen nu,i 2 kan bare snakke lidt sammen nu"
    h "oh okay ses"
    "sayori gik ind i skolen"
    mc "føler at det vil blive en god dag"
    h "godt at du kan se det lyse i det,jeg håber bare at vi ikke får toy freddy eller baldi"
    mc "samme her,skal vi gå ind?"
    h "ja det må vi nok heler"
    "i gik ind i skolen"
    scene bg hallWay
    h "og vil bare sige tak for at du lytter til mig og vil bringe tid sammen med mig"
    mc "det var så lidt,jeg er glad for at hjælpe"
    h "du er den eneste ven jeg har,men det er da godt at jeg har dig så"
    mc "hvad med sayori?"
    h "alttså hun er også flink nok men,tror ikke at hun vil være min ven"
    mc "hvad siger du til at være sammen med mig og sayori hos mig når vi også er kommet hjem fra clubben"
    h "mener du virkelig det,vil i virkelig have mig med sammen med jer?"
    mc "ja det er det man har venner til"
    h "waow tak du den bedste ven man kunne ønske sig"
    "han gav dig et hurtigt kram og efter det gik i i klassen"
    scene bg class_day
    "i så rekter jacob stå der"
    "jeg tror at helpy snart vil føle sig snydt lige om lidt"
    da "velkommen alle små elever,idag sker der noget meget vildt og spændene"
    h "what,skal du undervise os idag,det vil hvertfald være en forbedring istedenfor de skræld lærer"
    da "haha nej,jeg har noget andet at tage mig til bagefter"
    h "selvføgelig har du det"
    "sagde helpy irriteret"
    da "jeg er kommet her for at respentere jer for 2 nye der skal gå i den her fantastiske skole"
    h "hoste lyd,skræld skole"
    da "stille snegl!,når men her kommer svampebob"
    sb "bahahaha,det mig jeg hedder svampebob,og jeg er mærkelig bahahaha"
    h "what yes endelig en lærer der er flink nok"
    da "haha du så dum helpy,nej han er bare en elev,ligesom jer bønder,jeres rigtige lærer kommer nu"
    "blækward kom ind fra døren"
    da "tag godt i mod blækward,han er jeres nye lærer,og han skal undervise jer idag"
    h "pls lad det være en god lærer din dumme trash skole"
    bd "hej elever,jeg vil smadre svampebob og jer andre hvis i fejler"
    da "som i kan se og høre er han en fremravene lære"
    h "what hørte du ikke lige hvad han lige sagde der!"
    da "jeg sagde,...STILLE SNEGL"
    h "jeg hader den her skole"
    da "når men i må have det godt,jeg må heler passe mit job i kontoeret,ses små børn,og blækward"
    bd "ses,jeg skal nok passe rigtig godt på mit nye job som lærer"
    "darthjacob tog ud igen og pludseligt kom bedste mor gris ind"
    br "ahohoho hva så der noobs,nu skal jeg rigtig irritere jer hverdag"
    bd "oh hvor godt vi lige fik en ny elev her"
    br "vent nej,jeg er da ikke..."
    bd "tie stille og tag en plads!"
    "bedste mor gris var stille og gjor som blækward sagde"
    bd "okay hør godt efter små børn,idag skal i skrive jeres egen historie"
    mc "det lyder sjovt"
    bd "godt sagt mc,jeg tror at du måske vil blive min ynglings elev"
    h "seriøst!,du har jo lige mødt ham!"
    bd "ja,men han prokker sig ikke ligesom dig lille snegl"
    h "hvorfor skal i alle kalde mig for snegl!"
    bd "STILLE ELLER JEG SMADRE DIG!"
    h "...?"
    bd "det tænkte jeg nok,når børn,KOM SÅ IGANG!"
    "i begyndte at skrive jeres historie ned,nu skal du vælge en historie som du vil skrive om"
    bd "når ja glemte at nævne at hvis i skriver en dårlig eller kedelig eller en historie der ikke giver nogen menning,dumper i"
    menu:
        "shrek og hans sump":
            mc "okay her kommer min historie om shrek om hans sump"
            "du rejste dig op og læste det højt"
            mc "Det var en tidlig morgen i Shreks sump. Duggen hang stadig på de snoede træer"
            mc "og der lød et par tilfredse kvæk fra sumpens frøer."
            mc "Shrek snorkede højlydt i sin seng, mens Fiona og Æsel allerede var oppe og i gang med at lave morgenmad."
            mc "Pludselig bankede det voldsomt på døren. BANG BANG BANG"
            mc "shrek bliv irriteret og de forsatte med at banke på døren,så han gik ned og åbnet for dem"
            mc "det var nogen små dværge"
            mc "Shrek! Hjælp os! råbte de i munden på hinanden"
            mc "Jeg er ikke en helt, og jeg er bestemt ikke jeres babysitter,"
            mc "mumlede Shrek, men Fiona og Æsel stod allerede nysgerrigt bag ham."
            mc "vil du ikke nok hjælpe os sagde dvagene"
            mc "shrek sagde så,hvad er det i overhovedt skal have hjælp til?"
            mc "der er en ond trold mand ved navn grimsfjæs,han minder om gagamel og tror at vi er smølfer"
            mc "og derfor jagter han os sagde dvagene"
            mc "okay fint hvor finder jeg ham i kalder grimfjæs,sagde shrek"
            mc "du finder ham ude i skoven sagde de"
            mc "okay jeg reder jer,men kun den ene gang okay!,sagde shrek meget bestemt"
            mc "yep vi lover det sagde de"
            mc "godt og hold jer væk fra min sump,ellers vil jeg spise jer til morgen mad sagde han truene"
            mc "de niggede og gemte sig et sted hvor grimfjæs ikke kan finde dem"
            mc "shrek fandt den onde grimfjæs og gjor så klar til kamp"
            mc "grimfjæs sagde ha,en simpel trold kan ikke besejere mig den mægtige grimfjæs"
            mc "det skal du ikke være så sikker på sagde shrek"
            mc "grimfjæs sagde så,oh jeg skal give dig sagde jeg alaka"
            mc "han skulle til at skyde shrek med sin magiske stav"
            mc "shrek kom løbene og slog hans grimme fjæs"
            mc "åh nej,min eneste svaghed at blive slået i mit grimme fjæs,sagde den onde trold mand og endte med at dø"
            mc "lol han var weak sagde shrek og tog hjem igen for at slappe af igen og dvagene var redet slut"
            bd "altså den gav ingen menning,men det var nu ret underholdene,godt gået mc du består"
            mc "åh tusiden tak blækward"
            "blækward gik hen til helpy for at høre hans historie"
        "historien om darthjacobs barndom":
            mc "okay her kommer historien om darthjacobs barndom"
            "du rejste dig op og læste det højt"
            mc "I en fjern, fjern galakse, på en planet ingen længere husker navnet på"
            mc "blev lille Jacos født under en himmel fyldt med storme"
            mc "Allerede som barn kunne man mærke, at noget særligt boede i ham"
            mc "Han elskede mørke huler og stille aftener"
            mc "hvor vinden susede mellem træerne, og han kunne høre planetens dybe, dunkle ekko."
            mc "Jacos voksede op i en lille landsby, hvor han altid skilte sig ud"
            mc "Mens de andre børn legede og grinede, sad Jacos alene og studerede skyggerne"
            mc "der dansede på væggene"
            mc "Han er bare lidt sær, sagde de voksne, men ingen forstod, at Jacos kunne føle noget dybere. Noget kraftfuldt."
            mc "n dag, da han var blot 10 år gammel, fandt Jacos en gammel rusten hjelm i en forladt hule"
            mc "Da han tog den op, strømmede en mærkelig kulde gennem hans krop"
            mc "Han mærkede, hvordan en stemme, langt væk, hviskede Du er skabt til noget større, Jacos. Du er mørkets arving."
            mc "Fra den dag begyndte alt at forandre sig"
            mc "Hans hænder kunne flytte små sten uden at røre dem"
            mc " Folk i landsbyen blev nervøse, når han gik forbi"
            mc "Selv træerne syntes at bøje sig let, når Jacos nærmede sig. Han følte sig ikke længere hjemme."
            mc "En nat forlod Jacos landsbyen, iført den gamle hjelm"
            mc "der nu passede perfekt"
            mc "Han vidste ikke, hvor han var på vej hen"
            mc "men han fulgte stemmen, der kaldte fra stjernerne"
            mc "Snart ville han blive DarthJacos, den skikkelse, galaksen aldrig ville glemme"
            mc "slut"
            bd "den var lidt mærkelig,faktisk for mærkelig,du dumpet"
            "blækward gik hen til helpy for at høre hans historie"
    h "den her historie handler om en helpy som lider af en trash skole"
    "helpy rejste sig op for at fortælle hans historie"
    h "der var engang en helpy som var lykkelig"
    h "men så en dag følte han sig ensom,så han besluttet sig for at prøve at gå i en skole"
    h "ligså snart han har gået i skolen i noget tid fortryd han at han valgte den trash skole"
    h "alle lærene var onde mod ham,men edtemindste havet han en ven ved navn mc"
    h "mc har altid været så god ved stakkels helpy,så han kunne edtemindste tænke lidt mere positivt"
    h "han endte med at invetere helpy med til ham med sayori så han fik inu flere venner"
    h "plus han fik en club at gå i,for han tænkte at det kunne han ligeså godt joine"
    h "fordi toyfreddy ikke vil lade ham gå ud af den trash skole selv når han har fri"
    h "bare fordi han har givet ham uretfærdige bøder som han ikke kan betale,slut"
    bd "den vil være god hvis det ikke skulle forstille os!"
    h "what,hvad mener du mand!,hvorfor kan du ikke lide at det hanlder om jer!"
    bd "for det første,det handler alt for meget om dig"
    h "what!"
    bd "og for det andet,du skrev i din historie at vi er nogen forfærdelige lærer!"
    h "jeg skrev bare hvad der passet"
    bd "så ja du dumpet,taber snegl!"
    h "jeg hader den her skole"
    bd "din tur funtime foxy"
    fx "luuu min historie er rigtig god,er i klar"
    h "åh nej,ikke hindes historie,ved bare hvad det kommer til at handle om"
    fx "der var en dag hvor jeg mødtes med ron hvor jeg sagde,skal vi ikke følges ron"
    fx "så sagde han jo lad os gøre det,det vil blive sjovt"
    fx "hans bukser var så pæne,så jeg sagde,wow du har pæne bukser på"
    fx "så sagde ron,tak,jeg går altid med dem"
    fx "bagefter da vi gik en tur tabte han bukserne og sagde nedtur"
    fx "også grinte vi alle,hahaha luuuuu"
    h "jeg kender den historie"
    fx "hvordan det?"
    h "fordi du fortæller altid den samme historie!"
    fx "den er jo så god"
    h "nah,elnlig ikke"
    bd "du dumper funtime foxy,den var godt nok kedelig og uvigtig at høre,jeg er så irriteret på dig!"
    "blækward kølet ned igen og gik over til hmmmm?"
    bd "hvor er vanny,den pjækker!"
    mc "nu hvor du siger det,jeg har ikke set hinde siden igår,glitchtrap tog hinde med et sted,også så vi hinde ikke igen"
    bd "mystisk,når lige meget med hinde,lad os forsætte timen"
    "han gik mod bonnie for at høre hans historie"
    fb "okay den her skal nok blive god"
    "bonnie begyndte at fortælle hans historie"
    fb "der var engang en bonnie som elsket flæskestejs burger,men noget forfærdeligt skete"
    fb "der var slet ikke mere flæskestej,bonnie gik i panik og sagde,åh nej det er verdens undergang"
    fb "freddy kom hen til bonnie og sagde,jeg ved hvordan vi får flæskestej igen"
    fb "hvordan sahde han håbefuldt,det nemt nok,du skal bare købe det sagde freddy"
    fb "what,man kan ikke bare købe flæskestej sagde bonnie,det giver ingeng menning sagde freddy forvirret"
    fb "jeg har tjekket alle butikkerne,de sælger det ikke mere,men jeg ved nu hvordan vi får det tilbage igen"
    fb "hvordan sagde freddy,bonnie svaret tilbage,vi må tage over til flæske kongen"
    fb "bonnie og freddy tog straks afsted og kom til flæske kongen,bonnie og freddy bliv helt overasket over at han findes"
    fb "waow du findes virkelig sagde bonnie med store øjne"
    fb "jeg nægter at tro det,bonnie du må undskylde at jeg ikke troet på dig i alt den tid"
    fb "bonnie sagde til freddy,det okay freddy,det giver jo trosalt menning at du ikke troet på det før hen"
    fb "flæske kongen svaret,valg vil i her dødelige"
    fb "årh mægtige flæske konge,vi er kommet for at bede om din hjælp,vi har ingen flæskestej tilbage"
    fb "det er jo alvorligt udbryd flæskekongen,godt i kom her til,jeg vil søger for at der kommer flæskestej igen"
    fb "tusind tak for din hjælp o mægtige flæskekonge"
    fb "det dig vi burde at takke bonnie,sagde flæskekongen,og du vilnu blive kendt som helten i flæskestej"
    fb "what det jo vildt mange tak flæske konge sagde de og tog hjem til dem selv igen"
    fb "det endte lykkeligt,og der er nu flæske stej til dem alle,slut"
    bd "waow,den historie var for mærkelig!"
    fb "var den ikke god?"
    bd "god nej,sjov ja,men du dumper"
    fb "what hvorfor?"
    bd "havet jeg ikke sagt det klart!,historen skal give menning og være sjov og din gav overhovedt ingen menning,så derfor dumper du!"
    fb "what jeg burde at få en ok karakter,jeg gjor den jo sjov"
    bd "såden er det,surt sjov"
    fb "flabed"
    "blækward bliv så sur på bonnie at han slog ham"
    fb "av du sindsyg mand!"
    bd "så kan du lære det,ingeng skal sige at jeg er flabed eller irriterende,eller hvad enden ond ting det er!"
    h "ja det bliver lidt svært at ungå,mumulet han"
    bd "hvad sagde du der lille snegl?"
    h "um ikke noget"
    "han gik mod svampebob for at høre om hans historie"
    sb "bhahahaha,jeg vil ikke sige det"
    bd "hold nu op svampebob!"
    sb "bahahahah nej"
    bd "jeg smadre dig hvis du ikke snart siger din historie!"
    sb "okay her er min"
    "svampebob rejste sig op og fortalte hans historie"
    sb "der var engang en svampe bob,han mødtes med patrik,de bliv venner lige med det samme"
    sb "de prøvet at blive blækwards ven,men han spillet så kosbar,men så senere hen i en dag skete et mirakel"
    sb "blækward indså hvor godt han kunne lide os,så han bliv vores gode ven og havet det sjovt sammen"
    sb "svampebob spurgte skal vi ike være venner forevigt blækward,blækward sagde,nej,bedste venner"
    sb "de sluttet af med et kram,bahahahaha god historue var,jeg fandt selv på den"
    s "wow det var så sødt,det venskab lyd så smukt"
    bd "det kan godt være,men han dumper stadig"
    s "hvorfor var den ikke god?"
    bd "den var ikke sjov og den gav ingeng menning,så han dumper dobelt så meget som helpy gjor,fordi jeg hader svampebob plus hans histoire var kedelig og gav ingeng menning"
    sb "bahahaha du noget du bare siger fordi du i virkeligheden ikke vil indrømme at vi er gode venner"
    bd "jeg nakker dig svambebob!"
    "da blækward slog svampebob og kølet ned igen,gik han hen til sayori for at høre hindes historie"
    s "jeg ved ikke lige hvad der skete før der men er sikker på at du vil elsker min historie"
    "hun rejste sig op og begyndte at læse sit højt"
    s "Det var en perfekt morgen i den lille by"
    s " Solen skinnede gennem Sayoris vindue"
    s "og fuglene sang deres glade melodier"
    s "Sayori sprang ud af sengen med et stort smil og strakte armene ud mod loftet"
    s "I dag bliver en fantastisk dag!” erklærede hun for sig selv"
    s " som om verden havde brug for at høre det."
    s "Hun besluttede sig for at sprede glæde, hvor end hun gik"
    s "Først løb hun over til naboens hus og hjalp med at samle blomster til deres have"
    s "Hun dansede rundt med kurven, som om hun selv var en blomst."
    s "Derefter tog hun en pose småkager med i tasken og løb hen til parken"
    s "Her satte hun sig på en bænk og begyndte at dele dem ud til forbipasserende"
    s "både børn, voksne og endda en hund, som fik et “Værsgo, lille ven!."
    s "Sayori stoppede ikke der. Da hun så en ældre mand sidde alene på en bænk, gik hun hen og satte sig ved siden af ham"
    s "Hej! Er det ikke bare en smuk dag i dag?” sagde hun med sit største smil."
    s "Manden så overrasket ud, men efter et øjeblik begyndte hans mundvige at trække opad"
    s "det har du ret i, unge dame. Jeg havde næsten glemt at nyde solen"
    s "Da aftenen nærmede sig, gik Sayori hjem, træt men glad"
    s "Hendes hjerte føltes let, for hun vidste, at hun havde gjort dagen lidt lysere"
    s "både for andre og for sig selv. Hun lagde sig i sengen med et smil på læben og tænkte"
    s "Lykken er som solskin. Den skinner mest, når man deler den med andre"
    s "slut"
    bd "den var ret rørene,og den giver faktisk god menning,så noget kan ske plus historien var god,du består"
    s "virkelig,tak,jeg er så glad for at i kunne lide den"
    bd "nu ved jeg at sayori er min ynglings elev"
    h "du sagde jo lige at det var mc før der var din ynglings!"
    bd "nej,der sagde at han vil måske blive det,men det bliv han ikke,men han er okay,i modsætining til dig snegl"
    h "jeg skulle aldirg havet valgt den her skole"
    "blækward gik hen til natsuki for at høre hindes historie"
    "natsuki rejste sig op og talte om hindes historie"
    n "okay gør jeg klar til noget virkelig cool"
    "hun begyndte at læse"
    n "Der var engang en pige ved navn Natsuki, som elskede at bage"
    n "et ville hun dog aldrig indrømme sådan uden videre"
    n "Det er bare en hobby, okay? Det er ikke noget særligt! plejede hun at sige med røde kinder, når nogen spurgte."
    n "En dag besluttede Natsuki at deltage i den store kagekonkurrence i byen"
    n "ikke fordi jeg vil vinde eller noget! mumlede hun, mens hun æltede dejen. “Jeg gør det bare… fordi jeg kan"
    n "Men lige før konkurrencen begyndte"
    n "opdagede hun noget forfærdeligt"
    n "En anden deltager havde kopieret hendes opskrift på de sødeste"
    n " lyserøde cupcakes med jordbærglasur."
    n "“H-Hva?! Det er min idé!” udbrød hun og knyttede næverne"
    n "Med et fnys gik hun i gang med at bage noget helt andet"
    n "noget, som var typisk Natsuki"
    n "små cupcakes med chokolade, et strejf af krydderi og små, vrede katte ansigter tegnet med glasur"
    n "Se bare, sagde hun bestemt, mine er tusind gange bedre end de dér kedelige kopier!"
    n "Da dommerne smagte på hendes kager, blev deres øjne store"
    n "Disse… er fantastiske! sagde en af dem. De er søde, men med en overraskende bid! Ligesom… dig"
    n "Natsuki så hurtigt væk og foldede armene. “Hmpf, det er ikke noget særligt… Men… tak eller hvad."
    n "Og selvom hun fik førstepladsen, nægtede hun at smile for meget"
    n "Hun gik derfra med pokalen i hånden, men hendes røde kinder afslørede alt"
    n "Helt ærligt, det er ikke som om jeg prøvede SÅ hårdt!” mumlede hun"
    n "mens hun allerede tænkte på sin næste bagning.slut"
    bd "den historie var ret god,plus den gav menning,du består"
    n "tsk det ikke noget særligt,bare en fjollet ide jeg havet"
    s "den var så god og så cute som dig natsuki"
    n "jeg er ikke....CUTE!"
    "selv om natsuki virket irriteret og kold,kunne hun ikke skjule lidt rødmen på hindes kinder"
    n "hold din mund lasse!"
    "når når okay,jeg har altså også følelser"
    "blækward gik vidre til yuri,hinde som de fleste ser som kedelig,fordi hun er kedelig"
    y "huh?"
    bd "når fortæl os din historie yuri"
    y "okay jeg skal gøre mit bedste"
    "yuri rejste sig op og begyndte at fortælle hindes historie"
    y "den her handler om skyggernes rige"
    y "Langt borte, mellem verdener, lå Skyggernes Rige"
    y "et sted, hvor lyset sjældent nåede, og mørket hviskede historier til dem, der turde lytte"
    y " Ingen vidste præcis, hvordan man kom dertil,"
    y "men det siges, at hvis du gik gennem den tætte tåge og fulgte dine egne fodtrin, ville du finde en dør uden håndtag."
    y "En dag trådte en ung rejsende, ved navn Liora, ind i tågen"
    y "Hun havde hørt om riget fra gamle bøger"
    y "et sted, hvor skygger blev levende og kunne forme sig efter dine tanker"
    y "Liora var ikke bange. “Jeg søger svar,” sagde hun til mørket, som dansede omkring hende"
    y "Da hun endelig fandt døren, åbnede den sig lydløst af sig selv."
    y "Inde i Skyggernes Rige var alt dæmpet og stille"
    y "Mørke silhuetter gled langs væggene som ånder uden ansigt, men de var ikke fjendtlige"
    y "de betragtede hende bare. Én skygge, større end de andre, gled frem og hviskede med en stemme, der lød som vinden"
    y "Hvad søger du, rejsende?"
    y "Liora løftede hagen.Jeg søger at forstå, hvem jeg er."
    y "Skyggen lo sagte, en hul lyd, der rungede i det tomme rum"
    y "Sandheden findes her, men kun hvis du tør se ind i din egen skygge"
    y "Foran hende formede skyggerne sig til en skikkelse, der lignede hende selv"
    y "men mørkere, med et blik fyldt af frygt, vrede og håb. Liora følte sit hjerte slå hårdt"
    y "Hun trak vejret dybt og hviskede"
    y "Jeg er ikke bange for dig."
    y "Med de ord opløstes skikkelsen, og lyset begyndte langsomt at bryde gennem mørket"
    y "Skyggernes Rige forsvandt bag hende, men noget havde ændret sig i Liora."
    y "Hun bar nu skyggerne med sig ikke som frygt, men som en del af sig selv."
    y "slut"
    bd "wow en kedelig historie,ligesom din personlighed"
    y "må jeg spøger om noget?"
    bd "nej,ingeng gider at høre på en kedelig person"
    "yuri bliv fornærmet,men valgte at ladevære med at sige noget om det"
    bd "og foresten yuri,du dumpet"
    bd "lad os høre din historie ayano"
    "ayano nikket og begyndte at fortælle hindes historie"
    ay "der var engang en prinsesse som bliv låst inde i et tårn"
    ay "for hvergang hun spillet smart,bliv hun klodset og gjort til grin"
    ay "det var som en forbandelse der ramte hinde"
    br "det må være mig der forbandet hinde med upser,ahohoho"
    ay "du afbryder"
    br "uuuuups,der gjor jeg det vist igen var,timon"
    ay "men så fandt hun nogen lykke sko som hun bare skulle tage på"
    ay "det slog hinde når hun havet skoene på kunne hun ikke blive forbandet længer"
    ay "hun tog dem på og endte med at kunne spille smart uden problemer,slut"
    br "ej,det var ikke så god lille du,ahoho"
    bd "den var ret trash,både kedelig og gav ingen menning,dumpeeeeeeeet!"
    br "ups du vist uheldigt du timon ahoho"
    bd "okay pls kom nu med en elev der dur til noget"
    br "tja jeg er god til at irritere andre ahohoh sjovt"
    ak "jeg har en ide til min historie"
    "hun rejste sig op og læste,hun kigget flirtene på dig mc"
    ak "det startet med en pige der følte sig alene"
    ak "pludseligt så hun en smuk dreng ved navn mc der så det gode i hinde"
    ak "de bliv gode venner og lavet mange ting sammen"
    ak "de begyndte at blive forælsket og bliv kærster,og levet sammen forevigt,slut"
    bd "kedeligt!,du dumper"
    ak "jeg skrev bare sandheden mellem mig og mc"
    h "du har ham slet ikke som kærste"
    ak "det tror jeg at jeg har,har jeg ikke mc"
    bd "okay nu det nok,jeg gider ikke at høre på det mere,for nu skal vi videre til timen"
    "blækward ventet på at høre saukas forhåbenlige gode histroie"
    sa "jeg kan vel godt fortælle min nu,det startet med en solskin jeg så ud af vinduet"
    sa "det var et tegn på at jeg skulle hjælpe de triste borger"
    sa "så så mange triste folk,jeg må gøre dem glade tænkte jeg,men hvordan"
    sa "jeg fik så den gode ide hvor jeg gav dem alle en småkage"
    sa "jeg gav dem alle en småkage,men det var åbenbart ikke nok"
    h "ja hvorfor mon"
    sa "også kom jeg i tanke om at de skulle have et kram,men det hjalp heler ikke mod deres smerte"
    sa "jeg endte så med at give dem alle omærksomhed,og det endte med at de alle bliv gode venner,slut"
    bd "kedelig historie,du dumpet,skåd elever"
    bd "så mangler vi bare dig bedste mor gris"
    br "okay bro,jeg har en god historie,den handler om timon"
    "da bedste mor gris er en cupcake,stod hun bare på bordret"
    br "der var engang en timon,jeg sagde hej timon,og han sagde,hej bedste mor gris"
    br "så sagde jeg,er du klar til at jeg gøre det igen timon,også spurgte han,gør hvad?"
    br "også brangte jeg uheld så han altid bliv uheldig,også sagde jeg uuuuups,jeg gjorte det vist igen"
    br "god historie var ahoho"
    bd "det var godt nok trash,du dumper"
    br "ej bro,har du prøvet at tag dem på timon"
    bd "når men i har frikvater nu,ses,nu gider jeg ikke se på jer mere"
    "blækward pakket sine ting sammen og gik vidre,og i gik på vej ud til klassen"
    scene bg hallWay
    h "wow en skåd lærer var"
    mc "han var okay mod mig og god ved sayori og natsuki,men ja,han er lidt voldig"
    h "lidt!,han slog nogen elever!,det vil jeg ikke kalde for lidt"
    s "jeg tror at vi alle trænger til at komme ud og lave noget i frikvateret"
    mc "du har ret sayori lad os komme ud"
    "i gik ud for at holde frikvater"
    scene bg school_yard
    "i begyndte at hygge tale lidt"
    mc "så hvordan har du det med at være sammen med os helpy?"
    h "ret godt faktisk,i 2 er nogen mega gode venner især dig mc"
    s "det så rart at vi alle er venner,og det bliver så sjovt når vi alle 3 skal ud sammen efter alt det her"
    mc "yep det bliver fantastisk"
    "i tænkte på en ide på hvad i skal lave i jeres frikvater"
    mc "jeg har en ide,lad os tegne"
    s "det virker som en god ide,lad os gøre det"
    h "jeg har tilfældigvis nogen farve blyanter og papir med"
    mc "hvor har du dem fra?"
    h "det har jeg ikke lyst til at sige,men lad os nu gå i gang med at have det sjovt"
    s "yay,jeg ved allerede hvad jeg vil tegne"
    mc "okay lad os lave en kokoranse"
    s "jeg er med på den,hvad er det?"
    mc "den der tegner bedst vinder,og sidste pladsen skal sige sin mest pinglige øjeblik"
    s "aftale"
    "i begyndte at tegne,senere hen bliv i færdige og i viste jeres tegninger og grinte"
    h "se,jeg har tegnet toy freddy med en numse hage haha"
    mc "haha den er ret sjov,den passer godt til ham"
    h "ja ik,fordi så grim er han haha"
    s "jeg har tegnet mig der taber bukserne hehe"
    h "hvorfor dog det?"
    s "fordi jeg altid taber bukserne når jeg ikke har bælte på haha"
    mc "det ret sjovt at se"
    h "det godt nok dulled"
    s "ja jeg er ret dulled,jeg har også en bukse samling,jeg har cirka 100 par bukser"
    h "what!?"
    mc "tja det ret mange"
    mc "jeg har tegnet blækward som smiler"
    h "haha den er ret sjov,han burde også at gøre det noget ofter"
    mc "jeg synes at din tegning vinder helpy"
    s "det synes jeg også,den med toy freddy var genial"
    h "haha tak,godt at i edtemindste sætter pris på mig"
    mc "så betyder det vil at du skal sige din pinglieste øjeblik sayori"
    s "det rigtigt,det mest pinglige jeg har oplevet er at tabe bukserne foran hele skolen"
    h "det kan jeg godt huske,og funtime foxy gik ALT for meget op i det"
    mc "tja det var pingligt ja"
    "i hørte klokken ringe,det var tid til at tage til klassen"
    h "selvføgelig ringet klokken"
    mc "vi må nok gå til time"
    s "ja lad os gå"
    "i kom til skole gangen og foxy stod der"
    scene bg hallWay
    h "hvorfor er du her ude,skulle vi ikke ind klassen"
    fo "nej,vi skal jo til idret"
    h "åh nej,ikke idret"
    mc "er det så dårligt"
    h "det vildt trash,hvereneste fejl man laver begynder foxy at gøre grin med en"
    fo "begynd nu ikke at tude snegl"
    h "flabed"
    fo "lev med det,når men kom med mig elever,for nu skal vi til idret"
    "i fulgte foxy hen til idret"
    scene bg train_hall
    fo "godt elever,nu vil jeg dele jer op i et hold"
    "foxy begyndte at dele jer op,måske er du heldig"
    fo "vi spiller høvdinge bolt idag"
    mc "hvad er det?"
    fo "haha ved du ingeng gang det,du godt nok ikke særlig klog"
    h "jeg sagde jo at han var en ond lærer"
    fo "i høvdinge bolt skal man skyde mod hindaen,og det er alle mod alle"
    h "vent what!,du sagde jo lige før at vi skulle dele os op i et hold"
    fo "det ved jeg sure snegl,men jeg skiftede menning"
    h "what!,det burde en lære ikke at få lov til bare såden uden vidre!"
    fo "jeg gør som der passer mig taber"
    fx "luuu han taber bukserne"
    h "roboter bruger ikke bukser din dul"
    fx "luuu"
    br "nårrrh var,helpy er vist en lille baby bjørn ahoho"
    fo "haha den var god bedste mor gris"
    h "jeg hader den her skole"
    fo "husk at den der er tilbage som den eneste vinder,lad spillet begynde,jeg vil se en voldig kamp her"
    fo "det skal helst være smertefuldt hvis muligt,jeg har taget popcorn med for at se jeres kamp"
    h "vent what?"
    fo "når held og lykke og kom så igang"
    "i begyndte at spille spillet"
    "helpy var den første der bliv ramt"
    fo "haha du ude helpy,hvor er du bare trash ahaha"
    h "what,det jo også snyd når jeg skal være så lille"
    fo "haha skal du nu til at græde tudefjæs"
    "den næste der tabte var funtime foxy"
    fo "du ude funtime taber,fordi du tabte som en taber,haha hvor er jeg sjov"
    fx "luuuuu,taber bukser"
    "den næste der var ude var bonnie,foxt bliv bare ved med at gøre grin med dem der tabte"
    fo "du ude bonnie,taber snegl,fordi du er langsom som en"
    fb "behøver du virkelig at gøre grin med os hvergang"
    fo "jeg behøver ikke,men gøre det bare fordi det sjovt at se jeg blive smadret"
    fb "du er lidt sindsyg"
    fo "stille lille kanin,jeg har et sjovt bolde kamp jeg skal se"
    "svampebob var den næste der bliv hårdt ramt på maven"
    sb "det gjor faktisk ret ondt bahahaha"
    fo "du ude svampedum,fordi du ikke er så klog hahaha"
    "den her gang tabte bedstemor gris"
    br "arrrrh,jeg kan ikke tåle at blive ramt af en boldt"
    fo "lol du weak bedste mor gris,du ude"
    br "jeg flyver bare ud af banen ahohoho"
    "nu tabte alle de andre også,der var kun dig og akira tilbage"
    ak "når da mc,er du bange,ryster du mon lidt i bukserne"
    mc "jeg er ikke bange,det bare et spil"
    ak "det var da godt,men du kommer ikke til at slå mig i det her spil,jeg er vild god"
    mc "jeg spiller også bare for at have det sjovt,og så også fordi at foxy tvang os"
    ak "lad os se hvem der vinder her,godt du går efter at have det sjovt"
    ak "det er også en af de ting jeg elsker ved dig"
    mc "vent hvad?"
    "akira skyd bolden mod dig nu skal du se om du vinder eller taber,ved at du slår terning"
    menu:
        "1 2 3":
            "desværre bliv du ramt og du grab den ikke,så du tabte spillet og akira vandt"
            fo "du ude mc,akira er vinderen"
            h "what,du gjor ingeng gang nar af ham når han tabte,når du gjor det mod os alle andre!"
            fo "det klart,mc er min ynglings elev"
            h "hvad der galt med jer lærer!,i alle har bare en elev hvor det kun den elev i kan lide og hader alle andre!"
            fo "lev med det snegl"
            "akira kom hurtigt hen til dig for at se om du er okay"
            ak "er du okay mc?"
            mc "ja jeg har det fint"
            ak "er du sikker,jeg ramte dig ret hårdt"
            mc "tja det gjor kun lidt ondt"
            ak "undskyld hvis jeg ramte dig hårdt"
            mc "det okay,det går over"
            ak "du så stærk,det kan jeg godt lide ved dig"
            "du kunne mærke at hun flirtet lidt med dig,men du valgte bare at prøve at ignorere det"
            "da spillet var slut skulle i alle tilbage til foxy"
        "4 5 6":
            "du greb bolden og vandt spillet"
            fo "du ude akira,mc har vundet,jeg viste at du vil klare det mc"
            mc "virkelig tak foxy"
            "akira gik hen til dig med et varmt og kærligt smil"
            ak "aw,du virkelig god mc,så stærk og sej"
            mc "tak akira,jeg gjor mit bedste"
            ak "du så sød mc,jeg håber at vi en dag kunne være mere sammen"
            mc "det må jeg finde ud af med hvilken dag der passer bedst"
            "akira nikket og prøvet at kysse dig,men heldigvis kom natsuki og redet det"
            n "wow wow wow,jeg kan godt se hvad i har gang i"
            ak "jeg prøvet bare at have et romantisk øjeblik med mc"
            n "gør det privat istedenfor,vi gider ikke at se nogen kysse ad"
            ak "hvor du bare sart,jeg troede at du var sej"
            n "tag det i dig igen,jeg er sej"
            "natsuki bliv tydeligt irriteret"
            fo "okay så det nok i 2,kom elever,i skal hen til mig igen"
            "i gik hen til foxy igen"
    fo "okay elever,timen er slut,men ingen i går,skal jeg fortælle noget vigtigt"
    h "virkelig,har du tænkt dig at sige undskyld for at gør grin med os?"
    fo "haha nej dumme snegl,vil bare sige at da du tabte helpy,der lignet det at du faldt som en grim flodhest haha"
    h "what!,hvor flabed kan man lige være!"
    f "når men i kan bare tage til katinen og holde spise pause,ses små børn"
    "i alle gik hen mod gangen for at komme vidre mod katinen"
    














                

















    return