label ch3_main:
    $ currentDay = "Onsdag"
    scene bg bedroom
    play music t8
    
    "ONSDAG"
    "du stod op og tog dit tøj på,og du husket hvad der skete i din drøm,så du valgte at holde den for dig selv og nyde dagen"
    mc "det er idag hvor jeg skal rede sayori og være sammen med monika i clubben idag"
    "glæder du dig?"
    mc "ja,jeg er både nervøs og glad på sammen tid,så længe jeg ikke får baldi som lærer"
    "det godt at høre,du tog ned i køkkenet hvor natsuki også var kommet til"
    scene bg kitchen
    n "okay lad os lave noget mad mc"
    mc "yep,og jeg kan sige at idag skal nok blive din bedste dag nogensinde"
    n "hvorfor det?"
    mc "det finder du ud af senere"
    n "når men jeg tænker at vi kunne lave æg og bacon idag"
    mc "mmmm det lyder lækkert,lad os lave det"
    "i begyndte at lave maden"
    mc "det sjovt at være sammen med dig natsuki"
    n "tak,du er heler ikke værest,du en god ven,men sig ikke til nogen at jeg har været blød okay,jeg har et ry at opretholde!"
    mc "hehe barolig natsuki,jeg lover at jeg holder det mellem os 2"
    n "hey jeg er rolig,og um tak"
    "i lavet maden færdigt og tog tilærkner og bestik frem i stuen hvor i vil spise sammen"
    scene bg livingroom
    "inu engang ser i den samme kedelige film mens i spiser"
    n "du må nok se at få en bedre film"
    "sagde hun med et grin"
    mc "haha ja du har ret,den var god i starten,men en eller anden grund er jeg blivet træt af den"
    n "ja hvorfor mon da"
    "i spiste maden færdigt sammen og i gik tideligt ud da du havet travlt med at skulle se til sayori"
    scene bg street
    n "skal du ikke med til skolen?"
    mc "jo jo jeg vil bare se til sayori,er bekymret for hinde"
    n "hvorfor det?,hun er jo evig glæde skal du tænke på"
    mc "det var menningen at hun skulle komme hos os igår,men hun aflyste det af en grund hun ikke vil fortælle mig"
    n "okay vi ses i skolen så"
    mc "det gør vi ja,ses"
    n "bare i 2 fjollehoveder kommer til tiden"
    "natsuki gik mod skolen,mens du skyndte dig mod sayoris hus"
    scene bg house
    "du banket på døren da du ankom,ingeng reaksion,men du kunne se at døren ikke var låst,så du gik ind"
    scene bg kitchen
    "du kom ind i huset i i hindes køkken,du prøvet at råbe efter hinde"
    mc "sayori!"
    "ingeng reaksion,det fik dig til at ryste i bukserne"
    mc "det ret dulled"
    "det ved jeg,man skulle tro at du spillet en doki doki dulle mod"
    mc "hmmm hvad er det hun laver,hun kommer jo forsent hvis hun bliver ved med at blive væk"
    "du besluttet dig for at gå op til hindes værelse"
    scene bg door
    "du kom til hindes dør der var lukket,men den var heler ikke låst"
    mc "det har er underligt"
    mc "saoyri!"
    "ingeng reaksion"
    mc "er det okay at jeg kommer ind?"
    "der kom stadig ingen reaksion,men hun gav dig ingen valg,så du kom ind"
    mc "nu kommer jeg ind sayori"
    "du åbnet døren"
    scene bg sayori_bedroom
    s "oh hej mc,undskyld at jeg ikke reageret da du kaldte"
    "du så hinde have et reb i hånden"
    mc "sayori hvad skal du med det reb?"
    s "um det er um,ikke noget slemt i hvertfald hehe"
    "hun smilte men du kunne se på hinde at hun skjuler noget for dig,og nej det er ikke noget med at tabe bukserne at gøre"
    mc "vil du ikke nok fortælle mig sandheden"
    s "det her er sanheden,jeg har det fint"
    mc "virkelig?,hvordan kan det så være at du skrev i går aftes at du havet brug for min hjælp?"
    s "um det var bare for sjov,bø skramte jeg dig hehe"
    mc "sayori,pls fortæl mig hvad der rigtigt forgår"
    s "lov at du ikke siger det til nogen okay"
    mc "det lover jeg"
    s "okay du kan sikkert huske at jeg fortalte dig om min depression i mandags ik?"
    mc "ja selvføgelig"
    s "okay,det fordi nu det blivet værre,jeg har selvmords tanker"
    mc "what,hvorfor?"
    s "jeg føler at jeg er svag og ubruglig,og bliv lidt jealou over at du var sammen med de andre,så følte at jeg ikke behøvet at være der"
    mc "sayori,jeg vil ikke kunne klare det uden dig"
    s "mener du virkelig det?,jeg er en byrde mc,jeg kan resikere at bekymre de andre om min depression,og vil helst have at alle er glade"
    mc "sayori du er den bedste ven man kunne ønske sig,hvorfor tror du at jeg altid valgte at være sammen med dig da jeg havet et valg"
    s "undskyld mc,jeg er så ked af at jeg fik dig til at blive bange"
    "hun begyndte at græde,tudefjæs"
    mc "det okay sayori,det helt normalt at kunne få depression af og til,men du burde at tage din depression alvorligt"
    s "du har nok ret,hvad skal jeg gøre mc,det gør så ondt"
    mc "vi har brug for at få dig til en pygolog om det her,de kan hjælpe dig"
    s "tror du virkelig det?"
    mc "jeg tror det ikke for jeg ved det"
    "hun var stadig trist,men fik det lidt bedre"
    s "tak mc,jeg elsker dig"
    mc "jeg elsker også"
    s "må jeg spøger dig om noget mc?"
    mc "ja selvføgelig"
    s "er du også forælsket i mig ligesom jeg er med dig?"
    mc "huh?,hvor langtid har du været det?"
    s "det har jeg været længe nu"
    mc "okay jeg vil give dig svaret nu"
    "nu skal du vælge det du vil sige,husk at de valg du træffer ændre din historie til endten lykkeligt eller trist,afhænget af dine valg"
    "men det viser det dig først i det næste spil jacob vil lave fordi han vil forsætte det i denn her histoire i det du har valgt"
    mc "hvordan ved du alt det lasse?"
    "jeg ved alt om jer,om hvor i bor og hvad i føler og tænker og hvad jeres svaghed er"
    mc "det lidt skræmmene"
    "det ved jeg,når men vælg nu hvad du vil sige til sayori"
    menu:
        "jeg er også forælsket i dig":
            s "mener du virkelig det"
            mc "ja selvføgelig mener jeg det,du er smuk og cute,og du har de pæneste bukser på,selv når de falder ned"
            "hvem er det nu der er dulled var"
            s "yay det var det jeg håbet på at du vil sige,tak mc"
            "i kramte hindaen og fik jeres første kys"
        "lad os bare være bedste venner":
            s "oh,jamen okay,lad os bare det hehe"
            "hun virket trist,det som om hun håbede på noget mere romantisk"
            mc "er du okay sayori?"
            s "jaja,jeg har det helt okay"
            "du viste at noget ikke stemte"
            mc "du skal bare vide at jeg vil altid være der for dig uanset hvad"
            mc "bare fordi at vi ikke bliver kærster betyder det ikke at vi ikke kan være sammen"
            s "du har ret mc,du betyder også meget for mig"
            "i kramte hindaen"
    mc "vi må nok heler skynde os til skolen"
    s "ja du har ret lad os skynde os så vi ikke får ballade"
    "i skyndte jer alt hvad i kunne"
    scene bg street
    s "åh nej jeg glemte at tage bælte på"
    "du så hun rødmet og holdte bukserne oppe"
    s "jeg havet vist ikke tid til at finde bæltet hehe,vi havet så travlt,men det min egen skyld"
    mc "det okay,måske skulle vi tilbage og hente det"
    s "nej det har vi nok ikke tid til,ellers kommer i ikke til tiden,men bareolig,jeg kan bare trække bukserne op"
    mc "okay,og hvis nogen mobber dig om dine buksefald,skal jeg nok sige noget til dem"
    s "du altid så sød mc"
    mc "ja jeg er ret fantastisk ik ehehe"
    "i gik hen mod skolen"
    scene bg school
    "desværre for jer så toy freddy jer der ude som ikke var kommet ind i classen inu"
    tf "når når når,i kommer forsendt til jeres classe,og det er imod reglerne"
    s "undskyld toy freddy,det min fejl,mc kom med mig bare for at hjælpe mig med at komme afsted"
    tf "det var pænt af ham,men du skal stadig betale en bøde for at komme for sendt sayori"
    s "oh okay jeg forstår"
    "sayori betalte toyfreddy hindes bøde,den kostet kun 50kr heldigvis"
    tf "når men i må heler skynde jer til klassen,freddy har ventet på jer i 2 minutter nu"
    mc "forstået toy freddy,vi skynder os"
    tf "godt,og næste gang så kom til tiden"
    s "det skal vi nok"
    "i tog til klassen hvor freddy desvære virket lidt skuffet over at i ikke kom til tiden"
    scene bg class_day
    f "hey hvor har i været?,jeg har ventet enda i 4 minutter"
    h "hvordan kan du overhovedt tage det slemt,det jo kun 4 minutter de er forsinket i!"
    f "bland dig udenom snegl!"
    s "undskyld freddy,det min skyld,jeg er grunden til at vi kom forsendt"
    f "hvorfor dog det,du plejer altid at komme til tiden"
    s "det for pingligt at sige"
    fx "luuuu jeg ved hvad det er"
    f "stille dul!,jeg snakker med sayori ikke dig!"
    fx "hun taber"
    f "jeg sagde STILLE!"
    s "tak for at holde min hemmelighed hemmeligt"
    f "hvad mener du,oh når ja,det sandt,jeg er god til at holde på hemmeligheder,jeg er jo den bedste lære jo,så tak for det sayori"
    h "det var ingeng gang det hun sagde"
    f "stille snegl!,lad mig nyde øjeblikket!"
    f "når men idag skal vi nok mega sjovt"
    h "oh nej,er det matematik"
    f "nej noget meget bedre"
    h "what virkelig?"
    f "ja selvføgelig lille snegl,vi skal nemlig have teater"
    h "det lyder faktisk....sjovt"
    f "ja selvføgelig det var jo trosalt min ide"
    h "det var ikke lige helt det jeg"
    f "når men i efter jeres undervisning med glitchtrap og spise pausen,skal jeg være jeres lærer til teateret,i får mere at vide når vi når der til"
    h "åh nej ikke glitch trap igen"
    f "hov sagde jeg glitchtrap,nej nej en meget bedre lærer skal undervise jer"
    h "nice"
    f "ja og ham der skal undervise jer nu er"
    "toy freddy kom ind"
    tf "mig"
    h "må jeg græde nu"
    f "nej lille tudefjæs,ingeng gider at høre på en tudeprins"
    f "når jeg går igang hav det sjovt ahhaha"
    h "det får vi så ikke"
    "freddy gik ud af klassen og toy freddy stod klar til at undervise jer"
    tf "idag skal vi have en sjov undervisning"
    h "lad mig gætte,kunst?"
    tf "nej noget meget bedre,i får quiz time"
    h "seriøst!,nu kan det da heler ikke blive værre!"
    tf "når ja,og du skylder mig 400kr mere for at være irriteret helpy"
    h "jeg hader den her skole"
    mc "what,hvor er vanny,hun var der kun mandags"
    tf "oh vanny?,når ja jeg glemte at hun fandtes"
    mc "...?????"
    tf "når men nu til noget der er vitgiere in hinde banny hvad hun nu hed"
    tf "vi starter med dig der"
    h "jeg har faktisk et navn"
    tf "når ja lille snegl hed du,så lille snegl,hvem i fantasi historen har sovet i 1000år"
    h "hvorfor er det altid mig der får de videnskabs spørgsmål!"
    tf "fordi du skal blive kloger jo,og også fordi at jeg hader dig"
    h "er det titansne?"
    tf "ej hvor du trash helpy,forkert svaret,det er illidan som sov i 1000år,og det bliver 50kr for at dumpe"
    h "what,siden hvornår har illidan været i fantasi!"
    tf "ja det viste du ikke fordi du er en lille dum baby snegl"
    h "jeg forstår heler ikke det der med at vi skal betale for at fejle!"
    tf "arh,det gør de heler ikke,det kun dig reglen gælder for"
    h "what!"
    tf "så det dig funtimebuks"
    fx "luuuu du kaldte mig buks,mit ynglings kæle navn"
    tf "du afbryder!,når men nu skal du gætte på det her,hvem er den mægtiste her?"
    fx "luuuu,det er buksernes bukser"
    tf "forkert,hvad der galt med dig,du svare heletiden bukser"
    fx "fordi bukser er en buks som er bukser"
    tf "det giver jo slet ingeng menning,det en bøde på 70kr for at være så dulled"
    fx "luuuuuu"
    tf "så det dig bonnie ponny hahaha hvor er jeg sjov"
    fb "nah"
    tf "når når når,prøver du svare mig imod,det bliver 120kr for at være uenig med læren"
    fb "what,den regel er der slet ikke"
    "i kunne høre at han gik i gang med at taste på noget"
    tf "kig bedre efter"
    fb "what du har lige tilføjet den"
    tf "nej,du skulle bare havet kigget bedre efter"
    fb "men der står at du har tilføjet den for 4 seckundter siden!"
    tf "stille ponny,200kr i bøde nu for at være sur"
    h "og nu ved du hvorfor jeg hader den her skole bonnie"
    tf "når bonny ponny,hvor mange burger har jeg spist i alt"
    fb "what den er jo umulig!,er det 100"
    tf "what,hvor du trash,forkert,jeg spiste 1000 burger,det burde du at kunne vide"
    h "what du tyk"
    tf "skal man nu fornæme mig,det bliver 500kr for at være flabed snegl"
    h "hmm hvad mon værst,selvmord eller at blive i den her skole for altid,det undre jeg mig faktisk over"
    tf "ingeng gider at høre på din menning snegl,når sayori,hvordan forhendre man bukser i at falde ned"
    h "helt ærligt!,børnehave spørgsmålllll!"
    s "det gøre man med et bælte"
    fx "luuuu det ved du alt om fordi du taber bukserne"
    tf "what!,først afbryder du mig og nu gøre du nar af en af mine ynglings elever,det bliver en bøde på 800kr!"
    fx "luuuuu,jeg har næsten ingeng penge tilbage"
    tf "så må du bare ladevære med at bryde reglerne,når men vil sige at du bestod sayori"
    s "yay jeg gjor noget godt"
    tf "tja,det kunne man vist godt sige,du svaret hvertfald rigtigt"
    tf "din tur natsuki,hvem er batmans ærkefjende"
    h "det sjove ved det er at du altid giver natsuki børnehave spørgsmål!"
    n "det må være jokeren"
    tf "det rigtigt,flot klaret"
    tf "så det dig yuri,hvem var den udvalgte i starwars filmene"
    y "var det ikke anakin?"
    tf "det rigtigt flot klaret"
    h "seriøst,det kunne et barn svare på"
    tf "det ikke alle der kender starwars"
    h "ikke det!,det er en af de mest probolere film!"
    tf "når når når,du prøvet både at rette mig og du bliv irriteret,det en bøde på 800kr"
    h "det burde jeg at havet set komme"
    tf "så det dig svampebob,hvem laver pjatte jokes?"
    sb "bahahhah,det må være freddy"
    tf "hvor vover du at tale såden om freddys jokes.du dumper,plus du skal betale 500kr i bøde for at være flabed mod freddy"
    sb "bahahahah,nu bliver jeg mere fattig"
    tf "hvorfor griner du af det?,du bliver jo straffet"
    sb "jeg synes alt er sjovt bahahahaha"
    tf "hvad hvis nu en truet dig?"
    sb "så synes jeg at det stadig er sjovt bahahahaha"
    tf "??????"
    tf "ihvertfald er det din tur ayano,hvad er hovedstaden i danmark"
    ay "nemt,det er københavn"
    tf "det rigtigt flot klaret"
    ay "jeg viste det fordi at jeg"
    tf "jaja vi ligeglade,du har bestået"
    tf "din tur akira,hvem er den mest grimme i verdnen"
    ak "det må være pumbaa"
    tf "det rigtigt,pumbaa er omega grim og vi elsker at hade ham"
    br "jeg synes ellers at han er smuk ahohoh"
    tf "jamen det betyder jo bare at der noget galt med dig så"
    br "ej du,har du husket at tage dem på du"
    fx "luuuu det ligesom bukser"
    tf "når men så det dig sakura,hvem siger the jokes on you"
    sa "det må være shago"
    tf "flot klaret sakura"
    tf "din tur bedste mor gris,hvem græder allemest mærkeligt"
    br "det må være rowen,han lyd som et mærkeligt dyr ahohoh"
    tf "det rigtigt flot klaret"
    br "upser"
    tf "så er vist timen overstået,i har frikvater nu små børn"
    "toy freddy pakket sine ting sammen og gik ud for at spise"
    h "endelig har vi ham ikke mere"
    mc "han glemte at give mig en quiz"
    h "seriøst!,hvor det snyd at han bare lader dig være fri for det"
    br "det fordi at når man upser så upser man ahohoh"
    "i ignoreret bedste mor gris og gik ud til chica for at bestille mad"
    scene bg cantineIdle
    chica "hej idag har vi kun pizza fordi alt andet er usolgt"
    mc "okay så tager vi bare det"
    chica "det vliver 100 kr"
    "i tog til katinen for at spise"
    scene bg cantine
    "du sadte dig sammen med sayori og helpy"
    h "edtemindste er pizza da også lækkert"
    s "jeg elsker bare pizza"
    mc "samme her"
    "i spiste jeres pizze færdigt"
    mc "chica laver bare de bedste pizzaere"
    s "ja det er vildt lukus mad det her"
    h "ja,og det vildt sødt af jer at i vil betale for mig"
    mc "det var sålidt"
    h "så mc,hvordan gik det med dig og rekteren,du ved det med mig der sidder fast her"
    mc "kunne desværre ikke gøre noget ved det,han nægtede at lade dig få ordenligt fri uanset hvad jeg sagde til ham"
    h "trash rekter,men jeg er bare glad for at du prøvet,tak"
    s "mc er bare den sødeste"
    "sayori bliv lidt mere lun på dig,det tydeligt at hun er forælsket"
    "du valgte bare at tænke på noget andet og fukusere på det i skal snart skal lave"
    "klokken ringet,og i skulle til time igen og møde freddy ude i gangen"
    mc "tja så det vel nu vi skal have freddy"
    h "altså,han er bedre in toy freddy og alle de andre,tror faktisk det foxy jeg kan bedst lide"
    mc "hvorfor?"
    h "han er den eneste der kun er lidt sindsyg,mens alle de andre er mega syge i hoved"
    mc "du har en pointe"
    "i tog til skole gangen"
    scene bg hallWay
    f "hej små børn,det er nu i skal have teater undervisning,men enden vi tager afsted skal jeg lige forklare hvad det vil handle om"
    f "så det som det vil handle om er at en prinsese skal blive rede fra den onde gagamel,en rider og smulfer vil rede prinsesen"
    h "når,ikke mere in det"
    f "når ja tildsidst skal ridderen kysse prinsesen"
    ak "det vil passe godt til mig og mc"
    f "det ikke sikkert,jeg bestemmer rollerne her"
    ak "men jeg vil gerne være den der kysser ham"
    f "ja det bare surt for dig,for jeg vil stadig være den der vælger jeres skæbne"
    ak "det er uretfærdigt"
    f "stille!,når men kom med mig elever,så viser jeg jer et sted kaldes sukker øen"
    h "åh nej så begynder det"
    "mens i gik mod teateret begyndte i at minde helpy om flap jack introen"
    mc "hvad skal vi dog med den slags,for orden har jo alt"
    br "men ikke en sø fuld af sodavand og den mindste der smager af salt"
    ay "det farligt og risikabelt"
    sa "men eventyr er flot"
    s "for eventyr det altid godt"
    sb "og fuld af penge med slot"
    f "okay så det altså nok"
    h "endelig,jeg fik hovedpine"
    f "godt så lad os forsætte sangen forfra"
    h "NEJ!"
    "de drillet helpy med at synge sangen forfra igen"
    scene bg theater
    "i ankom til theateret"
    f "okay små børn,nu vil jeg dele jeres roller op"
    f "helpy du skal spille som gagamel"
    h "seriøst!,hvorfor skal jeg have den skåd rolle!"
    f "fordi det passer til dig"
    h "what!"
    f "mc du skal være ridderen"
    mc "nice tak,jeg skal gøre mit bedste"
    f "ja det skal du,for det her skal være perfekt!"
    f "og akira er prinsesen"
    ak "waow hvor romantisk,jeg glæder mig til kysset mc"
    "det tydeligt at hun flirter med dig"
    f "og i alle andre skal spille som smølferne"
    s "yay,jeg kan være en nuttet smølf"
    f "okay?,når men i må godt gå til opklædrings rummet,og her er jeres kustymer"
    h "hvor er mit kustyme?"
    f "du behøver ikke nogen kustyme,dit grimme udsennde passer dig perfekt som gagamel haha haaaaaa "
    h "what det flabed!"
    f "stille snegl!"
    h "værste skole nogensinde"
    f "når i må godt klæde jer om nu"
    "i gik ud til opklædrings rummet"
    scene bg costume
    "i kunne se at funtime foxy kigget på bukser,og sayori kigget efter et bælte fordi hun taber bukserne"
    "akira kom hen til dig"
    ak "skal jeg hjælpe dig med at finde et ridder kustyme?"
    mc "jeg tror at jeg har styr på det,men tak"
    ak "hm okay,jeg går ud og skifter til en smuk kjole,jeg vil sikkert blive mere udmåståelig"
    "hun gav dig et kærligt blik og gik mod opklædring rummet"
    scene bg changing_room
    "du begyndte at prøve at få ridder kustymet på"
    mc "whø hvor irriterende,de her ridder bukser er for store,jeg har brug for et bælte"
    "du kunne ikke finde et bælte"
    "pludseligt kunne du høre akiras stemme der ude"
    ak "har du brug for hjælp?"
    mc "bare bukserne der er lidt for store"
    ak "hehe jeg henter et bælte til dig"
    "du ventet i lidt tid og følte at det var lidt pinligt"
    mc "hvad skal jeg så gøre når hun kommer tilbage?"
    "du kunne lade hinde komme ind så hun kan give dig bæltet?"
    mc "nej tak,det virker for akavet når mine bukser glider ned"
    mc "wow,det godt nok dulled faktisk"
    "det er ret dulled faktisk ja"
    "du kunne høre at akira kom tætter på"
    ak "jeg har fundet et bælte til dig mc,må jeg komme ind?"
    menu:
        "ja":
            ak "okay nu kommer jeg"
            "akira gik ind og hjalp dig med at få bæltet på"
            ak "sådan nu skulle dine bukser meget gerne blive oppe"
            mc "det føles ret pingligt på en måde,men tak"
            ak "det var sålidt,jeg vil gøre alt for en smuk dreng som dig"
            mc "vi burde nok at gå ud nu"
            ak "ja du har ret"
            "i gik ud af rummet"
        "nej":
            ak "okay øv,men hvordan skal jeg så give dig bæltet?"
            mc "bare skub den her ind"
            ak "okay"
            "hun skubbet bæltet ind i rummet du var i"
            mc "tak akira"
            ak "det var sålidt søde mc,jeg venter på dig her ude"
            "du tog bæltet på og gik ud af rummet"
    scene bg costume
    "da du gik ud så du akria i en fin blå kjole"
    ak "når hvas synes du kære?"
    mc "det passer dig godt"
    ak "tak søde,hvordan går det med bukserne"
    mc "det går helt fint,og tak for hjælpen"
    ak "det var sålidt søde mc"
    mc "um,hvorfor bliver du ved med at kalde mig søde eller smukke?"
    ak "det fordi jeg elsker dig fjolle hehe"
    mc "men vi er jo bare venner"
    ak "det ved jeg,men før eller siden vil du vælge en kærste,det en del af spillet"
    mc "vent hvordan ved du hvad der vil ske?"
    ak "det finder du ud af senere,men lige nu skal vi fukusere på nuet"
    s "um mc,jeg taber bukserne,og har stadig mit bælte der hjemme fordi jeg ikke noget at tage det på i morges som du sikkert husker"
    "du kunne se at sayori holdte på sine bukser og smilte helt flovt"
    ak "der er bælter over til højre der"
    s "tak akira"
    ak "det var da sålidt"
    "sayori gik mod til højre mens hun trak bukserne op flere gange og ledte efter et bælte"
    "efter i alle bliv færdige med at tage jeres kustymer på gik i ud til freddy"
    scene bg theater
    fx "luuuu jeg har lige fået bukser på"
    f "du ret dulled men okay,godt i alle er klædt på"
    f "nu skal i bare øve jer,og huske det skal gå som jeg har planlagt det,forstået!"
    "i alle nikket ja til freddy"
    f "godt,okay til at starte med skal i smølfer opføre jer som nogen er glade,og husk at i skalsynge smølfe sangen"
    "de begyndte at synge smølfe sangen mens de gik rundt og fik det til at lige at de arbejdet"
    f "perfekt,og så det nu at du skal træde ind helpy som den onde gagamel, og du skal virke ondskabsfuld"
    h "hahaha jeg er den fæle troldmand gagamel,nu skal jeg fange jer smølfer"
    f "nice,jeg sagde jo du passet perfekt til at være den grimme troldmand haha"
    f "og nu skal jer som spiller smølferne gå i panik og få det til at se rigtig dramatisk ud"
    "de begyndte at gå i panik"
    f "godt perfekt,og nu skal i så prøve at finde ridder mc"
    sa "jeg har en ide,kom med mig smølfer,vi må skynde os og lede efter ridder jacob som kan besjere den onde gagamel,og at rede os og prinsesen"
    f "NEJ!,det smukke prinsse du skulle sige øjj!"
    sa "vi må skynde os og lede efter ridder jacob som kan besjere den onde gagamel og at rede den smukke prinsesse"
    f "godt,og nu er i kommet til ridderen,og nu skal du mc virke moden og følge den manoskrift jeg har givet dig"
    mc "hvad er der sket små smølfe venner"
    sa "åh store mægtige ridder,hjælp os med at stoppe den fæle gagamel,han har fanget nogen af vores smølfer og den smukke prinssese"
    mc "frygt ej mine små venner,jeg vil hjælper jer med at besejre den fæle troldmand og befire jeres venner og min smukke prinssese"
    f "godt klaret,og nu er vi kommet til den store finale!,det er nu at gagamel og ridder mc mødes angsigt til ansigt og skulle kæmpe"
    f "og husk det til døden"
    h "vent hvad!,er du sindsyg!"
    f "jeg mente ikke at i vil dø bogstavligt dumme snegl!"
    mc "du vil nu blive beseret fælde gagamel,giv op eller mærk min vrede"
    h "haha,tror du virkelig at du kan stoppe mig,jeg er den mægtige gagamel"
    mc "vi får se"
    f "i kæmpet mod hindaen og det endte med at mc besejret gagamel,den grimme troldmand"
    h "behøver du virkelig at kalde mig grimme"
    f "hold dig til manoskriftet!"
    h "oh nej du har besjeret mig"
    mc "du vil nu dø for retfærdigheden"
    f "ridder mc svinget sit svære og stak den ned på grimme gagamel"
    h "arrrrrh,edvak"
    f "nu befriet ridderen smølferne og den smukke prinsese"
    s "tusind tak for at rede os trapper ridder,vi smølfer er evig taknemmelige"
    mc "tak,jeg er glad for at kunne hjælpe"
    ak "min helt"
    f "det nu at i skal kysse,men kun et lille et,forstået!"
    "i begyndte at kysse lidt og akira bliv så glad for det en eller anden grund"
    f "godt så skal i gøre det igen snart,"
    h "og hvad mener du med det?"
    f "øjjj helpy,du forstår bare heler ikke noget vel!"
    h "trash skole"
    f "der kommer nemlig snart publikum,og der skal i gøre som i lige har øvet,men der lige en fejl du begik sakura"
    sa "um hvad er det?"
    f "du kaldte ridderen for jacob!,han hedder altså ridder mc!"
    sa "åh det må du undskylde freddy"
    f "det okay,bare husk at hold dig til mit manoskrift"
    h "det virket ellers som om at du mente det surt"
    f "bland dig udenom snegl!"
    h "hvordan gik det overhovedt til at jeg gik i den her trash skole"
    "efter noget tid kom publikummet"
    f "godt de er kommet nu,okay start som i øvet"
    "i gjor jer forberet på at freddu siger til"
    f "klar og action!"
    "i gik i gang med jeres rolle spil foran en masse mennesker og animatronics selvføgelig"
    "det bliv et meget spændene theater stykke,og publikummet hjuplet"
    "helt tilsidst da du som ridder stoppet den onde troldmand,befriet du smølferne og prinsesen"
    "smølferne takket dig,og dig og prinsessen kysset,og publikummet blivet helt rørt"
    f "i gjor det så flot små børn,nu må i godt tage til opklædens rummet og få jeres kustymer af"
    fx "luuu jeg har ikke lyst til at tage bukserne af"
    fb "det lyd ret akavet"
    fx "luuuuu"
    f "du skal tage bukserne af!,det er ikke dine,det skolens!"
    fx "luuu,så bliver jeg halv nøjen"
    f "hvad snakker du om,robotter går normalt ikke i bukser!,og det var ingeng gang menningen at du skulle tage dem på"
    fx "skal jeg tage dem af her?"
    f "nej din spasser!,du skal gøre det i prøve rummet dumme dul!"
    "i gik alle hen til tøj rummet"
    scene bg costume
    ak "det var et smukt øjeblik mc"
    "hun kigger forælsket på dig"
    mc "heh,det var jo bare skuespil angåene kysset"
    ak "er du sikker på at det ikke var begrund af noget andet også"
    "hun gav dig et kærligt blik"
    mc "jeg er sikker"
    ak "åh søde søde mc,altids så kosbar,jeg kan lide det"
    mc "okay jeg går ind og tager det her rustning af nu"
    ak "fint nok,jeg skal vist også have den her kjole af"
    "du gik ind i prøve rummet"
    scene bg changing_room
    "du begyndte at tage din kustyme af"
    mc "puha det var godt nok varmt med den ridder kustyme"
    "det jo klart,du havet jo 2 par bukser på"
    mc "okay du ret dulled lige nu"
    "er jeg?"
    mc "ja,lige før"
    "du har ret,jeg var ret dulled,måske er det en dulle mod du spiller lige nu"
    mc "hvorfor er der så mange der kalder det her for et spil?"
    "jeg ved ikke hvorfor de andre gør det,når jo det ved jeg,for jeg ved alt om jer"
    mc "det lidt creepy"
    "creeper,oh mand"
    mc "??????"
    "jeg kan fortælle dig at grunden til at vi siger at det er et spil er bare for at drille dig"
    mc "arh okay,så forstår jeg det bedre"
    "eller mener vi det faktisk hmmmmm,en gåde"
    mc "okay,kan vi komme vidre"
    "det var flabet sagt"
    mc "??????"
    "du gik ud af prøve rummet og mødtes med sayori og akira"
    scene bg costume
    ak "hej mc,min smukke ridder"
    s "eh,hvordan kan du vide om det ikke er mig han elsker?"
    ak "fordi han elsker mig"
    mc "det har jeg aldrig sagt at jeg gjor"
    ak "men vi kyssede før"
    mc "fordi det var en del af theateret"
    ak "var det nu det hmmm"
    s "lad os gå mc,det her føles forkert"
    ak "fint,bare vent til fredag,der skal han nok vælge mig som kærste,vent at se!"
    "hun gik væk fra jer"
    s "er du okay mc?"
    mc "jeg klare den,jeg har dig"
    "hun bliv helt glad og rødmet af det"
    s "jeg er også glad for at jeg har dig,faktisk så håber jeg at det bliver mig som bliver din kærste hehe"
    mc "jeg kan ikke love noget,men vi får at se hvad der sker den dag hvor jeg skal vælge en kærste,som jeg en eller aden grund er tvunget til"
    "hun kigget forvirret og smilte igen bagefter"
    mc "men du ved godt at det bælte du bruger nu er skolens ik?"
    s "når ja,jeg lånte det bare for at ungå at tabe bukserne foran hele folket"
    mc "men du nok nød til at aflevere det igen"
    s "hvor nederen,så må jeg bare leve med at tabe bukserne"
    mc "sker det virkelig så ofte?"
    s "ja,jeg taber bukserne heletiden,det mega irriterende faktisk"
    mc "godt at du kan bruge dit eget imorgen så"
    s "hehe ja,for den her dag er ret pinlig for mig"
    "en eller anden grund bliv hun helt flov"
    "hun tog bæltet af og lagte det tilbage"
    "i gik sammen og undervejs glid sayoris bukser ned heletiden mens hun trak dem konstant op"
    scene bg theater
    f "godt,nu skal vi bare have spise pause"
    fx "haha,prøv at se sayori,hun taber bukserne heletiden llululululu"
    f "stille dul!"
    fx "luuu men hun"
    f "NEJ STOP JEG MENER DET,INGENG GIDER AT HØRE PÅ DIN DULLEDE KOMMENTAR!"
    s "tak freddy"
    f "det var sållidt,jeg magter ikke at skulle høre på hindes dullesnak"
    h "det første gang at jeg er enig med freddy"
    f "når men jeg vil tage til lære værelset og få noget at spise,tag hen til katinen elever"
    "i alle tog til katinen,og hen til chica for at bestille"
    scene bg cantineIdle
    chica "hej,hvad vil du bestille idag?"
    "nu skal du vælge mad,hvis du ikke viste det"
    mc "jeg viste det godt,jeg hørte hinde selv"
    menu:
        "pasta med kethub 25kr":
            chica "det bliver 50kr"
            "du gik over til katinen for at spise"
        "salat med kylling 30kr":
            chica "det bliver 60kr"
            "du gik til katinen for at spise"
        "pizza med kebab 100kr":
            chica "det bliver 200kr"
            "du bruger mange penge"
            "du gik over til katinen for at spise"
    scene bg in_cantine
    "du gik over til de andre og spiste,"
    mc "hmmmm,hvem skulle jeg mon spise sammen med idag?"
    menu:
        "sayori":
            "du gik mod sayori"
            "sayori griner lidt for sig selv"
            s "Okay, MC, jeg har en historie, der vil få dig til at tabe din mad!"
            "du kigger op fra din bakke"
            mc "Åh nej, hvad nu? Er det endnu en af dine… episke Sayori-historier?"
            "sayori nikker ivrigt"
            s "Du ved det! Hør her! Så… det var den der ene gang, hvor jeg havde travlt på vej til skole… Jeg havde lidt for travlt, faktisk"
            "du løfter et øjebryn,hvorfor taler jeg så mrækeligt?"
            mc "hvor travlt?"
            "sayori bliver helt rød i kinderne,men griner stadig"
            s "Så travlt, at jeg glemte at binde min bukser ordentligt!"
            "du stopper midt i at tage en bid"
            mc "åh nej,hvad er der sket?"
            "sayori klapper i hænderne sammen og ler højt"
            s "De faldt ned, MC! Lige foran butikken, hvor ALLE kunne se det! Jeg stod bare der med min skoletaske, og så… BAM! Bukserne nede om anklerne"
            "du prøver at holde et grin tilbage"
            mc "og hvad gjorte du så?"
            "sayori ligger hovedt på skrå og smiler bredt"
            s "Hvad tror du? Jeg samlede dem op og råbte: 'Det er en ny mode! I burde prøve det!' Og så løb jeg væk"
            "du griner højt,hvor er i bare dulled"
            mc "Det lyder så meget som dig, Sayori. Hvordan er du så… afslappet over det nu?"
            s "Hvorfor ikke? Jeg mener, det var pinligt, men det er også ret sjovt, når jeg tænker tilbage på det! Hvis jeg ikke kan grine af det, hvad kan jeg så gøre?"
            mc "Du har en måde at gøre alting mindre alvorligt på. Det er faktisk ret imponerende."
            s "Det er fordi jeg ved, at livet er for kort til at bekymre sig om småting! Plus, når jeg deler historien, får jeg også dig til at grine og det gør det hele det værd!"
            mc "Okay, Sayori. Du vinder. Men næste gang, så husk at tjekke dit tøj, inden du løber ud af døren."
            s "Aftale! Men hvis det sker igen, så har jeg i det mindste endnu en sjov historie at fortælle!"
            "klokken ringet og i skulle til klassen"
            mc "det var ellers så hyggeligt og dulled"
            s "haha ja,men næste gang skal jeg nok huske mit bælte"
            "i gik ud til skole gangen"
        "helpy":
            "du gik over til helpy"
            mc "hey helpy er du okay?"
            "helpy trækker skuldren uden at se op"
            h "Tja… så okay, som det kan være, når verden hader én."
            mc "hvad skete der nu?"
            h "Lad os se… Første time var en katastrofe. Læreren bad mig om at læse højt, og selvfølgelig snublede jeg over ordene"
            h "Alle grinede. Derefter smed jeg min penalhus ned på gulvet… igen. Og for at gøre det værre"
            h "så tog læreren mig til side og sagde, at jeg 'burde gøre en større indsats'"
            "du kigger alvorligt på ham"
            mc "Det lyder hårdt. Men det er ikke fair, at læreren siger sådan til dig. Du prøver jo."
            h "Måske… Men det føles bare som om, jeg ikke er god nok. Og hvad er pointen i at prøve, hvis det aldrig bliver bedre?"
            "du rykker din stol tætter på ham"
            mc "Helpy, jeg ved, det føles sådan lige nu, men det er ikke sandt. Du er god nok. Måske har du bare haft en rigtig dårlig dag"
            mc "eller uge. Men det betyder ikke, at det altid vil være sådan."
            "helpy ser op med et svagt smil"
            h "Du lyder næsten som en motiverende bog, du ved det godt, ikke?"
            "du griner blidt"
            mc "Måske, men det betyder ikke, det ikke er sandt. Hey, hvad siger du til, at vi finder noget, der kan få dig til at grine? Noget til at lette humøret lidt."
            "helpy trækker på skuldren,lyder underligt hvis du spøger mig"
            h "Som hvad? Jeg er ikke så god til at have det sjovt, husker du?"
            mc "Okay, hvad med det her"
            mc "Efter vi har spist, så prøver vi at slå en verdensrekord i… at stable plastikkopper."
            mc "Eller… vi kan finde på en virkelig dårlig vittighed, der er så dum, at den får os begge til at grine."
            "helpy kan ikke lade være med at smile"
            h "Du er virkelig dårlig til at finde på ideer, men… måske hjælper det. Bare lidt"
            mc "Så det er en aftale. Og husk, Helpy selvom du har uheldige dage, betyder det ikke, at du er alene om at klare dem. Jeg er her"
            "helpy kigger væk med let røde kinder"
            h "Du lyder skør. Men… tak."
            "klokken ringet og i skulle til den sidste time"
            h "okay så længe det ikke er toy freddy,så klare jeg den"
            mc "ja toy freddy er skåd,lad os tage til time"
            "i kom mod gangen"
        "natsuki":
            mc "Så… hvad har du med i dag? Noget fancy? Eller er det en af dine 'jeg havde travlt'-madpakker?"
            "natsuki Kigger hurtigt væk, men man kan se, at hun smiler lidt"
            n "tsk, hvorfor skulle det interessere dig? Det er bare ris og grøntsager. Ikke noget særligt"
            "du læner dig frem,det kunne være sjovt hvis du faldt og slog dig"
            mc "Det lyder ret sundt. Helt anderledes end min kedelige sandwich"
            "natsuki Kigger på hans mad og sukker"
            n "Selvfølgelig spiser du en sandwich. Så standard."
            mc "Hvad kan jeg sige? Jeg er en simpel fyr med simple behov"
            "natsuki ruller med øjnene"
            n "Simpel er en pæn måde at sige kedelig på."
            "du Lader som om han er såret,sikkert bare for at se hindes bløde side"
            mc "Av, Natsuki. Jeg troede, vi var venner."
            "natsuki rødmet lidt,se selv efter,hvor er jeg bare sjov til at drille hinde"
            n "Hvem sagde, vi ikke er venner? Jeg mener bare, du kunne prøve lidt hårdere, når det kommer til mad"
            n "Bare fordi du ikke kan lave noget, betyder det ikke, du skal spise noget så… kedeligt."
            mc "Så hvad foreslår du? Skal jeg begynde at bage cupcakes som dig"
            "natsuki Sætter maden fra sig og ser på dig"
            n "Hmpf, som om du nogensinde kunne gøre det lige så godt som mig"
            n "Men det ville i det mindste være bedre end den her… sandwich-ting"
            mc "Okay, udfordring accepteret. Næste gang skal vi lave noget sammen, og så ser vi, hvem der laver det bedste"
            "natsuki Ser overrasket ud et øjeblik, men skubber hurtigt smilet væk"
            n "tsk, det er spild af tid. Men… hvis det betyder, jeg kan vise dig, hvor dårlig du er, så fint. Bare vær klar til at tabe."
            mc "Vi får se. Men hvis jeg vinder, skylder du mig en cupcake."
            "natsuki Kigger væk og gemmer sit smil"
            n "Som om det nogensinde ville ske. Men… okay. Aftale. Bare ikke begynd at græde, når jeg slår dig"
            "i kunne høre klokken ringe"
            mc "okay hvad siger du til at vi prøver at bage sammen igen på mandag?"
            n "det kan vi godt,men kom så,vi skal til time"
            "i gik mod gangen"
    scene bg hallWay
    "du så vanny er tilbage,men mistet et øje"
    mc "wow,er du okay vanny,hvad er der dog sket med dig?"
    






            































            
        




        

        
        
        
            
        





    









    








                


