label ch2_main:
    $ currentDay = "Tirsdag"
    scene bg sayori_bedroom
    play music t8
    "TIRSDAG"
    "i stod op og tog tøj på"
    s "godmorgen mc,har du sovet godt?"
    mc "ja,det har sovet mega godt"
    s "det da godt"
    mc "og tak for at lade mig overnatte hos dig,elsker dig højt som min bedste ven"
    s "du ved altid hvordan du får mig til at smile"
    mc "jeg er ret sulten lad os spise morgenmad"
    s "god ide min søde ven"
    "i gik ud i køkkenet for at tage noget at spise"
    scene bg kitchen
    "sayori tog noget yougurt og myslig frem meget mere fornuftige valg in du havet mandags"
    mc "det flabedt sagt lasse"
    "jeg siger blot bare sandheden"
    "i begyndte at spise jeres morgen mad,hvilket betyder at u spiser det lige nu"
    "bare så i ved det"
    s "jeg elsker bare yougurt"
    mc "det gør jeg også,det smager altid godt og er sundt"
    "i gik ud af huset"
    scene bg street
    s "ups jeg glemte mit bælte,jeg taber bukserne hehe hvor pinligt,jeg henter tager lige hjem for at hente det"
    mc "okay,jeg venter på dig her"
    s "tak det sætter jeg pris på"
    "hun gik hjem for at finde bæltet,hvor dulled kan hun lige være,og hvorfor går hun i bukser"
    mc "det ved jeg heler ikke,det ret dulled"
    "det er det ja,pludseligt kom rekter jacob frem og så dig og kom hen til dig"
    mc "oh hej rekter jacob"
    da "hej mc,godt at se dig,um hvad venter du på?,skal du ikke til skolen?"
    mc "jo,jeg venter bare på sayori"
    da "tja det typisk hinde at være lidt sendt på den,det sødt af dig at du altid er der for hinde"
    mc "tak jeg kan meget godt lide hinde"
    da "det forstår jeg godt,hun er en god pige"
    "der kom lidt vente stilhed"
    da "når jeg må heler tage afsted,ses,og helst ungå at komme forsendt til timen"
    mc "vi skal nok komme til tiden ses"
    "rekter jacob gik ind i sin bil og kørte afsted igen"
    "pludseligt kom sayori frem igen med bæltet på"
    s "såden,prøv at forstille dig at jeg tabte bukserne i klassen,hehe det vil være pinligt"
    mc "haha ja,men lad os komme afsted,det også lidt for dulled lige nu"
    "i tog straks hen mod skolen"
    scene bg school
    "foran skolen så i helpy oh hilste"
    mc "hej helpy"
    h "oh hej mc,godt at se dig"
    s "det også godt at se dig,jeg går bare ind i klassen nu,i 2 kan bare snakke lidt sammen nu"
    h "oh okay ses"
    "sayori gik ind i skolen"
    mc "føler at det vil blive en god dag"
    h "godt at du kan se det lyse i det,jeg håber bare at vi ikke får toy freddy eller baldi"
    mc "samme her,skal vi gå ind?"
    h "ja det må vi nok heler"
    "i gik ind i skolen"
    scene bg hallWay
    h "og vil bare sige tak for at du lytter til mig og vil bringe tid sammen med mig"
    mc "det var så lidt,jeg er glad for at hjælpe"
    h "du er den eneste ven jeg har,men det er da godt at jeg har dig så"
    mc "hvad med sayori?"
    h "alttså hun er også flink nok men,tror ikke at hun vil være min ven"
    mc "hvad siger du til at være sammen med mig og sayori hos mig når vi også er kommet hjem fra clubben"
    h "mener du virkelig det,vil i virkelig have mig med sammen med jer?"
    mc "ja det er det man har venner til"
    h "waow tak du den bedste ven man kunne ønske sig"
    "han gav dig et hurtigt kram og efter det gik i i klassen"
    scene bg class_day
    "i så rekter jacob stå der"
    "jeg tror at helpy snart vil føle sig snydt lige om lidt"
    da "velkommen alle små elever,idag sker der noget meget vildt og spændene"
    h "what,skal du undervise os idag,det vil hvertfald være en forbedring istedenfor de skræld lærer"
    da "haha nej,jeg har noget andet at tage mig til bagefter"
    h "selvføgelig har du det"
    "sagde helpy irriteret"
    da "jeg er kommet her for at respentere jer for 2 nye der skal gå i den her fantastiske skole"
    h "hoste lyd,skræld skole"
    da "stille snegl!,når men her kommer svampebob"
    sb "bahahaha,det mig jeg hedder svampebob,og jeg er mærkelig bahahaha"
    h "what yes endelig en lærer der er flink nok"
    da "haha du så dum helpy,nej han er bare en elev,ligesom jer bønder,jeres rigtige lærer kommer nu"
    "blækward kom ind fra døren"
    da "tag godt i mod blækward,han er jeres nye lærer,og han skal undervise jer idag"
    h "pls lad det være en god lærer din dumme trash skole"
    bd "hej elever,jeg vil smadre svampebob og jer andre hvis i fejler"
    da "som i kan se og høre er han en fremravene lære"
    h "what hørte du ikke lige hvad han lige sagde der!"
    da "jeg sagde,...STILLE SNEGL"
    h "jeg hader den her skole"
    da "når men i må have det godt,jeg må heler passe mit job i kontoeret,ses små børn,og blækward"
    bd "ses,jeg skal nok passe rigtig godt på mit nye job som lærer"
    "darthjacob tog ud igen og pludseligt kom bedste mor gris ind"
    br "ahohoho hva så der noobs,nu skal jeg rigtig irritere jer hverdag"
    bd "oh hvor godt vi lige fik en ny elev her"
    br "vent nej,jeg er da ikke..."
    bd "tie stille og tag en plads!"
    "bedste mor gris var stille og gjor som blækward sagde"
    bd "okay hør godt efter små børn,idag skal i skrive jeres egen historie"
    mc "det lyder sjovt"
    bd "godt sagt mc,jeg tror at du måske vil blive min ynglings elev"
    h "seriøst!,du har jo lige mødt ham!"
    bd "ja,men han prokker sig ikke ligesom dig lille snegl"
    h "hvorfor skal i alle kalde mig for snegl!"
    bd "STILLE ELLER JEG SMADRE DIG!"
    h "...?"
    bd "det tænkte jeg nok,når børn,KOM SÅ IGANG!"
    "i begyndte at skrive jeres historie ned,nu skal du vælge en historie som du vil skrive om"
    bd "når ja glemte at nævne at hvis i skriver en dårlig eller kedelig eller en historie der ikke giver nogen menning,dumper i"
    menu:
        "shrek og hans sump":
            mc "okay her kommer min historie om shrek om hans sump"
            "du rejste dig op og læste det højt"
            mc "Det var en tidlig morgen i Shreks sump. Duggen hang stadig på de snoede træer"
            mc "og der lød et par tilfredse kvæk fra sumpens frøer."
            mc "Shrek snorkede højlydt i sin seng, mens Fiona og Æsel allerede var oppe og i gang med at lave morgenmad."
            mc "Pludselig bankede det voldsomt på døren. BANG BANG BANG"
            mc "shrek bliv irriteret og de forsatte med at banke på døren,så han gik ned og åbnet for dem"
            mc "det var nogen små dværge"
            mc "Shrek! Hjælp os! råbte de i munden på hinanden"
            mc "Jeg er ikke en helt, og jeg er bestemt ikke jeres babysitter,"
            mc "mumlede Shrek, men Fiona og Æsel stod allerede nysgerrigt bag ham."
            mc "vil du ikke nok hjælpe os sagde dvagene"
            mc "shrek sagde så,hvad er det i overhovedt skal have hjælp til?"
            mc "der er en ond trold mand ved navn grimsfjæs,han minder om gagamel og tror at vi er smølfer"
            mc "og derfor jagter han os sagde dvagene"
            mc "okay fint hvor finder jeg ham i kalder grimfjæs,sagde shrek"
            mc "du finder ham ude i skoven sagde de"
            mc "okay jeg reder jer,men kun den ene gang okay!,sagde shrek meget bestemt"
            mc "yep vi lover det sagde de"
            mc "godt og hold jer væk fra min sump,ellers vil jeg spise jer til morgen mad sagde han truene"
            mc "de niggede og gemte sig et sted hvor grimfjæs ikke kan finde dem"
            mc "shrek fandt den onde grimfjæs og gjor så klar til kamp"
            mc "grimfjæs sagde ha,en simpel trold kan ikke besejere mig den mægtige grimfjæs"
            mc "det skal du ikke være så sikker på sagde shrek"
            mc "grimfjæs sagde så,oh jeg skal give dig sagde jeg alaka"
            mc "han skulle til at skyde shrek med sin magiske stav"
            mc "shrek kom løbene og slog hans grimme fjæs"
            mc "åh nej,min eneste svaghed at blive slået i mit grimme fjæs,sagde den onde trold mand og endte med at dø"
            mc "lol han var weak sagde shrek og tog hjem igen for at slappe af igen og dvagene var redet slut"
            bd "altså den gav ingen menning,men det var nu ret underholdene,godt gået mc du består"
            mc "åh tusiden tak blækward"
            "blækward gik hen til helpy for at høre hans historie"
        "historien om darthjacobs barndom":
            mc "okay her kommer historien om darthjacobs barndom"
            "du rejste dig op og læste det højt"
            mc "I en fjern, fjern galakse, på en planet ingen længere husker navnet på"
            mc "blev lille Jacos født under en himmel fyldt med storme"
            mc "Allerede som barn kunne man mærke, at noget særligt boede i ham"
            mc "Han elskede mørke huler og stille aftener"
            mc "hvor vinden susede mellem træerne, og han kunne høre planetens dybe, dunkle ekko."
            mc "Jacos voksede op i en lille landsby, hvor han altid skilte sig ud"
            mc "Mens de andre børn legede og grinede, sad Jacos alene og studerede skyggerne"
            mc "der dansede på væggene"
            mc "Han er bare lidt sær, sagde de voksne, men ingen forstod, at Jacos kunne føle noget dybere. Noget kraftfuldt."
            mc "n dag, da han var blot 10 år gammel, fandt Jacos en gammel rusten hjelm i en forladt hule"
            mc "Da han tog den op, strømmede en mærkelig kulde gennem hans krop"
            mc "Han mærkede, hvordan en stemme, langt væk, hviskede Du er skabt til noget større, Jacos. Du er mørkets arving."
            mc "Fra den dag begyndte alt at forandre sig"
            mc "Hans hænder kunne flytte små sten uden at røre dem"
            mc " Folk i landsbyen blev nervøse, når han gik forbi"
            mc "Selv træerne syntes at bøje sig let, når Jacos nærmede sig. Han følte sig ikke længere hjemme."
            mc "En nat forlod Jacos landsbyen, iført den gamle hjelm"
            mc "der nu passede perfekt"
            mc "Han vidste ikke, hvor han var på vej hen"
            mc "men han fulgte stemmen, der kaldte fra stjernerne"
            mc "Snart ville han blive DarthJacos, den skikkelse, galaksen aldrig ville glemme"
            mc "slut"
            bd "den var lidt mærkelig,faktisk for mærkelig,du dumpet"
            "blækward gik hen til helpy for at høre hans historie"
    h "den her historie handler om en helpy som lider af en trash skole"
    
                

















    return