label ch2_main:
    $ currentDay = "Tirsdag"
    scene bg sayori_bedroom
    play music t8
    "TIRSDAG"
    "i stod op og tog tøj på"
    s "godmorgen mc,har du sovet godt?"
    mc "ja,det har sovet mega godt"
    s "det da godt"
    mc "og tak for at lade mig overnatte hos dig,elsker dig højt som min bedste ven"
    s "du ved altid hvordan du får mig til at smile"
    mc "jeg er ret sulten lad os spise morgenmad"
    s "god ide min søde ven"
    "i gik ud i køkkenet for at tage noget at spise"
    scene bg kitchen
    "sayori tog noget yougurt og myslig frem meget mere fornuftige valg in du havet mandags"
    mc "det flabedt sagt lasse"
    "jeg siger blot bare sandheden"
    "i begyndte at spise jeres morgen mad,hvilket betyder at u spiser det lige nu"
    "bare så i ved det"
    s "jeg elsker bare yougurt"
    mc "det gør jeg også,det smager altid godt og er sundt"
    "i gik ud af huset"
    scene bg street
    s "ups jeg glemte mit bælte,jeg taber bukserne hehe hvor pinligt,jeg henter tager lige hjem for at hente det"
    mc "okay,jeg venter på dig her"
    s "tak det sætter jeg pris på"
    "hun gik hjem for at finde bæltet,hvor dulled kan hun lige være,og hvorfor går hun i bukser"
    mc "det ved jeg heler ikke,det ret dulled"
    "det er det ja,pludseligt kom rekter jacob frem og så dig og kom hen til dig"
    mc "oh hej rekter jacob"
    da "hej mc,godt at se dig,um hvad venter du på?,skal du ikke til skolen?"
    mc "jo,jeg venter bare på sayori"
    da "tja det typisk hinde at være lidt sendt på den,det sødt af dig at du altid er der for hinde"
    mc "tak jeg kan meget godt lide hinde"
    da "det forstår jeg godt,hun er en god pige"
    "der kom lidt vente stilhed"
    da "når jeg må heler tage afsted,ses,og helst ungå at komme forsendt til timen"
    mc "vi skal nok komme til tiden ses"
    "rekter jacob gik ind i sin bil og kørte afsted igen"
    "pludseligt kom sayori frem igen med bæltet på"
    s "såden,prøv at forstille dig at jeg tabte bukserne i klassen,hehe det vil være pinligt"
    mc "haha ja,men lad os komme afsted,det også lidt for dulled lige nu"
    "i tog straks hen mod skolen"
    scene bg school
    "foran skolen så i helpy oh hilste"
    mc "hej helpy"
    h "oh hej mc,godt at se dig"
    s "det også godt at se dig,jeg går bare ind i klassen nu,i 2 kan bare snakke lidt sammen nu"
    h "oh okay ses"
    "sayori gik ind i skolen"
    mc "føler at det vil blive en god dag"
    h "godt at du kan se det lyse i det,jeg håber bare at vi ikke får toy freddy eller baldi"
    mc "samme her,skal vi gå ind?"
    h "ja det må vi nok heler"
    "i gik ind i skolen"
    scene bg hallWay
    h "og vil bare sige tak for at du lytter til mig og vil bringe tid sammen med mig"
    mc "det var så lidt,jeg er glad for at hjælpe"
    h "du er den eneste ven jeg har,men det er da godt at jeg har dig så"
    mc "hvad med sayori?"
    h "alttså hun er også flink nok men,tror ikke at hun vil være min ven"
    mc "hvad siger du til at være sammen med mig og sayori hos mig når vi også er kommet hjem fra clubben"
    h "mener du virkelig det,vil i virkelig have mig med sammen med jer?"
    mc "ja det er det man har venner til"
    h "waow tak du den bedste ven man kunne ønske sig"
    "han gav dig et hurtigt kram og efter det gik i i klassen"
    scene bg class_day
    "i så rekter jacob stå der"
    "jeg tror at helpy snart vil føle sig snydt lige om lidt"
    da "velkommen alle små elever,idag sker der noget meget vildt og spændene"
    h "what,skal du undervise os idag,det vil hvertfald være en forbedring istedenfor de skræld lærer"
    da "haha nej,jeg har noget andet at tage mig til bagefter"
    h "selvføgelig har du det"
    "sagde helpy irriteret"
    da "jeg er kommet her for at respentere jer for 2 nye der skal gå i den her fantastiske skole"
    h "hoste lyd,skræld skole"
    da "stille snegl!,når men her kommer svampebob"
    sb "bahahaha,det mig jeg hedder svampebob,og jeg er mærkelig bahahaha"
    h "what yes endelig en lærer der er flink nok"
    da "haha du så dum helpy,nej han er bare en elev,ligesom jer bønder,jeres rigtige lærer kommer nu"
    "blækward kom ind fra døren"
    da "tag godt i mod blækward,han er jeres nye lærer,og han skal undervise jer idag"
    h "pls lad det være en god lærer din dumme trash skole"
    bd "hej elever,jeg vil smadre svampebob og jer andre hvis i fejler"
    da "som i kan se og høre er han en fremravene lære"
    h "what hørte du ikke lige hvad han lige sagde der!"
    da "jeg sagde,...STILLE SNEGL"
    h "jeg hader den her skole"
    da "når men i må have det godt,jeg må heler passe mit job i kontoeret,ses små børn,og blækward"
    bd "ses,jeg skal nok passe rigtig godt på mit nye job som lærer"
    "darthjacob tog ud igen og pludseligt kom bedste mor gris ind"
    br "ahohoho hva så der noobs,nu skal jeg rigtig irritere jer hverdag"
    bd "oh hvor godt vi lige fik en ny elev her"
    br "vent nej,jeg er da ikke..."
    bd "tie stille og tag en plads!"
    "bedste mor gris var stille og gjor som blækward sagde"
    bd "okay hør godt efter små børn,idag skal i skrive jeres egen historie"
    mc "det lyder sjovt"
    bd "godt sagt mc,jeg tror at du måske vil blive min ynglings elev"
    h "seriøst!,du har jo lige mødt ham!"
    bd "ja,men han prokker sig ikke ligesom dig lille snegl"
    h "hvorfor skal i alle kalde mig for snegl!"
    bd "STILLE ELLER JEG SMADRE DIG!"
    h "...?"
    bd "det tænkte jeg nok,når børn,KOM SÅ IGANG!"
    "i begyndte at skrive jeres historie ned,nu skal du vælge en historie som du vil skrive om"
    bd "når ja glemte at nævne at hvis i skriver en dårlig eller kedelig eller en historie der ikke giver nogen menning,dumper i"
    menu:
        "shrek og hans sump":
            mc "okay her kommer min historie om shrek om hans sump"
            "du rejste dig op og læste det højt"
            mc "Det var en tidlig morgen i Shreks sump. Duggen hang stadig på de snoede træer"
            mc "og der lød et par tilfredse kvæk fra sumpens frøer."
            mc "Shrek snorkede højlydt i sin seng, mens Fiona og Æsel allerede var oppe og i gang med at lave morgenmad."
            mc "Pludselig bankede det voldsomt på døren. BANG BANG BANG"
            mc "shrek bliv irriteret og de forsatte med at banke på døren,så han gik ned og åbnet for dem"
            mc "det var nogen små dværge"
            mc "Shrek! Hjælp os! råbte de i munden på hinanden"
            mc "Jeg er ikke en helt, og jeg er bestemt ikke jeres babysitter,"
            mc "mumlede Shrek, men Fiona og Æsel stod allerede nysgerrigt bag ham."
            mc "vil du ikke nok hjælpe os sagde dvagene"
            mc "shrek sagde så,hvad er det i overhovedt skal have hjælp til?"
            mc "der er en ond trold mand ved navn grimsfjæs,han minder om gagamel og tror at vi er smølfer"
            mc "og derfor jagter han os sagde dvagene"
            mc "okay fint hvor finder jeg ham i kalder grimfjæs,sagde shrek"
            mc "du finder ham ude i skoven sagde de"
            mc "okay jeg reder jer,men kun den ene gang okay!,sagde shrek meget bestemt"
            mc "yep vi lover det sagde de"
            mc "godt og hold jer væk fra min sump,ellers vil jeg spise jer til morgen mad sagde han truene"
            mc "de niggede og gemte sig et sted hvor grimfjæs ikke kan finde dem"
            mc "shrek fandt den onde grimfjæs og gjor så klar til kamp"
            mc "grimfjæs sagde ha,en simpel trold kan ikke besejere mig den mægtige grimfjæs"
            mc "det skal du ikke være så sikker på sagde shrek"
            mc "grimfjæs sagde så,oh jeg skal give dig sagde jeg alaka"
            mc "han skulle til at skyde shrek med sin magiske stav"
            mc "shrek kom løbene og slog hans grimme fjæs"
            mc "åh nej,min eneste svaghed at blive slået i mit grimme fjæs,sagde den onde trold mand og endte med at dø"
            mc "lol han var weak sagde shrek og tog hjem igen for at slappe af igen og dvagene var redet slut"
            bd "altså den gav ingen menning,men det var nu ret underholdene,godt gået mc du består"
            mc "åh tusiden tak blækward"
            "blækward gik hen til helpy for at høre hans historie"
        "historien om darthjacobs barndom":
            mc "okay her kommer historien om darthjacobs barndom"
            "du rejste dig op og læste det højt"
            mc "I en fjern, fjern galakse, på en planet ingen længere husker navnet på"
            mc "blev lille Jacos født under en himmel fyldt med storme"
            mc "Allerede som barn kunne man mærke, at noget særligt boede i ham"
            mc "Han elskede mørke huler og stille aftener"
            mc "hvor vinden susede mellem træerne, og han kunne høre planetens dybe, dunkle ekko."
            mc "Jacos voksede op i en lille landsby, hvor han altid skilte sig ud"
            mc "Mens de andre børn legede og grinede, sad Jacos alene og studerede skyggerne"
            mc "der dansede på væggene"
            mc "Han er bare lidt sær, sagde de voksne, men ingen forstod, at Jacos kunne føle noget dybere. Noget kraftfuldt."
            mc "n dag, da han var blot 10 år gammel, fandt Jacos en gammel rusten hjelm i en forladt hule"
            mc "Da han tog den op, strømmede en mærkelig kulde gennem hans krop"
            mc "Han mærkede, hvordan en stemme, langt væk, hviskede Du er skabt til noget større, Jacos. Du er mørkets arving."
            mc "Fra den dag begyndte alt at forandre sig"
            mc "Hans hænder kunne flytte små sten uden at røre dem"
            mc " Folk i landsbyen blev nervøse, når han gik forbi"
            mc "Selv træerne syntes at bøje sig let, når Jacos nærmede sig. Han følte sig ikke længere hjemme."
            mc "En nat forlod Jacos landsbyen, iført den gamle hjelm"
            mc "der nu passede perfekt"
            mc "Han vidste ikke, hvor han var på vej hen"
            mc "men han fulgte stemmen, der kaldte fra stjernerne"
            mc "Snart ville han blive DarthJacos, den skikkelse, galaksen aldrig ville glemme"
            mc "slut"
            bd "den var lidt mærkelig,faktisk for mærkelig,du dumpet"
            "blækward gik hen til helpy for at høre hans historie"
    h "den her historie handler om en helpy som lider af en trash skole"
    "helpy rejste sig op for at fortælle hans historie"
    h "der var engang en helpy som var lykkelig"
    h "men så en dag følte han sig ensom,så han besluttet sig for at prøve at gå i en skole"
    h "ligså snart han har gået i skolen i noget tid fortryd han at han valgte den trash skole"
    h "alle lærene var onde mod ham,men edtemindste havet han en ven ved navn mc"
    h "mc har altid været så god ved stakkels helpy,så han kunne edtemindste tænke lidt mere positivt"
    h "han endte med at invetere helpy med til ham med sayori så han fik inu flere venner"
    h "plus han fik en club at gå i,for han tænkte at det kunne han ligeså godt joine"
    h "fordi toyfreddy ikke vil lade ham gå ud af den trash skole selv når han har fri"
    h "bare fordi han har givet ham uretfærdige bøder som han ikke kan betale,slut"
    bd "den vil være god hvis det ikke skulle forstille os!"
    h "what,hvad mener du mand!,hvorfor kan du ikke lide at det hanlder om jer!"
    bd "for det første,det handler alt for meget om dig"
    h "what!"
    bd "og for det andet,du skrev i din historie at vi er nogen forfærdelige lærer!"
    h "jeg skrev bare hvad der passet"
    bd "så ja du dumpet,taber snegl!"
    h "jeg hader den her skole"
    bd "din tur funtime foxy"
    fx "luuu min historie er rigtig god,er i klar"
    h "åh nej,ikke hindes historie,ved bare hvad det kommer til at handle om"
    fx "der var en dag hvor jeg mødtes med ron hvor jeg sagde,skal vi ikke følges ron"
    fx "så sagde han jo lad os gøre det,det vil blive sjovt"
    fx "hans bukser var så pæne,så jeg sagde,wow du har pæne bukser på"
    fx "så sagde ron,tak,jeg går altid med dem"
    fx "bagefter da vi gik en tur tabte han bukserne og sagde nedtur"
    fx "også grinte vi alle,hahaha luuuuu"
    h "jeg kender den historie"
    fx "hvordan det?"
    h "fordi du fortæller altid den samme historie!"
    fx "den er jo så god"
    h "nah,elnlig ikke"
    bd "du dumper funtime foxy,den var godt nok kedelig og uvigtig at høre,jeg er så irriteret på dig!"
    "blækward kølet ned igen og gik over til hmmmm?"
    bd "hvor er vanny,den pjækker!"
    mc "nu hvor du siger det,jeg har ikke set hinde siden igår,glitchtrap tog hinde med et sted,også så vi hinde ikke igen"
    bd "mystisk,når lige meget med hinde,lad os forsætte timen"
    "han gik mod bonnie for at høre hans historie"
    fb "okay den her skal nok blive god"
    "bonnie begyndte at fortælle hans historie"
    fb "der var engang en bonnie som elsket flæskestejs burger,men noget forfærdeligt skete"
    fb "der var slet ikke mere flæskestej,bonnie gik i panik og sagde,åh nej det er verdens undergang"
    fb "freddy kom hen til bonnie og sagde,jeg ved hvordan vi får flæskestej igen"
    fb "hvordan sahde han håbefuldt,det nemt nok,du skal bare købe det sagde freddy"
    fb "what,man kan ikke bare købe flæskestej sagde bonnie,det giver ingeng menning sagde freddy forvirret"
    fb "jeg har tjekket alle butikkerne,de sælger det ikke mere,men jeg ved nu hvordan vi får det tilbage igen"
    fb "hvordan sagde freddy,bonnie svaret tilbage,vi må tage over til flæske kongen"
    fb "bonnie og freddy tog straks afsted og kom til flæske kongen,bonnie og freddy bliv helt overasket over at han findes"
    fb "waow du findes virkelig sagde bonnie med store øjne"
    fb "jeg nægter at tro det,bonnie du må undskylde at jeg ikke troet på dig i alt den tid"
    fb "bonnie sagde til freddy,det okay freddy,det giver jo trosalt menning at du ikke troet på det før hen"
    fb "flæske kongen svaret,valg vil i her dødelige"
    fb "årh mægtige flæske konge,vi er kommet for at bede om din hjælp,vi har ingen flæskestej tilbage"
    fb "det er jo alvorligt udbryd flæskekongen,godt i kom her til,jeg vil søger for at der kommer flæskestej igen"
    fb "tusind tak for din hjælp o mægtige flæskekonge"
    fb "det dig vi burde at takke bonnie,sagde flæskekongen,og du vilnu blive kendt som helten i flæskestej"
    fb "what det jo vildt mange tak flæske konge sagde de og tog hjem til dem selv igen"
    fb "det endte lykkeligt,og der er nu flæske stej til dem alle,slut"
    bd "waow,den historie var for mærkelig!"
    fb "var den ikke god?"
    bd "god nej,sjov ja,men du dumper"
    fb "what hvorfor?"
    bd "havet jeg ikke sagt det klart!,historen skal give menning og være sjov og din gav overhovedt ingen menning,så derfor dumper du!"
    fb "what jeg burde at få en ok karakter,jeg gjor den jo sjov"
    bd "såden er det,surt sjov"
    fb "flabed"
    "blækward bliv så sur på bonnie at han slog ham"
    fb "av du sindsyg mand!"
    bd "så kan du lære det,ingeng skal sige at jeg er flabed eller irriterende,eller hvad enden ond ting det er!"
    h "ja det bliver lidt svært at ungå,mumulet han"
    bd "hvad sagde du der lille snegl?"
    h "um ikke noget"
    "han gik mod svampebob for at høre om hans historie"
    sb "bhahahaha,jeg vil ikke sige det"
    bd "hold nu op svampebob!"
    sb "bahahahah nej"
    bd "jeg smadre dig hvis du ikke snart siger din historie!"
    sb "okay her er min"
    "svampebob rejste sig op og fortalte hans historie"
    sb "der var engang en svampe bob,han mødtes med patrik,de bliv venner lige med det samme"
    sb "de prøvet at blive blækwards ven,men han spillet så kosbar,men så senere hen i en dag skete et mirakel"
    sb "blækward indså hvor godt han kunne lide os,så han bliv vores gode ven og havet det sjovt sammen"
    sb "svampebob spurgte skal vi ike være venner forevigt blækward,blækward sagde,nej,bedste venner"
    sb "de sluttet af med et kram,bahahahaha god historue var,jeg fandt selv på den"
    s "wow det var så sødt,det venskab lyd så smukt"
    bd "det kan godt være,men han dumper stadig"
    s "hvorfor var den ikke god?"
    bd "den var ikke sjov og den gav ingeng menning,så han dumper dobelt så meget som helpy gjor,fordi jeg hader svampebob plus hans histoire var kedelig og gav ingeng menning"
    sb "bahahaha du noget du bare siger fordi du i virkeligheden ikke vil indrømme at vi er gode venner"
    bd "jeg nakker dig svambebob!"
    "da blækward slog svampebob og kølet ned igen,gik han hen til sayori for at høre hindes historie"
    s "jeg ved ikke lige hvad der skete før der men er sikker på at du vil elsker min historie"
    "hun rejste sig op og begyndte at læse sit højt"
    s "Det var en perfekt morgen i den lille by"
    s " Solen skinnede gennem Sayoris vindue"
    s "og fuglene sang deres glade melodier"
    s "Sayori sprang ud af sengen med et stort smil og strakte armene ud mod loftet"
    s "I dag bliver en fantastisk dag!” erklærede hun for sig selv"
    s " som om verden havde brug for at høre det."
    s "Hun besluttede sig for at sprede glæde, hvor end hun gik"
    s "Først løb hun over til naboens hus og hjalp med at samle blomster til deres have"
    s "Hun dansede rundt med kurven, som om hun selv var en blomst."
    s "Derefter tog hun en pose småkager med i tasken og løb hen til parken"
    s "Her satte hun sig på en bænk og begyndte at dele dem ud til forbipasserende"
    s "både børn, voksne og endda en hund, som fik et “Værsgo, lille ven!."
    s "Sayori stoppede ikke der. Da hun så en ældre mand sidde alene på en bænk, gik hun hen og satte sig ved siden af ham"
    s "Hej! Er det ikke bare en smuk dag i dag?” sagde hun med sit største smil."
    s "Manden så overrasket ud, men efter et øjeblik begyndte hans mundvige at trække opad"
    s "det har du ret i, unge dame. Jeg havde næsten glemt at nyde solen"
    s "Da aftenen nærmede sig, gik Sayori hjem, træt men glad"
    s "Hendes hjerte føltes let, for hun vidste, at hun havde gjort dagen lidt lysere"
    s "både for andre og for sig selv. Hun lagde sig i sengen med et smil på læben og tænkte"
    s "Lykken er som solskin. Den skinner mest, når man deler den med andre"
    s "slut"
    bd "den var ret rørene,og den giver faktisk god menning,så noget kan ske plus historien var god,du består"
    s "virkelig,tak,jeg er så glad for at i kunne lide den"
    bd "nu ved jeg at sayori er min ynglings elev"
    h "du sagde jo lige at det var mc før der var din ynglings!"
    bd "nej,der sagde at han vil måske blive det,men det bliv han ikke,men han er okay,i modsætining til dig snegl"
    h "jeg skulle aldirg havet valgt den her skole"
    "blækward gik hen til natsuki for at høre hindes historie"
    "natsuki rejste sig op og talte om hindes historie"
    n "okay gør jeg klar til noget virkelig cool"
    "hun begyndte at læse"
    n "Der var engang en pige ved navn Natsuki, som elskede at bage"
    n "et ville hun dog aldrig indrømme sådan uden videre"
    n "Det er bare en hobby, okay? Det er ikke noget særligt! plejede hun at sige med røde kinder, når nogen spurgte."
    n "En dag besluttede Natsuki at deltage i den store kagekonkurrence i byen"
    n "ikke fordi jeg vil vinde eller noget! mumlede hun, mens hun æltede dejen. “Jeg gør det bare… fordi jeg kan"
    n "Men lige før konkurrencen begyndte"
    n "opdagede hun noget forfærdeligt"
    n "En anden deltager havde kopieret hendes opskrift på de sødeste"
    n " lyserøde cupcakes med jordbærglasur."
    n "“H-Hva?! Det er min idé!” udbrød hun og knyttede næverne"
    n "Med et fnys gik hun i gang med at bage noget helt andet"
    n "noget, som var typisk Natsuki"
    n "små cupcakes med chokolade, et strejf af krydderi og små, vrede katte ansigter tegnet med glasur"
    n "Se bare, sagde hun bestemt, mine er tusind gange bedre end de dér kedelige kopier!"
    n "Da dommerne smagte på hendes kager, blev deres øjne store"
    n "Disse… er fantastiske! sagde en af dem. De er søde, men med en overraskende bid! Ligesom… dig"
    n "Natsuki så hurtigt væk og foldede armene. “Hmpf, det er ikke noget særligt… Men… tak eller hvad."
    n "Og selvom hun fik førstepladsen, nægtede hun at smile for meget"
    n "Hun gik derfra med pokalen i hånden, men hendes røde kinder afslørede alt"
    n "Helt ærligt, det er ikke som om jeg prøvede SÅ hårdt!” mumlede hun"
    n "mens hun allerede tænkte på sin næste bagning.slut"
    bd "den historie var ret god,plus den gav menning,du består"
    n "tsk det ikke noget særligt,bare en fjollet ide jeg havet"
    s "den var så god og så cute som dig natsuki"
    n "jeg er ikke....CUTE!"
    "selv om natsuki virket irriteret og kold,kunne hun ikke skjule lidt rødmen på hindes kinder"
    n "hold din mund lasse!"
    "når når okay,jeg har altså også følelser"
    "blækward gik vidre til yuri,hinde som de fleste ser som kedelig,fordi hun er kedelig"
    y "huh?"
    bd "når fortæl os din historie yuri"
    y "okay jeg skal gøre mit bedste"
    "yuri rejste sig op og begyndte at fortælle hindes historie"
    y "den her handler om skyggernes rige"
    y "Langt borte, mellem verdener, lå Skyggernes Rige"
    y "et sted, hvor lyset sjældent nåede, og mørket hviskede historier til dem, der turde lytte"








                

















    return