label ch3_main:
    $ currentDay = "Onsdag"
    scene bg bedroom
    play music t8
    
    "ONSDAG"
    "du stod op og tog dit tøj på,og du husket hvad der skete i din drøm,så du valgte at holde den for dig selv og nyde dagen"
    mc "det er idag hvor jeg skal rede sayori og være sammen med monika i clubben idag"
    "glæder du dig?"
    mc "ja,jeg er både nervøs og glad på sammen tid,så længe jeg ikke får baldi som lærer"
    "det godt at høre,du tog ned i køkkenet hvor natsuki også var kommet til"
    scene bg kitchen
    n "okay lad os lave noget mad mc"
    mc "yep,og jeg kan sige at idag skal nok blive din bedste dag nogensinde"
    n "hvorfor det?"
    mc "det finder du ud af senere"
    n "når men jeg tænker at vi kunne lave æg og bacon idag"
    mc "mmmm det lyder lækkert,lad os lave det"
    "i begyndte at lave maden"
    mc "det sjovt at være sammen med dig natsuki"
    n "tak,du er heler ikke værest,du en god ven,men sig ikke til nogen at jeg har været blød okay,jeg har et ry at opretholde!"
    mc "hehe barolig natsuki,jeg lover at jeg holder det mellem os 2"
    n "hey jeg er rolig,og um tak"
    "i lavet maden færdigt og tog tilærkner og bestik frem i stuen hvor i vil spise sammen"
    scene bg livingroom
    "inu engang ser i den samme kedelige film mens i spiser"
    n "du må nok se at få en bedre film"
    "sagde hun med et grin"
    mc "haha ja du har ret,den var god i starten,men en eller anden grund er jeg blivet træt af den"
    n "ja hvorfor mon da"
    "i spiste maden færdigt sammen og i gik tideligt ud da du havet travlt med at skulle se til sayori"
    scene bg street
    n "skal du ikke med til skolen?"
    mc "jo jo jeg vil bare se til sayori,er bekymret for hinde"
    n "hvorfor det?,hun er jo evig glæde skal du tænke på"
    mc "det var menningen at hun skulle komme hos os igår,men hun aflyste det af en grund hun ikke vil fortælle mig"
    n "okay vi ses i skolen så"
    mc "det gør vi ja,ses"
    n "bare i 2 fjollehoveder kommer til tiden"
    "natsuki gik mod skolen,mens du skyndte dig mod sayoris hus"
    scene bg house
    "du banket på døren da du ankom,ingeng reaksion,men du kunne se at døren ikke var låst,så du gik ind"
    scene bg kitchen
    "du kom ind i huset i i hindes køkken,du prøvet at råbe efter hinde"
    mc "sayori!"
    "ingeng reaksion,det fik dig til at ryste i bukserne"
    mc "det ret dulled"
    "det ved jeg,man skulle tro at du spillet en doki doki dulle mod"
    mc "hmmm hvad er det hun laver,hun kommer jo forsent hvis hun bliver ved med at blive væk"
    "du besluttet dig for at gå op til hindes værelse"
    scene bg door
    "du kom til hindes dør der var lukket,men den var heler ikke låst"
    mc "det har er underligt"
    mc "saoyri!"
    "ingeng reaksion"
    mc "er det okay at jeg kommer ind?"
    "der kom stadig ingen reaksion,men hun gav dig ingen valg,så du kom ind"
    mc "nu kommer jeg ind sayori"
    "du åbnet døren"
    scene bg sayori_bedroom
    s "oh hej mc,undskyld at jeg ikke reageret da du kaldte"
    "du så hinde have et reb i hånden"
    mc "sayori hvad skal du med det reb?"
    s "um det er um,ikke noget slemt i hvertfald hehe"
    "hun smilte men du kunne se på hinde at hun skjuler noget for dig,og nej det er ikke noget med at tabe bukserne at gøre"
    mc "vil du ikke nok fortælle mig sandheden"
    s "det her er sanheden,jeg har det fint"
    mc "virkelig?,hvordan kan det så være at du skrev i går aftes at du havet brug for min hjælp?"
    s "um det var bare for sjov,bø skramte jeg dig hehe"
    mc "sayori,pls fortæl mig hvad der rigtigt forgår"
    s "lov at du ikke siger det til nogen okay"
    mc "det lover jeg"
    s "okay du kan sikkert huske at jeg fortalte dig om min depression i mandags ik?"
    mc "ja selvføgelig"
    s "okay,det fordi nu det blivet værre,jeg har selvmords tanker"
    mc "what,hvorfor?"
    s "jeg føler at jeg er svag og ubruglig,og bliv lidt jealou over at du var sammen med de andre,så følte at jeg ikke behøvet at være der"
    mc "sayori,jeg vil ikke kunne klare det uden dig"
    s "mener du virkelig det?,jeg er en byrde mc,jeg kan resikere at bekymre de andre om min depression,og vil helst have at alle er glade"
    mc "sayori du er den bedste ven man kunne ønske sig,hvorfor tror du at jeg altid valgte at være sammen med dig da jeg havet et valg"
    s "undskyld mc,jeg er så ked af at jeg fik dig til at blive bange"
    "hun begyndte at græde,tudefjæs"
    mc "det okay sayori,det helt normalt at kunne få depression af og til,men du burde at tage din depression alvorligt"
    s "du har nok ret,hvad skal jeg gøre mc,det gør så ondt"
    mc "vi har brug for at få dig til en pygolog om det her,de kan hjælpe dig"
    s "tror du virkelig det?"
    mc "jeg tror det ikke for jeg ved det"
    "hun var stadig trist,men fik det lidt bedre"
    s "tak mc,jeg elsker dig"
    mc "jeg elsker også"
    s "må jeg spøger dig om noget mc?"
    mc "ja selvføgelig"
    s "er du også forælsket i mig ligesom jeg er med dig?"
    mc "huh?,hvor langtid har du været det?"
    s "det har jeg været længe nu"
    mc "okay jeg vil give dig svaret nu"
    "nu skal du vælge det du vil sige,husk at de valg du træffer ændre din historie til endten lykkeligt eller trist,afhænget af dine valg"
    "men det viser det dig først i det næste spil jacob vil lave fordi han vil forsætte det i denn her histoire i det du har valgt"
    mc "hvordan ved du alt det lasse?"
    "jeg ved alt om jer,om hvor i bor og hvad i føler og tænker og hvad jeres svaghed er"
    mc "det lidt skræmmene"
    "det ved jeg,når men vælg nu hvad du vil sige til sayori"
    menu:
        "jeg er også forælsket i dig":
            s "mener du virkelig det"
            mc "ja selvføgelig mener jeg det,du er smuk og cute,og du har de pæneste bukser på,selv når de falder ned"
            "hvem er det nu der er dulled var"
            s "yay det var det jeg håbet på at du vil sige,tak mc"
            "i kramte hindaen og fik jeres første kys"
        "lad os bare være bedste venner":
            s "oh,jamen okay,lad os bare det hehe"
            "hun virket trist,det som om hun håbede på noget mere romantisk"
            mc "er du okay sayori?"
            s "jaja,jeg har det helt okay"
            "du viste at noget ikke stemte"
            mc "du skal bare vide at jeg vil altid være der for dig uanset hvad"
            mc "bare fordi at vi ikke bliver kærster betyder det ikke at vi ikke kan være sammen"
            s "du har ret mc,du betyder også meget for mig"
            "i kramte hindaen"
    mc "vi må nok heler skynde os til skolen"
    s "ja du har ret lad os skynde os så vi ikke får ballade"
    "i skyndte jer alt hvad i kunne"
    scene bg street
    s "åh nej jeg glemte at tage bælte på"
    "du så hun rødmet og holdte bukserne oppe"
    s "jeg havet vist ikke tid til at finde bæltet hehe,vi havet så travlt,men det min egen skyld"
    mc "det okay,måske skulle vi tilbage og hente det"
    s "nej det har vi nok ikke tid til,ellers kommer i ikke til tiden,men bareolig,jeg kan bare trække bukserne op"
    mc "okay,og hvis nogen mobber dig om dine buksefald,skal jeg nok sige noget til dem"
    s "du altid så sød mc"
    mc "ja jeg er ret fantastisk ik ehehe"
    "i gik hen mod skolen"
    scene bg school
    "desværre for jer så toy freddy jer der ude som ikke var kommet ind i classen inu"
    tf "når når når,i kommer forsendt til jeres classe,og det er imod reglerne"
    s "undskyld toy freddy,det min fejl,mc kom med mig bare for at hjælpe mig med at komme afsted"
    tf "det var pænt af ham,men du skal stadig betale en bøde for at komme for sendt sayori"
    s "oh okay jeg forstår"
    "sayori betalte toyfreddy hindes bøde,den kostet kun 50kr heldigvis"
    tf "når men i må heler skynde jer til klassen,freddy har ventet på jer i 2 minutter nu"
    mc "forstået toy freddy,vi skynder os"
    tf "godt,og næste gang så kom til tiden"
    s "det skal vi nok"
    "i tog til klassen hvor freddy desvære virket lidt skuffet over at i ikke kom til tiden"
    scene bg class_day
    f "hey hvor har i været?,jeg har ventet enda i 4 minutter"
    h "hvordan kan du overhovedt tage det slemt,det jo kun 4 minutter de er forsinket i!"
    f "bland dig udenom snegl!"
    s "undskyld freddy,det min skyld,jeg er grunden til at vi kom forsendt"
    f "hvorfor dog det,du plejer altid at komme til tiden"
    s "det for pingligt at sige"
    fx "luuuu jeg ved hvad det er"
    f "stille dul!,jeg snakker med sayori ikke dig!"
    fx "hun taber"
    f "jeg sagde STILLE!"
    s "tak for at holde min hemmelighed hemmeligt"
    f "hvad mener du,oh når ja,det sandt,jeg er god til at holde på hemmeligheder,jeg er jo den bedste lære jo,så tak for det sayori"
    h "det var ingeng gang det hun sagde"
    f "stille snegl!,lad mig nyde øjeblikket!"
    f "når men idag skal vi nok mega sjovt"
    h "oh nej,er det matematik"
    f "nej noget meget bedre"
    h "what virkelig?"
    f "ja selvføgelig lille snegl,vi skal nemlig have teater"
    h "det lyder faktisk....sjovt"
    f "ja selvføgelig det var jo trosalt min ide"
    h "det var ikke lige helt det jeg"
    f "når men i efter jeres undervisning med glitchtrap og spise pausen,skal jeg være jeres lærer til teateret,i får mere at vide når vi når der til"
    h "åh nej ikke glitch trap igen"
    f "hov sagde jeg glitchtrap,nej nej en meget bedre lærer skal undervise jer"
    h "nice"
    f "ja og ham der skal undervise jer nu er"
    "toy freddy kom ind"
    tf "mig"
    h "må jeg græde nu"
    f "nej lille tudefjæs,ingeng gider at høre på en tudeprins"
    f "når jeg går igang hav det sjovt ahhaha"
    h "det får vi så ikke"
    "freddy gik ud af klassen og toy freddy stod klar til at undervise jer"
    tf "idag skal vi have en sjov undervisning"
    h "lad mig gætte,kunst?"
    tf "nej noget meget bedre,i får quiz time"
    h "seriøst!,nu kan det da heler ikke blive værre!"
    tf "når ja,og du skylder mig 400kr mere for at være irriteret helpy"
    h "jeg hader den her skole"
    mc "what,hvor er vanny,hun var der kun mandags"
    tf "oh vanny?,når ja jeg glemte at hun fandtes"
    mc "...?????"
    tf "når men nu til noget der er vitgiere in hinde banny hvad hun nu hed"
    tf "vi starter med dig der"
    h "jeg har faktisk et navn"
    tf "når ja lille snegl hed du,så lille snegl,hvem i fantasi historen har sovet i 1000år"
    h "hvorfor er det altid mig der får de videnskabs spørgsmål!"
    tf "fordi du skal blive kloger jo,og også fordi at jeg hader dig"
    h "er det titansne?"
    tf "ej hvor du trash helpy,forkert svaret,det er illidan som sov i 1000år,og det bliver 50kr for at dumpe"
    h "what,siden hvornår har illidan været i fantasi!"
    tf "ja det viste du ikke fordi du er en lille dum baby snegl"
    h "jeg forstår heler ikke det der med at vi skal betale for at fejle!"
    tf "arh,det gør de heler ikke,det kun dig reglen gælder for"
    h "what!"
    tf "så det dig funtimebuks"
    fx "luuuu du kaldte mig buks,mit ynglings kæle navn"
    tf "du afbryder!,når men nu skal du gætte på det her,hvem er den mægtiste her?"
    fx "luuuu,det er buksernes bukser"
    tf "forkert,hvad der galt med dig,du svare heletiden bukser"
    fx "fordi bukser er en buks som er bukser"
    tf "det giver jo slet ingeng menning,det en bøde på 70kr for at være så dulled"
    fx "luuuuuu"
    tf "så det dig bonnie ponny hahaha hvor er jeg sjov"
    fb "nah"
    tf "når når når,prøver du svare mig imod,det bliver 120kr for at være uenig med læren"
    fb "what,den regel er der slet ikke"
    "i kunne høre at han gik i gang med at taste på noget"
    tf "kig bedre efter"
    fb "what du har lige tilføjet den"
    tf "nej,du skulle bare havet kigget bedre efter"
    fb "men der står at du har tilføjet den for 4 seckundter siden!"
    tf "stille ponny,200kr i bøde nu for at være sur"
    h "og nu ved du hvorfor jeg hader den her skole bonnie"
    tf "når bonny ponny,hvor mange burger har jeg spist i alt"
    fb "what den er jo umulig!,er det 100"
    tf "what,hvor du trash,forkert,jeg spiste 1000 burger,det burde du at kunne vide"
    h "what du tyk"
    tf "skal man nu fornæme mig,det bliver 500kr for at være flabed snegl"
    h "hmm hvad mon værst,selvmord eller at blive i den her skole for altid,det undre jeg mig faktisk over"
    tf "ingeng gider at høre på din menning snegl,når sayori,hvordan forhendre man bukser i at falde ned"
    h "helt ærligt!,børnehave spørgsmålllll!"
    s "det gøre man med et bælte"
    fx "luuuu det ved du alt om fordi du taber bukserne"
    tf "what!,først afbryder du mig og nu gøre du nar af en af mine ynglings elever,det bliver en bøde på 800kr!"
    fx "luuuuu,jeg har næsten ingeng penge tilbage"
    tf "så må du bare ladevære med at bryde reglerne,når men vil sige at du bestod sayori"
    s "yay jeg gjor noget godt"
    tf "tja,det kunne man vist godt sige,du svaret hvertfald rigtigt"
    tf "din tur natsuki,hvem er batmans ærkefjende"
    h "det sjove ved det er at du altid giver natsuki børnehave spørgsmål!"
    n "det må være jokeren"
    tf "det rigtigt,flot klaret"
    tf "så det dig yuri,hvem var den udvalgte i starwars filmene"
    y "var det ikke anakin?"
    tf "det rigtigt flot klaret"
    h "seriøst,det kunne et barn svare på"
    tf "det ikke alle der kender starwars"
    h "ikke det!,det er en af de mest probolere film!"
    tf "når når når,du prøvet både at rette mig og du bliv irriteret,det en bøde på 800kr"
    h "det burde jeg at havet set komme"
    tf "så det dig svampebob,hvem laver pjatte jokes?"
    sb "bahahhah,det må være freddy"
    tf "hvor vover du at tale såden om freddys jokes.du dumper,plus du skal betale 500kr i bøde for at være flabed mod freddy"
    sb "bahahahah,nu bliver jeg mere fattig"
    tf "hvorfor griner du af det?,du bliver jo straffet"
    sb "jeg synes alt er sjovt bahahahaha"
    tf "hvad hvis nu en truet dig?"
    sb "så synes jeg at det stadig er sjovt bahahahaha"
    tf "??????"
    tf "ihvertfald er det din tur ayano,hvad er hovedstaden i danmark"
    ay "nemt,det er københavn"
    tf "det rigtigt flot klaret"
    ay "jeg viste det fordi at jeg"
    tf "jaja vi ligeglade,du har bestået"
    








                


