label ch3_main:
    $ currentDay = "Onsdag"
    scene bg bedroom
    play music t8
    
    "ONSDAG"
    "du stod op og tog dit tøj på,og du husket hvad der skete i din drøm,så du valgte at holde den for dig selv og nyde dagen"
    mc "det er idag hvor jeg skal rede sayori og være sammen med monika i clubben idag"
    "glæder du dig?"
    mc "ja,jeg er både nervøs og glad på sammen tid,så længe jeg ikke får baldi som lærer"
    "det godt at høre,du tog ned i køkkenet hvor natsuki også var kommet til"
    scene bg kitchen
    n "okay lad os lave noget mad mc"
    mc "yep,og jeg kan sige at idag skal nok blive din bedste dag nogensinde"
    n "hvorfor det?"
    mc "det finder du ud af senere"
    n "når men jeg tænker at vi kunne lave æg og bacon idag"
    mc "mmmm det lyder lækkert,lad os lave det"
    "i begyndte at lave maden"
    mc "det sjovt at være sammen med dig natsuki"
    n "tak,du er heler ikke værest,du en god ven,men sig ikke til nogen at jeg har været blød okay,jeg har et ry at opretholde!"
    mc "hehe barolig natsuki,jeg lover at jeg holder det mellem os 2"
    n "hey jeg er rolig,og um tak"
    "i lavet maden færdigt og tog tilærkner og bestik frem i stuen hvor i vil spise sammen"
    scene bg livingroom
    "inu engang ser i den samme kedelige film mens i spiser"
    n "du må nok se at få en bedre film"
    "sagde hun med et grin"
    mc "haha ja du har ret,den var god i starten,men en eller anden grund er jeg blivet træt af den"
    n "ja hvorfor mon da"
    "i spiste maden færdigt sammen og i gik tideligt ud da du havet travlt med at skulle se til sayori"
    scene bg street
    n "skal du ikke med til skolen?"
    mc "jo jo jeg vil bare se til sayori,er bekymret for hinde"
    n "hvorfor det?,hun er jo evig glæde skal du tænke på"
    mc "det var menningen at hun skulle komme hos os igår,men hun aflyste det af en grund hun ikke vil fortælle mig"
    n "okay vi ses i skolen så"
    mc "det gør vi ja,ses"
    n "bare i 2 fjollehoveder kommer til tiden"
    "natsuki gik mod skolen,mens du skyndte dig mod sayoris hus"
    scene bg house
    "du banket på døren da du ankom,ingeng reaksion,men du kunne se at døren ikke var låst,så du gik ind"
    scene bg kitchen
    "du kom ind i huset i i hindes køkken,du prøvet at råbe efter hinde"
    mc "sayori!"
    "ingeng reaksion,det fik dig til at ryste i bukserne"
    mc "det ret dulled"
    "det ved jeg,man skulle tro at du spillet en doki doki dulle mod"
    mc "hmmm hvad er det hun laver,hun kommer jo forsent hvis hun bliver ved med at blive væk"
    "du besluttet dig for at gå op til hindes værelse"
    scene bg door
    "du kom til hindes dør der var lukket,men den var heler ikke låst"
    mc "det har er underligt"
    mc "saoyri!"
    "ingeng reaksion"
    mc "er det okay at jeg kommer ind?"
    "der kom stadig ingen reaksion,men hun gav dig ingen valg,så du kom ind"
    mc "nu kommer jeg ind sayori"
    "du åbnet døren"
    scene bg sayori_bedroom
    s "oh hej mc,undskyld at jeg ikke reageret da du kaldte"
    "du så hinde have et reb i hånden"
    mc "sayori hvad skal du med det reb?"
    s "um det er um,ikke noget slemt i hvertfald hehe"
    "hun smilte men du kunne se på hinde at hun skjuler noget for dig,og nej det er ikke noget med at tabe bukserne at gøre"
    mc "vil du ikke nok fortælle mig sandheden"
    s "det her er sanheden,jeg har det fint"
    mc "virkelig?,hvordan kan det så være at du skrev i går aftes at du havet brug for min hjælp?"
    s "um det var bare for sjov,bø skramte jeg dig hehe"
    mc "sayori,pls fortæl mig hvad der rigtigt forgår"
    s "lov at du ikke siger det til nogen okay"
    mc "det lover jeg"
    s "okay du kan sikkert huske at jeg fortalte dig om min depression i mandags ik?"
    mc "ja selvføgelig"
    s "okay,det fordi nu det blivet værre,jeg har selvmords tanker"
    mc "what,hvorfor?"
    s "jeg føler at jeg er svag og ubruglig,og bliv lidt jealou over at du var sammen med de andre,så følte at jeg ikke behøvet at være der"
    mc "sayori,jeg vil ikke kunne klare det uden dig"
    s "mener du virkelig det?,jeg er en byrde mc,jeg kan resikere at bekymre de andre om min depression,og vil helst have at alle er glade"
    mc "sayori du er den bedste ven man kunne ønske sig,hvorfor tror du at jeg altid valgte at være sammen med dig da jeg havet et valg"
    s "undskyld mc,jeg er så ked af at jeg fik dig til at blive bange"
    "hun begyndte at græde,tudefjæs"
    mc "det okay sayori,det helt normalt at kunne få depression af og til,men du burde at tage din depression alvorligt"
    s "du har nok ret,hvad skal jeg gøre mc,det gør så ondt"
    mc "vi har brug for at få dig til en pygolog om det her,de kan hjælpe dig"
    s "tror du virkelig det?"
    mc "jeg tror det ikke for jeg ved det"
    "hun var stadig trist,men fik det lidt bedre"
    s "tak mc,jeg elsker dig"
    mc "jeg elsker også"
    s "må jeg spøger dig om noget mc?"
    mc "ja selvføgelig"
    s "er du også forælsket i mig ligesom jeg er med dig?"
    mc "huh?,hvor langtid har du været det?"
    s "det har jeg været længe nu"
    mc "okay jeg vil give dig svaret nu"
    "nu skal du vælge det du vil sige,husk at de valg du træffer ændre din historie til endten lykkeligt eller trist,afhænget af dine valg"
    "men det viser det dig først i det næste spil jacob vil lave fordi han vil forsætte det i denn her histoire i det du har valgt"
    mc "hvordan ved du alt det lasse?"
    "jeg ved alt om jer,om hvor i bor og hvad i føler og tænker og hvad jeres svaghed er"
    mc "det lidt skræmmene"
    "det ved jeg,når men vælg nu hvad du vil sige til sayori"
    menu:
        "jeg er også forælsket i dig":
            s "mener du virkelig det"
            mc "ja selvføgelig mener jeg det,du er smuk og cute,og du har de pæneste bukser på,selv når de falder ned"
            "hvem er det nu der er dulled var"
            s "yay det var det jeg håbet på at du vil sige,tak mc"
            "i kramte hindaen og fik jeres første kys"
        "lad os bare være bedste venner":
            s "oh,jamen okay,lad os bare det hehe"
            "hun virket trist,det som om hun håbede på noget mere romantisk"
            mc "er du okay sayori?"
            s "jaja,jeg har det helt okay"
            "du viste at noget ikke stemte"
            mc "du skal bare vide at jeg vil altid være der for dig uanset hvad"
            mc "bare fordi at vi ikke bliver kærster betyder det ikke at vi ikke kan være sammen"
            s "du har ret mc,du betyder også meget for mig"
            "i kramte hindaen"
    mc "vi må nok heler skynde os til skolen"
    s "ja du har ret lad os skynde os så vi ikke får ballade"
    "i skyndte jer alt hvad i kunne"
    scene bg street
    s "åh nej jeg glemte at tage bælte på"
    "du så hun rødmet og holdte bukserne oppe"
    s "jeg havet vist ikke tid til at finde bæltet hehe,vi havet så travlt,men det min egen skyld"
    mc "det okay,måske skulle vi tilbage og hente det"
    s "nej det har vi nok ikke tid til,ellers kommer i ikke til tiden,men bareolig,jeg kan bare trække bukserne op"
    mc "okay,og hvis nogen mobber dig om dine buksefald,skal jeg nok sige noget til dem"
    s "du altid så sød mc"
    mc "ja jeg er ret fantastisk ik ehehe"
    "i gik hen mod skolen"
    scene bg school
    "desværre for jer så toy freddy jer der ude som ikke var kommet ind i classen inu"
    tf "når når når,i kommer forsendt til jeres classe,og det er imod reglerne"
    s "undskyld toy freddy,det min fejl,mc kom med mig bare for at hjælpe mig med at komme afsted"
    tf "det var pænt af ham,men du skal stadig betale en bøde for at komme for sendt sayori"
    s "oh okay jeg forstår"
    "sayori betalte toyfreddy hindes bøde,den kostet kun 50kr heldigvis"
    tf "når men i må heler skynde jer til klassen,freddy har ventet på jer i 2 minutter nu"
    mc "forstået toy freddy,vi skynder os"
    tf "godt,og næste gang så kom til tiden"
    s "det skal vi nok"
    "i tog til klassen hvor freddy desvære virket lidt skuffet over at i ikke kom til tiden"
    scene bg class_day
    f "hey hvor har i været?,jeg har ventet enda i 4 minutter"
    h "hvordan kan du overhovedt tage det slemt,det jo kun 4 minutter de er forsinket i!"
    f "bland dig udenom snegl!"
    s "undskyld freddy,det min skyld,jeg er grunden til at vi kom forsendt"
    f "hvorfor dog det,du plejer altid at komme til tiden"
    s "det for pingligt at sige"
    fx "luuuu jeg ved hvad det er"
    f "stille dul!,jeg snakker med sayori ikke dig!"
    fx "hun taber"
    f "jeg sagde STILLE!"
    s "tak for at holde min hemmelighed hemmeligt"
    f "hvad mener du,oh når ja,det sandt,jeg er god til at holde på hemmeligheder,jeg er jo den bedste lære jo,så tak for det sayori"
    h "det var ingeng gang det hun sagde"
    f "stille snegl!,lad mig nyde øjeblikket!"
    f "når men idag skal vi nok mega sjovt"
    h "oh nej,er det matematik"
    f "nej noget meget bedre"
    h "what virkelig?"
    f "ja selvføgelig lille snegl,vi skal nemlig have teater"
    h "det lyder faktisk....sjovt"
    f "ja selvføgelig det var jo trosalt min ide"
    h "det var ikke lige helt det jeg"
    f "når men i efter jeres undervisning med glitchtrap og spise pausen,skal jeg være jeres lærer til teateret,i får mere at vide når vi når der til"
    h "åh nej ikke glitch trap igen"
    f "hov sagde jeg glitchtrap,nej nej en meget bedre lærer skal undervise jer"
    h "nice"
    f "ja og ham der skal undervise jer nu er"
    "toy freddy kom ind"
    tf "mig"
    h "må jeg græde nu"
    f "nej lille tudefjæs,ingeng gider at høre på en tudeprins"
    f "når jeg går igang hav det sjovt ahhaha"
    h "det får vi så ikke"
    "freddy gik ud af klassen og toy freddy stod klar til at undervise jer"
    tf "idag skal vi have en sjov undervisning"
    h "lad mig gætte,kunst?"
    tf "nej noget meget bedre,i får quiz time"
    h "seriøst!,nu kan det da heler ikke blive værre!"
    tf "når ja,og du skylder mig 400kr mere for at være irriteret helpy"
    h "jeg hader den her skole"
    mc "what,hvor er vanny,hun var der kun mandags"
    tf "oh vanny?,når ja jeg glemte at hun fandtes"
    mc "...?????"
    tf "når men nu til noget der er vitgiere in hinde banny hvad hun nu hed"
    tf "vi starter med dig der"
    h "jeg har faktisk et navn"
    tf "når ja lille snegl hed du,så lille snegl,hvem i fantasi historen har sovet i 1000år"
    h "hvorfor er det altid mig der får de videnskabs spørgsmål!"
    tf "fordi du skal blive kloger jo,og også fordi at jeg hader dig"
    h "er det titansne?"
    tf "ej hvor du trash helpy,forkert svaret,det er illidan som sov i 1000år,og det bliver 50kr for at dumpe"
    h "what,siden hvornår har illidan været i fantasi!"
    tf "ja det viste du ikke fordi du er en lille dum baby snegl"
    h "jeg forstår heler ikke det der med at vi skal betale for at fejle!"
    tf "arh,det gør de heler ikke,det kun dig reglen gælder for"
    h "what!"
    tf "så det dig funtimebuks"
    fx "luuuu du kaldte mig buks,mit ynglings kæle navn"
    tf "du afbryder!,når men nu skal du gætte på det her,hvem er den mægtiste her?"
    fx "luuuu,det er buksernes bukser"
    tf "forkert,hvad der galt med dig,du svare heletiden bukser"
    fx "fordi bukser er en buks som er bukser"
    tf "det giver jo slet ingeng menning,det en bøde på 70kr for at være så dulled"
    fx "luuuuuu"
    tf "så det dig bonnie ponny hahaha hvor er jeg sjov"
    fb "nah"
    tf "når når når,prøver du svare mig imod,det bliver 120kr for at være uenig med læren"
    fb "what,den regel er der slet ikke"
    "i kunne høre at han gik i gang med at taste på noget"
    tf "kig bedre efter"
    fb "what du har lige tilføjet den"
    tf "nej,du skulle bare havet kigget bedre efter"
    fb "men der står at du har tilføjet den for 4 seckundter siden!"
    tf "stille ponny,200kr i bøde nu for at være sur"
    h "og nu ved du hvorfor jeg hader den her skole bonnie"
    tf "når bonny ponny,hvor mange burger har jeg spist i alt"
    fb "what den er jo umulig!,er det 100"
    tf "what,hvor du trash,forkert,jeg spiste 1000 burger,det burde du at kunne vide"
    h "what du tyk"
    tf "skal man nu fornæme mig,det bliver 500kr for at være flabed snegl"
    h "hmm hvad mon værst,selvmord eller at blive i den her skole for altid,det undre jeg mig faktisk over"
    tf "ingeng gider at høre på din menning snegl,når sayori,hvordan forhendre man bukser i at falde ned"
    h "helt ærligt!,børnehave spørgsmålllll!"
    s "det gøre man med et bælte"
    fx "luuuu det ved du alt om fordi du taber bukserne"
    tf "what!,først afbryder du mig og nu gøre du nar af en af mine ynglings elever,det bliver en bøde på 800kr!"
    fx "luuuuu,jeg har næsten ingeng penge tilbage"
    tf "så må du bare ladevære med at bryde reglerne,når men vil sige at du bestod sayori"
    s "yay jeg gjor noget godt"
    tf "tja,det kunne man vist godt sige,du svaret hvertfald rigtigt"
    tf "din tur natsuki,hvem er batmans ærkefjende"
    h "det sjove ved det er at du altid giver natsuki børnehave spørgsmål!"
    n "det må være jokeren"
    tf "det rigtigt,flot klaret"
    tf "så det dig yuri,hvem var den udvalgte i starwars filmene"
    y "var det ikke anakin?"
    tf "det rigtigt flot klaret"
    h "seriøst,det kunne et barn svare på"
    tf "det ikke alle der kender starwars"
    h "ikke det!,det er en af de mest probolere film!"
    tf "når når når,du prøvet både at rette mig og du bliv irriteret,det en bøde på 800kr"
    h "det burde jeg at havet set komme"
    tf "så det dig svampebob,hvem laver pjatte jokes?"
    sb "bahahhah,det må være freddy"
    tf "hvor vover du at tale såden om freddys jokes.du dumper,plus du skal betale 500kr i bøde for at være flabed mod freddy"
    sb "bahahahah,nu bliver jeg mere fattig"
    tf "hvorfor griner du af det?,du bliver jo straffet"
    sb "jeg synes alt er sjovt bahahahaha"
    tf "hvad hvis nu en truet dig?"
    sb "så synes jeg at det stadig er sjovt bahahahaha"
    tf "??????"
    tf "ihvertfald er det din tur ayano,hvad er hovedstaden i danmark"
    ay "nemt,det er københavn"
    tf "det rigtigt flot klaret"
    ay "jeg viste det fordi at jeg"
    tf "jaja vi ligeglade,du har bestået"
    tf "din tur akira,hvem er den mest grimme i verdnen"
    ak "det må være pumbaa"
    tf "det rigtigt,pumbaa er omega grim og vi elsker at hade ham"
    br "jeg synes ellers at han er smuk ahohoh"
    tf "jamen det betyder jo bare at der noget galt med dig så"
    br "ej du,har du husket at tage dem på du"
    fx "luuuu det ligesom bukser"
    tf "når men så det dig sakura,hvem siger the jokes on you"
    sa "det må være shago"
    tf "flot klaret sakura"
    tf "din tur bedste mor gris,hvem græder allemest mærkeligt"
    br "det må være rowen,han lyd som et mærkeligt dyr ahohoh"
    tf "det rigtigt flot klaret"
    br "upser"
    tf "så er vist timen overstået,i har frikvater nu små børn"
    "toy freddy pakket sine ting sammen og gik ud for at spise"
    h "endelig har vi ham ikke mere"
    mc "han glemte at give mig en quiz"
    h "seriøst!,hvor det snyd at han bare lader dig være fri for det"
    br "det fordi at når man upser så upser man ahohoh"
    "i ignoreret bedste mor gris og gik ud til chica for at bestille mad"
    scene bg cantineIdle
    chica "hej idag har vi kun pizza fordi alt andet er usolgt"
    mc "okay så tager vi bare det"
    chica "det vliver 100 kr"
    "i tog til katinen for at spise"
    scene bg cantine
    "du sadte dig sammen med sayori og helpy"
    h "edtemindste er pizza da også lækkert"
    s "jeg elsker bare pizza"
    mc "samme her"
    "i spiste jeres pizze færdigt"
    mc "chica laver bare de bedste pizzaere"
    s "ja det er vildt lukus mad det her"
    h "ja,og det vildt sødt af jer at i vil betale for mig"
    mc "det var sålidt"
    h "så mc,hvordan gik det med dig og rekteren,du ved det med mig der sidder fast her"
    mc "kunne desværre ikke gøre noget ved det,han nægtede at lade dig få ordenligt fri uanset hvad jeg sagde til ham"
    h "trash rekter,men jeg er bare glad for at du prøvet,tak"
    s "mc er bare den sødeste"
    "sayori bliv lidt mere lun på dig,det tydeligt at hun er forælsket"
    "du valgte bare at tænke på noget andet og fukusere på det i skal snart skal lave"
    "klokken ringet,og i skulle til time igen og møde freddy ude i gangen"
    mc "tja så det vel nu vi skal have freddy"
    h "altså,han er bedre in toy freddy og alle de andre,tror faktisk det foxy jeg kan bedst lide"
    mc "hvorfor?"
    h "han er den eneste der kun er lidt sindsyg,mens alle de andre er mega syge i hoved"
    mc "du har en pointe"
    "i tog til skole gangen"
    scene bg hallWay
    f "hej små børn,det er nu i skal have teater undervisning,men enden vi tager afsted skal jeg lige forklare hvad det vil handle om"
    f "så det som det vil handle om er at en prinsese skal blive rede fra den onde gagamel,en rider og smulfer vil rede prinsesen"
    h "når,ikke mere in det"
    f "når ja tildsidst skal ridderen kysse prinsesen"
    ak "det vil passe godt til mig og mc"
    f "det ikke sikkert,jeg bestemmer rollerne her"
    ak "men jeg vil gerne være den der kysser ham"
    f "ja det bare surt for dig,for jeg vil stadig være den der vælger jeres skæbne"
    ak "det er uretfærdigt"
    f "stille!,når men kom med mig elever,så viser jeg jer et sted kaldes sukker øen"
    h "åh nej så begynder det"
    "mens i gik mod teateret begyndte i at minde helpy om flap jack introen"
    mc "hvad skal vi dog med den slags,for orden har jo alt"
    br "men ikke en sø fuld af sodavand og den mindste der smager af salt"
    ay "det farligt og risikabelt"
    sa "men eventyr er flot"
    s "for eventyr det altid godt"
    sb "og fuld af penge med slot"
    f "okay så det altså nok"
    h "endelig,jeg fik hovedpine"
    f "godt så lad os forsætte sangen forfra"
    h "NEJ!"
    "de drillet helpy med at synge sangen forfra igen"
    scene bg theater
    "i ankom til theateret"
    f "okay små børn,nu vil jeg dele jeres roller op"
    f "helpy du skal spille som gagamel"
    h "seriøst!,hvorfor skal jeg have den skåd rolle!"
    f "fordi det passer til dig"
    h "what!"
    f "mc du skal være ridderen"
    mc "nice tak,jeg skal gøre mit bedste"
    f "ja det skal du,for det her skal være perfekt!"
    f "og akira er prinsesen"
    ak "waow hvor romantisk,jeg glæder mig til kysset mc"
    "det tydeligt at hun flirter med dig"
    f "og i alle andre skal spille som smølferne"
    s "yay,jeg kan være en nuttet smølf"
    f "okay?,når men i må godt gå til opklædrings rummet,og her er jeres kustymer"
    h "hvor er mit kustyme?"
    f "du behøver ikke nogen kustyme,dit grimme udsennde passer dig perfekt som gagamel haha haaaaaa "
    h "what det flabed!"
    f "stille snegl!"
    h "værste skole nogensinde"
    f "når i må godt klæde jer om nu"
    "i gik ud til opklædrings rummet"
    scene bg costume
    "i kunne se at funtime foxy kigget på bukser,og sayori kigget efter et bælte fordi hun taber bukserne"
    "akira kom hen til dig"
    ak "skal jeg hjælpe dig med at finde et ridder kustyme?"
    mc "jeg tror at jeg har styr på det,men tak"
    ak "hm okay,jeg går ud og skifter til en smuk kjole,jeg vil sikkert blive mere udmåståelig"
    "hun gav dig et kærligt blik og gik mod opklædring rummet"
    scene bg changing_room
    "du begyndte at prøve at få ridder kustymet på"
    mc "whø hvor irriterende,de her ridder bukser er for store,jeg har brug for et bælte"
    "du kunne ikke finde et bælte"
    "pludseligt kunne du høre akiras stemme der ude"
    ak "har du brug for hjælp?"
    mc "bare bukserne der er lidt for store"
    ak "hehe jeg henter et bælte til dig"
    "du ventet i lidt tid og følte at det var lidt pinligt"
    mc "hvad skal jeg så gøre når hun kommer tilbage?"
    "du kunne lade hinde komme ind så hun kan give dig bæltet?"
    mc "nej tak,det virker for akavet når mine bukser glider ned"
    mc "wow,det godt nok dulled faktisk"
    "det er ret dulled faktisk ja"
    "du kunne høre at akira kom tætter på"
    ak "jeg har fundet et bælte til dig mc,må jeg komme ind?"
    menu:
        "ja":
            ak "okay nu kommer jeg"
            "akira gik ind og hjalp dig med at få bæltet på"
            ak "sådan nu skulle dine bukser meget gerne blive oppe"
            mc "det føles ret pingligt på en måde,men tak"
            ak "det var sålidt,jeg vil gøre alt for en smuk dreng som dig"
            mc "vi burde nok at gå ud nu"
            ak "ja du har ret"
            "i gik ud af rummet"
        "nej":
            ak "okay øv,men hvordan skal jeg så give dig bæltet?"
            mc "bare skub den her ind"
            ak "okay"
            "hun skubbet bæltet ind i rummet du var i"
            mc "tak akira"
            ak "det var sålidt søde mc,jeg venter på dig her ude"
            "du tog bæltet på og gik ud af rummet"
    scene bg costume
    "da du gik ud så du akria i en fin blå kjole"
    ak "når hvas synes du kære?"
    mc "det passer dig godt"
    ak "tak søde,hvordan går det med bukserne"
    mc "det går helt fint,og tak for hjælpen"
    ak "det var sålidt søde mc"
    mc "um,hvorfor bliver du ved med at kalde mig søde eller smukke?"
    ak "det fordi jeg elsker dig fjolle hehe"
    mc "men vi er jo bare venner"
    ak "det ved jeg,men før eller siden vil du vælge en kærste,det en del af spillet"
    mc "vent hvordan ved du hvad der vil ske?"
    ak "det finder du ud af senere,men lige nu skal vi fukusere på nuet"
    s "um mc,jeg taber bukserne,og har stadig mit bælte der hjemme fordi jeg ikke noget at tage det på i morges som du sikkert husker"
    "du kunne se at sayori holdte på sine bukser og smilte helt flovt"
    ak "der er bælter over til højre der"
    s "tak akira"
    ak "det var da sålidt"
    "sayori gik mod til højre mens hun trak bukserne op flere gange og ledte efter et bælte"
    "efter i alle bliv færdige med at tage jeres kustymer på gik i ud til freddy"
    scene bg theater
    fx "luuuu jeg har lige fået bukser på"
    f "du ret dulled men okay,godt i alle er klædt på"
    f "nu skal i bare øve jer,og huske det skal gå som jeg har planlagt det,forstået!"
    "i alle nikket ja til freddy"
    f "godt,okay til at starte med skal i smølfer opføre jer som nogen er glade,og husk at i skalsynge smølfe sangen"
    "de begyndte at synge smølfe sangen mens de gik rundt og fik det til at lige at de arbejdet"
    f "perfekt,og så det nu at du skal træde ind helpy som den onde gagamel, og du skal virke ondskabsfuld"
    h "hahaha jeg er den fæle troldmand gagamel,nu skal jeg fange jer smølfer"
    f "nice,jeg sagde jo du passet perfekt til at være den grimme troldmand haha"
    f "og nu skal jer som spiller smølferne gå i panik og få det til at se rigtig dramatisk ud"
    "de begyndte at gå i panik"
    f "godt perfekt,og nu skal i så prøve at finde ridder mc"
    sa "jeg har en ide,kom med mig smølfer,vi må skynde os og lede efter ridder jacob som kan besjere den onde gagamel,og at rede os og prinsesen"
    f "NEJ!,det smukke prinsse du skulle sige øjj!"
    sa "vi må skynde os og lede efter ridder jacob som kan besjere den onde gagamel og at rede den smukke prinsesse"
    f "godt,og nu er i kommet til ridderen,og nu skal du mc virke moden og følge den manoskrift jeg har givet dig"
    mc "hvad er der sket små smølfe venner"
    sa "åh store mægtige ridder,hjælp os med at stoppe den fæle gagamel,han har fanget nogen af vores smølfer og den smukke prinssese"
    mc "frygt ej mine små venner,jeg vil hjælper jer med at besejre den fæle troldmand og befire jeres venner og min smukke prinssese"
    f "godt klaret,og nu er vi kommet til den store finale!,det er nu at gagamel og ridder mc mødes angsigt til ansigt og skulle kæmpe"
    f "og husk det til døden"
    h "vent hvad!,er du sindsyg!"
    f "jeg mente ikke at i vil dø bogstavligt dumme snegl!"
    mc "du vil nu blive beseret fælde gagamel,giv op eller mærk min vrede"
    h "haha,tror du virkelig at du kan stoppe mig,jeg er den mægtige gagamel"
    mc "vi får se"
    f "i kæmpet mod hindaen og det endte med at mc besejret gagamel,den grimme troldmand"
    h "behøver du virkelig at kalde mig grimme"
    f "hold dig til manoskriftet!"
    h "oh nej du har besjeret mig"
    mc "du vil nu dø for retfærdigheden"
    f "ridder mc svinget sit svære og stak den ned på grimme gagamel"
    h "arrrrrh,edvak"
    f "nu befriet ridderen smølferne og den smukke prinsese"
    s "tusind tak for at rede os trapper ridder,vi smølfer er evig taknemmelige"
    mc "tak,jeg er glad for at kunne hjælpe"
    ak "min helt"
    f "det nu at i skal kysse,men kun et lille et,forstået!"
    "i begyndte at kysse lidt og akira bliv så glad for det en eller anden grund"
    f "godt så skal i gøre det igen snart,"
    h "og hvad mener du med det?"
    f "øjjj helpy,du forstår bare heler ikke noget vel!"
    h "trash skole"
    f "der kommer nemlig snart publikum,og der skal i gøre som i lige har øvet,men der lige en fejl du begik sakura"
    sa "um hvad er det?"
    f "du kaldte ridderen for jacob!,han hedder altså ridder mc!"
    sa "åh det må du undskylde freddy"
    f "det okay,bare husk at hold dig til mit manoskrift"
    h "det virket ellers som om at du mente det surt"
    f "bland dig udenom snegl!"
    h "hvordan gik det overhovedt til at jeg gik i den her trash skole"
    "efter noget tid kom publikummet"
    f "godt de er kommet nu,okay start som i øvet"
    "i gjor jer forberet på at freddu siger til"
    f "klar og action!"
    "i gik i gang med jeres rolle spil foran en masse mennesker og animatronics selvføgelig"
    "det bliv et meget spændene theater stykke,og publikummet hjuplet"
    "helt tilsidst da du som ridder stoppet den onde troldmand,befriet du smølferne og prinsesen"
    "smølferne takket dig,og dig og prinsessen kysset,og publikummet blivet helt rørt"
    f "i gjor det så flot små børn,nu må i godt tage til opklædens rummet og få jeres kustymer af"
    fx "luuu jeg har ikke lyst til at tage bukserne af"
    fb "det lyd ret akavet"
    fx "luuuuu"
    f "du skal tage bukserne af!,det er ikke dine,det skolens!"
    fx "luuu,så bliver jeg halv nøjen"
    f "hvad snakker du om,robotter går normalt ikke i bukser!,og det var ingeng gang menningen at du skulle tage dem på"
    fx "skal jeg tage dem af her?"
    f "nej din spasser!,du skal gøre det i prøve rummet dumme dul!"
    "i gik alle hen til tøj rummet"
    scene bg costume
    ak "det var et smukt øjeblik mc"
    "hun kigger forælsket på dig"
    mc "heh,det var jo bare skuespil angåene kysset"
    ak "er du sikker på at det ikke var begrund af noget andet også"
    "hun gav dig et kærligt blik"
    mc "jeg er sikker"
    ak "åh søde søde mc,altids så kosbar,jeg kan lide det"
    mc "okay jeg går ind og tager det her rustning af nu"
    ak "fint nok,jeg skal vist også have den her kjole af"
    "du gik ind i prøve rummet"
    scene bg changing_room
    "du begyndte at tage din kustyme af"
    mc "puha det var godt nok varmt med den ridder kustyme"
    "det jo klart,du havet jo 2 par bukser på"
    mc "okay du ret dulled lige nu"
    "er jeg?"
    mc "ja,lige før"
    "du har ret,jeg var ret dulled,måske er det en dulle mod du spiller lige nu"
    mc "hvorfor er der så mange der kalder det her for et spil?"
    "jeg ved ikke hvorfor de andre gør det,når jo det ved jeg,for jeg ved alt om jer"
    mc "det lidt creepy"
    "creeper,oh mand"
    mc "??????"
    "jeg kan fortælle dig at grunden til at vi siger at det er et spil er bare for at drille dig"
    mc "arh okay,så forstår jeg det bedre"
    "eller mener vi det faktisk hmmmmm,en gåde"
    mc "okay,kan vi komme vidre"
    "det var flabet sagt"
    mc "??????"
    "du gik ud af prøve rummet og mødtes med sayori og akira"
    scene bg costume
    ak "hej mc,min smukke ridder"
    s "eh,hvordan kan du vide om det ikke er mig han elsker?"
    ak "fordi han elsker mig"
    mc "det har jeg aldrig sagt at jeg gjor"
    ak "men vi kyssede før"
    mc "fordi det var en del af theateret"
    ak "var det nu det hmmm"
    s "lad os gå mc,det her føles forkert"
    ak "fint,bare vent til fredag,der skal han nok vælge mig som kærste,vent at se!"
    "hun gik væk fra jer"
    s "er du okay mc?"
    mc "jeg klare den,jeg har dig"
    "hun bliv helt glad og rødmet af det"
    s "jeg er også glad for at jeg har dig,faktisk så håber jeg at det bliver mig som bliver din kærste hehe"
    mc "jeg kan ikke love noget,men vi får at se hvad der sker den dag hvor jeg skal vælge en kærste,som jeg en eller aden grund er tvunget til"
    "hun kigget forvirret og smilte igen bagefter"
    mc "men du ved godt at det bælte du bruger nu er skolens ik?"
    s "når ja,jeg lånte det bare for at ungå at tabe bukserne foran hele folket"
    mc "men du nok nød til at aflevere det igen"
    s "hvor nederen,så må jeg bare leve med at tabe bukserne"
    mc "sker det virkelig så ofte?"
    s "ja,jeg taber bukserne heletiden,det mega irriterende faktisk"
    mc "godt at du kan bruge dit eget imorgen så"
    s "hehe ja,for den her dag er ret pinlig for mig"
    "en eller anden grund bliv hun helt flov"
    "hun tog bæltet af og lagte det tilbage"
    "i gik sammen og undervejs glid sayoris bukser ned heletiden mens hun trak dem konstant op"
    scene bg theater
    f "godt,nu skal vi bare have spise pause"
    fx "haha,prøv at se sayori,hun taber bukserne heletiden llululululu"
    f "stille dul!"
    fx "luuu men hun"
    f "NEJ STOP JEG MENER DET,INGENG GIDER AT HØRE PÅ DIN DULLEDE KOMMENTAR!"
    s "tak freddy"
    f "det var sållidt,jeg magter ikke at skulle høre på hindes dullesnak"
    h "det første gang at jeg er enig med freddy"
    f "når men jeg vil tage til lære værelset og få noget at spise,tag hen til katinen elever"
    "i alle tog til katinen,og hen til chica for at bestille"
    scene bg cantineIdle
    chica "hej,hvad vil du bestille idag?"
    "nu skal du vælge mad,hvis du ikke viste det"
    mc "jeg viste det godt,jeg hørte hinde selv"
    menu:
        "pasta med kethub 25kr":
            chica "det bliver 50kr"
            "du gik over til katinen for at spise"
        "salat med kylling 30kr":
            chica "det bliver 60kr"
            "du gik til katinen for at spise"
        "pizza med kebab 100kr":
            chica "det bliver 200kr"
            "du bruger mange penge"
            "du gik over til katinen for at spise"
    scene bg in_cantine
    "du gik over til de andre og spiste,"
    mc "hmmmm,hvem skulle jeg mon spise sammen med idag?"
    menu:
        "sayori":
            "du gik mod sayori"
            "sayori griner lidt for sig selv"
            s "Okay, MC, jeg har en historie, der vil få dig til at tabe din mad!"
            "du kigger op fra din bakke"
            mc "Åh nej, hvad nu? Er det endnu en af dine… episke Sayori-historier?"
            "sayori nikker ivrigt"
            s "Du ved det! Hør her! Så… det var den der ene gang, hvor jeg havde travlt på vej til skole… Jeg havde lidt for travlt, faktisk"
            "du løfter et øjebryn,hvorfor taler jeg så mrækeligt?"
            mc "hvor travlt?"
            "sayori bliver helt rød i kinderne,men griner stadig"
            s "Så travlt, at jeg glemte at binde min bukser ordentligt!"
            "du stopper midt i at tage en bid"
            mc "åh nej,hvad er der sket?"
            "sayori klapper i hænderne sammen og ler højt"
            s "De faldt ned, MC! Lige foran butikken, hvor ALLE kunne se det! Jeg stod bare der med min skoletaske, og så… BAM! Bukserne nede om anklerne"
            "du prøver at holde et grin tilbage"
            mc "og hvad gjorte du så?"
            "sayori ligger hovedt på skrå og smiler bredt"
            s "Hvad tror du? Jeg samlede dem op og råbte: 'Det er en ny mode! I burde prøve det!' Og så løb jeg væk"
            "du griner højt,hvor er i bare dulled"
            mc "Det lyder så meget som dig, Sayori. Hvordan er du så… afslappet over det nu?"
            s "Hvorfor ikke? Jeg mener, det var pinligt, men det er også ret sjovt, når jeg tænker tilbage på det! Hvis jeg ikke kan grine af det, hvad kan jeg så gøre?"
            mc "Du har en måde at gøre alting mindre alvorligt på. Det er faktisk ret imponerende."
            s "Det er fordi jeg ved, at livet er for kort til at bekymre sig om småting! Plus, når jeg deler historien, får jeg også dig til at grine og det gør det hele det værd!"
            mc "Okay, Sayori. Du vinder. Men næste gang, så husk at tjekke dit tøj, inden du løber ud af døren."
            s "Aftale! Men hvis det sker igen, så har jeg i det mindste endnu en sjov historie at fortælle!"
            "klokken ringet og i skulle til klassen"
            mc "det var ellers så hyggeligt og dulled"
            s "haha ja,men næste gang skal jeg nok huske mit bælte"
            "i gik ud til skole gangen"
        "helpy":
            "du gik over til helpy"
            mc "hey helpy er du okay?"
            "helpy trækker skuldren uden at se op"
            h "Tja… så okay, som det kan være, når verden hader én."
            mc "hvad skete der nu?"
            h "Lad os se… Første time var en katastrofe. Læreren bad mig om at læse højt, og selvfølgelig snublede jeg over ordene"
            h "Alle grinede. Derefter smed jeg min penalhus ned på gulvet… igen. Og for at gøre det værre"
            h "så tog læreren mig til side og sagde, at jeg 'burde gøre en større indsats'"
            "du kigger alvorligt på ham"
            mc "Det lyder hårdt. Men det er ikke fair, at læreren siger sådan til dig. Du prøver jo."
            h "Måske… Men det føles bare som om, jeg ikke er god nok. Og hvad er pointen i at prøve, hvis det aldrig bliver bedre?"
            "du rykker din stol tætter på ham"
            mc "Helpy, jeg ved, det føles sådan lige nu, men det er ikke sandt. Du er god nok. Måske har du bare haft en rigtig dårlig dag"
            mc "eller uge. Men det betyder ikke, at det altid vil være sådan."
            "helpy ser op med et svagt smil"
            h "Du lyder næsten som en motiverende bog, du ved det godt, ikke?"
            "du griner blidt"
            mc "Måske, men det betyder ikke, det ikke er sandt. Hey, hvad siger du til, at vi finder noget, der kan få dig til at grine? Noget til at lette humøret lidt."
            "helpy trækker på skuldren,lyder underligt hvis du spøger mig"
            h "Som hvad? Jeg er ikke så god til at have det sjovt, husker du?"
            mc "Okay, hvad med det her"
            mc "Efter vi har spist, så prøver vi at slå en verdensrekord i… at stable plastikkopper."
            mc "Eller… vi kan finde på en virkelig dårlig vittighed, der er så dum, at den får os begge til at grine."
            "helpy kan ikke lade være med at smile"
            h "Du er virkelig dårlig til at finde på ideer, men… måske hjælper det. Bare lidt"
            mc "Så det er en aftale. Og husk, Helpy selvom du har uheldige dage, betyder det ikke, at du er alene om at klare dem. Jeg er her"
            "helpy kigger væk med let røde kinder"
            h "Du lyder skør. Men… tak."
            "klokken ringet og i skulle til den sidste time"
            h "okay så længe det ikke er toy freddy,så klare jeg den"
            mc "ja toy freddy er skåd,lad os tage til time"
            "i kom mod gangen"
        "natsuki":
            mc "Så… hvad har du med i dag? Noget fancy? Eller er det en af dine 'jeg havde travlt'-madpakker?"
            "natsuki Kigger hurtigt væk, men man kan se, at hun smiler lidt"
            n "tsk, hvorfor skulle det interessere dig? Det er bare ris og grøntsager. Ikke noget særligt"
            "du læner dig frem,det kunne være sjovt hvis du faldt og slog dig"
            mc "Det lyder ret sundt. Helt anderledes end min kedelige sandwich"
            "natsuki Kigger på hans mad og sukker"
            n "Selvfølgelig spiser du en sandwich. Så standard."
            mc "Hvad kan jeg sige? Jeg er en simpel fyr med simple behov"
            "natsuki ruller med øjnene"
            n "Simpel er en pæn måde at sige kedelig på."
            "du Lader som om han er såret,sikkert bare for at se hindes bløde side"
            mc "Av, Natsuki. Jeg troede, vi var venner."
            "natsuki rødmet lidt,se selv efter,hvor er jeg bare sjov til at drille hinde"
            n "Hvem sagde, vi ikke er venner? Jeg mener bare, du kunne prøve lidt hårdere, når det kommer til mad"
            n "Bare fordi du ikke kan lave noget, betyder det ikke, du skal spise noget så… kedeligt."
            mc "Så hvad foreslår du? Skal jeg begynde at bage cupcakes som dig"
            "natsuki Sætter maden fra sig og ser på dig"
            n "Hmpf, som om du nogensinde kunne gøre det lige så godt som mig"
            n "Men det ville i det mindste være bedre end den her… sandwich-ting"
            mc "Okay, udfordring accepteret. Næste gang skal vi lave noget sammen, og så ser vi, hvem der laver det bedste"
            "natsuki Ser overrasket ud et øjeblik, men skubber hurtigt smilet væk"
            n "tsk, det er spild af tid. Men… hvis det betyder, jeg kan vise dig, hvor dårlig du er, så fint. Bare vær klar til at tabe."
            mc "Vi får se. Men hvis jeg vinder, skylder du mig en cupcake."
            "natsuki Kigger væk og gemmer sit smil"
            n "Som om det nogensinde ville ske. Men… okay. Aftale. Bare ikke begynd at græde, når jeg slår dig"
            "i kunne høre klokken ringe"
            mc "okay hvad siger du til at vi prøver at bage sammen igen på mandag?"
            n "det kan vi godt,men kom så,vi skal til time"
            "i gik mod gangen"
    scene bg hallWay
    "du så vanny er tilbage,men mistet et øje"
    mc "wow,er du okay vanny,hvad er der dog sket med dig?"
    vanny "jeg ved ikke hvor langtid jeg har"
    mc "hvad mener du med det?"
    vanny "jeg tror at glitchtrap vil dræbe mig,han gjor det her mod mig"
    mc "det jo alvorligt,vi må sige det til rekteren"
    vanny "tror du det vil hjælpe?,har prøvet,rekteren var ligeglad,så jeg turde ikke at gå i skolen og bliv hjemme"
    mc "det ikke godt,jeg vil prøve at snakke med ham idag om det"
    vanny "bare være forsigtig,man ved aldrig hvad han kan finde på"
    "du rystet i bukserne af det der skete"
    "og i gik ind til klassen"
    scene bg class_day
    "i stod og ventet på læren"
    h "pls lad det nu ikke være toyfreddy igen,pls skole være sød"
    "toy freddy kom ind,ej du troet lige var haha,det glitchtrap der kom ind"
    h "hmm,det heler ikke godt,men det bedre in toy freddy"
    glitchtrap "godag elver,det længesiden var"
    h "ikke længe nok"
    glitchtrap "du skal bare tie stille lille snegl"
    h "seriøst virkelig?,nu også dig der kalder mig snegl"
    glitchtrap "det jo klart,du er lille og langsom som en"
    h "der er bare ikke noget værre in den her skole"
    glitchtrap "i den her time skal i lærer om hvorfor jeg hader vanny"
    h "er du seriøs!,hvad lærer vi overhovedt af det!"
    glitchtrap "vi lære om hvem man bare skal hade"
    h "men det får vi jo heler ikke noget ud af!"
    glitchtrap "STILLE SNEGL!"
    "helpy turde ikke at sige mere,det forstår jeg godt"
    glitchtrap "når men du kan starte mc,nævn en grund til at jeg hader vanny"
    mc "er det fordi hun har magiere?"
    glitchtrap "godt klaret mc,du består"
    h "kan du ikke komme med noget mere svært næste gang?"
    glitchtrap "okay,du bedte selv om det"
    h "endelig,tak"
    glitchtrap "hvorfor lugter pumbaa?"
    h "ikke mod mig!"
    glitchtrap "det sagde jo mine opgaver var for nemme,så nu får du en svær en"
    h "jeg mente mod de andre ikke mig,jeg får det jo heletiden!"
    glitchtrap "surt show snegl,men du dumper"
    h "what!jeg noget jo slet ikke at svare på spørgsmålet!"
    glitchtrap "og ved du hvorfor du ikke gjor det"
    h "fordi i alle lærer er trash"
    glitchtrap "nej fordi du er langsom som en lille taber snegl hahhahaha"
    glitchtrap "din tur VANNY!"
    glitchtrap "hvorfor får jeg altid lyst til at smadre dig"
    vanny "fordi du hader mig"
    glitchtrap "forkert,fordi jeg hader dig og fordi du bruger magiere"
    vanny "men du sagde ikke noget om at jeg skulle svare på 2"
    glitchtrap "det var bare søn VANNY"
    glitchtrap "din tur svampebob,hvorfor piller folk sig i næsen"
    sb "bahahaha,du godt nok klam"
    glitchtrap "WHAT ER DU SINDSYG MAND DU FLABED!,DUMPEEEEEEET!"
    glitchtrap "så det dig bonnie ponny"
    fb "behøver i virkelig at kalde mig det heletiden"
    glitchtrap "ja vi gør,det din nye kæle navn"
    fb "men jeg vil ikke have det"
    glitchtrap "TUDEFJÆS TUDEFJÆS!"
    glitchtrap "SVAR SÅ PÅ SPØRGSMÅLET PONNY!"
    fb "du har jo ingen gang givet mig nogen,har du hukkomelses tab?"
    glitchtrap "WHAT HVOR FLABED,DU DUMPET!"
    fb "hvordan kan jeg dumpe når du ingeng gang har givet mig en opgave at svare på!"
    glitchtrap "FORDI DU VAR FLABED!"
    glitchtrap "din tur sayori,hvad gøre vanny så irriterende"
    s "uuu den er svær,er det fordi at hun praler med sine magiere"
    glitchtrap "ligepresis sayori,du består,dig og mc er okay"
    glitchtrap "din tur natsuki,hvorfor gør vanny mig altid så vred?"
    n "er det fordi at hun er bare irriterende generalt?"
    glitchtrap "det rigtigt,du består!"
    glitchtrap "din tur yuri kedeligsen"
    y "hvorfor synes du at jeg er kedelig?"
    glitchtrap "lad mig se hmmm,når ja,du er mindre følsom in alle andre,og du er dyster,og klog på den kedelige måde,jeg kunne blive ved heledagen hahaha"
    y "?????"
    glitchtrap "når men svare på det her yuri,fortæl mig en god joke"
    h "hvordan skulle hun kunne gøre det når du lige har nedgjort hinde!"
    glitchtrap "STILLE SNEGL!"
    y "okay jeg prøver,bank banke på"
    glitchtrap "hvem der"
    y "dumpet"
    glitchtrap "hmmm,det var en okay joke,for det minder mig om vanny der dumper,du består"
    glitchtrap "din tur ayano,hvem tror på flæske kongen?"
    h "okay så nu har vi åbenbart quiz time eller hvad?"
    glitchtrap "ja,for nu jeg ikke sur på vanny mere"
    h "det giver ingen menning"
    ay "tror det er bonnie"
    glitchtrap "du består"
    ay "vil i vide hvordan jeg kune vide det?"
    glitchtrap "nej,vi magter ikke at høre på din kedelige viden"
    ay "what?"
    glitchtrap "du er bestået,så hver nu bare glad for DET!"
    glitchtrap "din tur akira,hvordan ungår man at blive taget med bukserne nede"
    ak "det ret dulled,man bruger bare et bælte"
    glitchtrap "forkert"
    ak "men det holder jo bukserne oppe"
    glitchtrap "ja men jeg mente det jo ikke bogstavligt,det var et ordsprog du dumper"
    fx "luuuu bukserne har talt"
    glitchtrap "tie stille dul!"
    "glitchtrap kom lige i tanke om at han lyd ret dulled før,og han regnet med at det var vanny der fik ham til det"
    glitchtrap "UUUUUU DU SÅ OP VANNY!"
    vanny "what hvad har jeg nu gjort"
    glitchtrap "SPIL IKKE DUM,DU VED GODT HVAD DU LIGE GJOR!"
    vanny "?????"
    glitchtrap "DU FIK MIG TIL AT TALE OM BUKSER,DU SKULLE TIL AT GØRE MIG DULLED"
    vanny "det vil edtemindste ændre din personlighed"
    glitchtrap "WHAT VANNY DU SYG I HOVED.JEG NAKKER DIG MAND!"
    "efter glithtrap kølet ned igen underviste han vidre"
    glitchtrap "din tur funtimedul,hvad kan gøre en oppustet"
    fx "luuu bukser"
    glitchtrap "forkert,du dumper"
    glitchtrap "du den sidste her saruka,når ja og bedste mor gris,jeg var lige ved at glemme dig"
    br "ej du,kan du tage dem på ahohoh"
    fx "luuuu bukser på"
    br "tag dem på tag tag tag dem på"
    fx "lulululululu"
    glitchtrap "når men saruka,hvordan fjerner man en pølle"
    sa "man skyllder dem ud i toiletet?"
    glitchtrap "det rigtigt du består"
    br "ej er der en der pøllet ahhohohoh"
    glitchtrap "din tur cupcake"
    br "upser"
    fx "bukser"
    glitchtrap "okay hvem er ledren i danmark lige nu"
    br "ej den er umulig du ahohoh,men jeg tror det er timon"
    glitchtrap "wow hvor forkert kan man lige værre !"
    "klokken ringet og i alle havet fri"
    "du ventet til at de andre gik ud så der kun var dig og glithtrap tilbage"
    mc "må jeg spøger dig om noget glitchtrap?"
    glitchtrap "ja selvføgelig"
    mc "er det ikke lidt for voldigt at skade vanny fysisk?"
    glitchtrap "åh stakkels forvirret mc,vanny er altså ikke så flink som du tror"
    mc "jeg forstår det ikke"
    glitchtrap "det ved jeg,så derfor vil jeg forklare hvorfor at hun har fortjent det"
    glitchtrap "jeg tror at vanny er en ond trold kvinde,du ved magikere,og hun er ret ond"
    mc "hvordan ond?"
    glitchtrap "hun prøvr at kontrolere vores personligheder,og nogen gange prøver hun at skade den her verden med at få det til at craze"
    glitchtrap "håber du forstår mig"
    "han kigger på dig som om at han vil høre din menning,hvad vil du svære?"
    menu:
        "jeg tror på dig":
            mc "jeg forstår nu at vanny er den onde,jeg er på din side"
            glitchtrap "ved du hvad,du en god elev,faktisk min ynglings elev"
            mc "det jeg glad for at høre,du er min ynglings lærer"
            glitchtrap "tak,det betyder meget,når men du må heler tage ud,du skal nydig komme sendt hjem"
            mc "det vil jeg,ses en anden dag"
            "du gik ud mod clubben"
        "du for ond mod vanny":
            glitchtrap "WHAT!,HVORDAN KAN DU VENDE MOD MIG PÅ DEN MÅDE"
            mc "jeg synes bare at det søn for vanny,og som om at hun har magiere,det giver ingeng menning"
            glitchtrap "det en skam,du var ellers min ynglings elev"
            mc "jeg er ked af det,men jeg kan ikke se noget ondt i vanny"
            glitchtrap "det burde du også at være,nu kom her!"
            "han kom pludseligt mod dig med en kniv"
            "du løb væk og lukket døren foran ham og ind i et skab som kan skjule dig fra ham"
            scene bg school_closet
            "du begyndte at græde,tudefjæs"
            mc "det jo klaret når jeg skulle til at dø"
            "du kunne høre hans fodtrin ikke var der mere,så du kom ud igen"
            scene bg hallWay
            "ingen spor af ham,han er nok taget ud af skolen,så du tog mod clubben"
    scene bg corridor
    "du så eddy foran dig,han kom hen til dig"
    eddy "hej"
    mc "hej eddy,så hvordan er det gået med dig?"
    eddy "det går meget fint,og hvordan går det med dig i clubben?"
    mc "det går helt fint"
    eddy "glæder du dig til at være sammen med monika idag"
    mc "ja,vent hvor ved du det fra?"
    eddy "det en hemmelighed,det bedst at du ikke ved det"
    mc "hvorfor?"
    eddy "når men hyg dig med monika,jeg skal hjem nu,og husk at pas på med monika,har hørt at hun har noget specielt"
    "du skulle til at spøger ham om mere,men han er allerede gået"
    "du gik ind i clubben"
    scene bg club_day
    m "hej mc,jeg glæder mig til vores særlig dag"
    "sagde hun med et lunt smil"
    mc "tja jeg tror også at det bliver spændene"
    m "okay her er planen,mig og mc er sammen,sayori og helpy er sammen,og natsuki og yuri er sammen"
    s "yay det bliver så sjovt helpy"
    h "normalt vil jeg sige elenlig ikke,men den her gang siger jeg ja,det bliver sjovt"
    n "lad os bage nogen cupcakes yuri"
    y "um okay"
    m "når mc,lad os tage til musikintrument lokalet"
    mc "god ide"
    "i gik mod musik lokalet"
    scene bg classWindow
    "da i ankom så du de forskelige musik intrumenter"
    mc "wow der mange intrumenter,det så smukt"
    m "ja ik,det er her jeg slapper af når jeg har det svært"
    mc "spiller du så musik her inde"
    m "ja,vil du høre mig spille klaver"
    mc "det vil jeg meget gerne"
    "hun begyndte at spille klaver,det lyd ret smukt"
    mc "wow du god til det"
    m "hehe tak,hvor du sød,jeg har øvet mig"
    "MC og Monika sidder i musiklokalet efter skoletid. Solens stråler skinner ind gennem vinduet og giver rummet en varm glød"
    "Monika sidder ved klaveret, mens MC sidder med en guitar, han ikke er helt sikker på, hvordan han skal spille"
    "Monikas smil er beroligende, men der er noget anderledes i luften som om hun er lidt mere opmærksom på MC end sædvanligt."
    "monika læner sig mod klaveret"
    m "Okay, MC, lad os prøve igen. Denne gang skal du bare følge akkorderne"
    m "jeg spiller. Du behøver ikke være perfekt bare følg rytmen"
    "du kigger nervøst på guitaren"
    mc "Det er nemt for dig at sige. Du spiller klaver, som om du blev født til det. Jeg… knap nok kan huske, hvordan jeg holder denne her ting."
    m "Kom nu, du gør det fint! Det handler ikke om perfektion. Musik er en følelse. Hvis du kan mærke det, kan du spille det"
    "du Kigger op og møder hendes blik"
    mc "Det lyder smukt. Er det sådan, du ser på musik?"
    "monika Ser kort ud ad vinduet, men smiler svagt"
    m "Ja… Musik er som en måde at udtrykke alt det, man ikke kan sige med ord. Det er… ærligt"
    mc "Det er måske derfor, du er så god til det. Du virker altid så… ærlig."
    "monika rødmer og kigger lidt væk"
    m "Det er sødt sagt, MC. Men… ærligt talt, nogle gange føler jeg mig ikke så perfekt, som folk tror, jeg er"
    "du Sætter guitaren lidt fra dig og læner dig frem"
    mc "Det er okay, Monika. Ingen forventer, at du skal være perfekt hele tiden. Du er allerede ret fantastisk, bare ved at være dig"
    "monika Kigger på dig med et blik, der afslører en blanding af taknemmelighed og noget mere"
    m "Tak, MC… Det betyder meget at høre det fra dig"
    "du Griner lidt for at lette stemningen"
    mc "Det er det mindste, jeg kan gøre. Når alt kommer til alt, redder du mig her fra at lyde som en knækket strenget guitar"
    "monika griner og ryster i bukserne,jeg mener i hovedt"
    m "Du undervurderer dig selv. Hør, lad os prøve noget nyt."
    "du løfter et øjenbryn,det lyder mærkeligt"
    mc "nyt som hvad?"
    "monika Rykker lidt tættere på og ser dig direkte i øjnene"
    m "Jeg spiller en simpel melodi, og du improviserer teksten. Ingen pres bare sig, hvad du føler."
    mc "Sig, hvad jeg føler? Okay, det kan ikke gå galt, vel?"
    m "Ikke når det kommer fra dig"
    "Monika begynder at spille en blid melodi på klaveret"
    "du prøver nervøst at finde ordene, men dine blik bliver hængende på Monika."
    "Hendes nærvær gør dig rolig, og du begynder langsomt at improvisere. Teksten handler om øjeblikke"
    "der føles specielle og folk, der gør alting bedre, bare ved at være der"
    "Da du slutter, er rummet stille. Monika stopper med at spille og ser på dig med et varmt smil"
    m "Det var… smukt, MC"
    "du griner akavet"
    mc "Du mener ikke frygteligt?"
    "monika ryster i bukserne, Ryster på hovedet"
    m "Nej. Jeg mener smukt. Du har en måde at sige tingene på, som… rammer lige ind. Jeg tror, jeg kunne lytte til dig hele dagen."
    "jeres øjne mødes, og der er et øjebliks stilhed mellem jer, fyldt med noget usagt"
    "men tydeligt. Monika rømmer sig og vender tilbage til klaveret, selvom hun stadig smiler lidt genert"
    m "Okay, lad os prøve en duet næste gang. Men… kun hvis du lover ikke at overskygge mig med dine tekster"
    mc "Det lover jeg. Men jeg er sikker på, du altid vil stjæle showet, Monika."
    "klokken bliv 17:00,så det er lukke tid"
    mc "øv,nu var det ellers lige så sjovt"
    m "ja,men vi kan altid være sammen en anden dag"
    mc "det jo rigtigt nok"
    "i gik ud til de andre igen"
    scene bg club_day
    m "hej så hvordan gik det alle"
    s "tja mig og helpy har haft det rigtigt sjovt sammen,selv om jeg tabte bukserne heletiden"
    h "selvføgelig gjor du det"
    n "og mig og yuri har bagt cupcakesne"
    y "vi lavet dem i sødme"
    n "hey,glem nu ikke cool"
    m "godt i alle har haft det godt,men ses"
    "de andre gik og monika stoppet dig i at gå"
    m "jeg vil lige sige noget til dig mc"
    mc "ja selvføgelig hvad er det?"
    m "jeg er forælsket i dig,og jeg håber at du vil vælge mig som kærste"
    mc "jeg kan ikke love noget,men du er en sød ven"
    m "tak,jeg håber at du vil vælge at være sammen med mig igen i clubben imorgen"
    mc "vi finder ud af det der,ellers kan vi alle være sammen istedenfor"
    "i gik ud for at komme ud af skolen"
    scene bg school
    "darthjacob kom mod dig da du kom ud af skolen"
    da "jeg sagde jo at du skulle holde dig væk fra monika"
    mc "men hun virker så sød"
    da "det kan godt være,men hun er bogstavligtalt forælset i dig"
    mc "det ved jeg,hvad der slemt ved det"
    da "det er ikke det der er slemt,hun er besat af dig,og hvis du vælger hinde vil hun sikkert ingeng gang lade dig værre nogensinde"
    mc "aldrig?"
    da "ja aldrig,borset fra at hun vil nok lade dig værre når du skal på wc,men ellers vil hun være meget klistrene"
    mc "okay,jeg vil prøve at være forsigtig med hinde"
    da "godt,for du har fortjent en god slutning,du vores ynglings elev"
    mc "ja borset fra baldi,han hader mig"
    da "vent what,hvordan kan man hade dig?"
    mc "for hvert fejl jeg laver,kalder han mig ubruglig og dum og alt muligt ondt"
    da "WHAT!,DET SKAL HAN IKKE HAVE LOV TIL!"
    da "jeg snakker med ham om det,jeg vil fyre ham hvis det er nødvendigt"
    mc "tak,du en god rekter"
    da "tak,de fleste synes at jeg er skåd og har for mange regler,men du den eneste elev der kan lide mig såden som jeg er"
    da "også selv om jeg kan være lidt sindyg,når men ses imorgen mc,og husk at komme til tiden som altid"
    mc "det skal jeg nok ses"
    "du så ham køre hjem af og du gik tætter på dit hjem"
    scene bg street
    "klokken var 18:00,fordi dig og darthjacob snakket i en evighed,"
    mc "jeg kan bare godt lide at snakke"
    "det behøver du ikke at fortælle mig"
    mc "??????"
    "da den ikke var så mange tog du til byen for at handle"
    scene bg resturent
    mc "hmmm,jeg tænker at jeg vil købe noget nemt at lave"
    "du købte nogen thaibox og noget andet mad så du har til flere dage"
    "pludseligt kom akira"
    ak "hej mc,hvor sjovt at jeg lige stødte ind i dig"
    mc "oh hej akira,godt at se dig"
    ak "hvorfor gør du det imod mig?"
    mc "gøre hvad?"
    ak "du altid sammen med de andre piger,men du vælger aldrig mig,kan du ikke lide mig"
    "hun begyndte at græde,tudefjæs"
    mc "hey jeg kan godt lide dig,det bare svært når i alle vil være sammen med mig"
    ak "og derfor holder du mig ude?"
    mc "undskyld akira,hør hvad siger du til at tage med mig hjem?"
    "hun begyndte at smile igen og så flirtene ud igen"
    ak "det vil jeg meget gerne,tak mc"
    "i gik sammen til dit hjem"
    scene bg kitchen
    ak "wow så det her er dit køkken,meget smukt"
    mc "tak,jeg er glad for at du kan lide det"
    "i begyndte at lave nogen thaibox,2 til hver"
    ak "det så sødt af dig at dele din mad med mig,du er bare sød"
    mc "tak,du også en god ven"
    "i gik ind i stuen for at se en film,og selvføgelig ser du altid den mærkelige og kedelige film"
    scene bg livingroom
    "i spiste jeres mad færdigt og talte lidt,husk at klokken nu er 20:00 batman"
    ak "Det er så rart, at du lod mig komme til dig i dag, MC. Jeg har ventet hele ugen på at tilbringe tid med dig"
    mc "Heh, ja. Det er også rart at hænge ud.det er hyggeligt"
    "akira Læner sig lidt tættere på"
    ak "Hyggeligt? Åh, MC, du behøver ikke være så beskeden. Du kan sige, det er specielt, når jeg er her. Alt føles bedre med dig"
    "du griner akavet"
    mc "Det er… virkelig sødt sagt, Akira. Jeg mener det. Men jeg er sikker på, du siger det til alle"
    "Hendes øjne bliver skarpe i et øjeblik"
    "men hun genfinder hurtigt sit smil"
    ak "Alle? Som om nogen andre kunne få mig til at føle sådan her. Det er kun dig, MC"
    "du prøver at ændre emnet"
    mc "Heh, så… har du noget nyt på programmet i denne uge? Noget sjovt, måske?"
    "akira Læner sig tilbage, men holder stadig øjnene på dig"
    ak "Hmmm, ikke rigtig. Det eneste, jeg tænker på, er, hvordan jeg kan bruge mere tid med dig"
    ak "Skolen er sådan et spild af tid, ikke? Vi kunne lave så mange andre… mere interessante ting"
    mc "Jo, skolen er ret krævende, men det er vigtigt. Og hey, vi hænger jo ud nu, ikke? Det er ret fedt"
    "akira Leger med en lok af sit hår og smiler næsten drilsk"
    ak "Det er det, ja. Men nogle gange føler jeg, at du… ikke ser, hvor meget jeg gør for at få vores tid sammen til at ske"
    mc "Hvad mener du"
    ak "Åh, ingenting. Bare… at jeg sørger for, at folk ikke afbryder os. Som tidligere i dag"
    ak "en eller anden pige prøvede at tale med dig efter klasse, ikke? Hun virker så… irriterende"
    "du bliver lidt anspændt"
    mc "Åh, du mener… monika? Hun spurgte bare om lektierne. Der var ikke noget særligt"
    "akira Lænende sig tættere på og kigger dig direkte i øjnene"
    ak "Du er så naiv, MC. Jeg ved, hvad piger som hende tænker. Men du skal ikke bekymre dig"
    ak "jeg skal nok sørge for, at hun holder sig på afstand"
    "du smilte nerøvst"
    mc "Akira, det lyder… lidt overdrevet. Jeg er sikker på, at hun ikke mente noget med det"
    "Hendes smil bliver større, men hendes øjne forbliver intense"
    ak "Måske. Men hvorfor tage chancer, når jeg kan beskytte dig? Ingen forstår dig, som jeg gør, MC"
    ak "og ingen vil passe på dig som mig"
    "du prøver at aflede igen"
    mc "Det er virkelig… sødt af dig, Akira. Men hey, lad os tale om noget sjovere. Har du set den nye serie, alle taler om?"
    "akira Kigger på dig et øjeblik og skifter derefter tone"
    ak "Åh, du mener Crimson Hearts? Ja, den er ret god. Selvom hovedpersonen minder mig lidt om dig"
    ak "han har den der måde at få alle til at stole på ham, uden han selv er klar over det. Det er… fascinerende"
    mc "Heh, det lyder som en fed karakter. Måske skulle jeg tjekke den ud"
    "akira Smiler blidt, men hendes stemme har stadig en undertone"
    ak "Måske kunne vi se den sammen næste gang. Jeg kunne godt lide at have dig her lidt længere. Bare os to"
    mc "det kunne vi godt,hvad siger du til tirsdag?"
    ak "det vil være perfekt"
    "hun begyndte at kramme dig"
    "klokken var nu 22:00,nu skal i putte putte"
    ak "må jeg sove her?"
    mc "tja det ret sendt nu,jeg kan vise dig vejen til gæste værelset"
    ak "jeg tænkte på om jeg kunne sove hos dig"
    mc "men det ikke fordi vi er kærster"
    ak "derfor kan vi da stadig sove sammen fjolle,vi venner"
    mc "men jeg har slet ikke 2 senge"
    ak "men jeg vil så gerne sove med dig"
    "hun virket besat"
    mc "beklager du må sove i gæste værelset"
    ak "okay fint,vis mig vej"
    "du viste hinde vejen der over"
    scene bg door
    mc "det er her inde"
    ak "aligevel,tak for idag mc,det har været en hyggelig aften"
    mc "det var så lidt,hvad har man venner til"
    ak "hehe så sandt,godnat søde"
    "du gik op til dig selv og sov"
    scene bg bedroom_evil
    "der var nogen uhyggelige røde øjne et sted,men du var så træt da den er 23:00 at du slet ikke ligget mærke til det"
    "du faldte i søvn,og du hørte nogen hviske"
    ak "jeg vil altid være ved din side"

    return
    



































































    
    
    






    







            































            
        




        

        
        
        
            
        





    









    








                


