label ch5_main:
    
    $ currentDay = "Fredag"
    play music t8
    scene bg bedroom

    "FREDAG"
    "du stod op og tog tøj på"
    mc "det må være idag der sker noget specielt"
    "det er det nemlig ja"
    "du gik mod køkknet"
    scene bg kitchen
    mc "tid til noget morgen mad"
    mc "jeg håber at der er noget godt"
    "her er dine muligheder"
    menu:
        "risat":
            "hvorfor risat?"
            mc "er det ikke normalt at spise til morgen mad?"
            "næ"
            "du tog noget risat og spiste det"
        "kylling med rugbrød":
            "godt valg"
            mc "tak"
            "du tog noget kylling med rygbrød,og begyndte at spise"
        "æg og bacon":
            "du lavet noget æg og bacon"
            "bagefter spiste du det og lagte dine ting du brugte i opvasken"
    mc "det var lækkert med noget morgen mad"
    "det kan jeg godt forstå,og nu skal du afsted"
    mc "når ja,jeg vil nydlig komme forsendt"
    "du gik ud af huset"
    scene bg street
    play music t2
    "du så sayori komme hen mod mig"
    "wow,hun taber ikke bukserne den her gang"
    s "hej mc,kan du se noget nyt i mig idag?"
    mc "du taber ikke bukserne?"
    s "ja det mega nice"
    mc "det nogen pæne bukser du har på"
    s "tak,jeg tænkte bare at jeg vil prøve noget nyt,og elsker bare de her sorte baggy jeans jeg har på nu"
    mc "de klær dig også"
    s "hehe,du så sød mc"
    mc "du taler som om at du er forælsket i mig"
    s "oh,um jeg vil bare være flink,og jeg synes også at du er sød,den sødeste dreng der er"
    "i gik sammen hen til skolen"
    scene bg school
    play music t3
    "i mødte freddy og toy freddy foran skolen"
    "når ja,og helpy selvføgelig"
    tf "velkkomen små børn,godt at være har igen"
    h "åh nej,hvorfor lige de 2,på en FREDAG!"
    f "det rigtigt små børn,idag får i springtrap til at starte med og"
    h "nooooo,så skal vi høre på de skræld jokes heledagen"
    f "stille snegl,du afbryder!"
    tf "200kr i bøde for at afbryde læren helpy"
    f "som jeg var ved at sige da jeg bliv AFBRUDT af en SNEGL,får i mig efter springtrap,og tilsidst toy freddy"
    h "hmmm,måske skulle jeg begrave mig selv ilive"
    f "når men kom elever,hen til skolen og hav det sjovt"
    h "du mener vil kom til skolen og bliv tortureret"
    "i gik ind i klassen"
    scene bg class_day
    play music t4
    h "jeg havet glædet mig såden til fredag,og selvføgelig skal vi abselut have toy freddy!"
    mc "godt det så snart er weekend"
    h "godt for jer,jeg bor jo stadig skolen begrund af toy freddys bøder"
    mc "det ret nedren at jeg ikke kunne overtale rekteren til at få dem fjernet"
    "pludseligt kom en lære ind"
    springtrap "hvad så der små noobs,nu får i mig"
    h "jeg tror snart at jeg begynder at græde"
    springtrap "nej det må man ikke"
    h "hvorfor ikke det?,det giver jo ingeng menning"
    springtrap "fordi ingeng gider at høre på en tudefjæs"
    h "what!,det er fredag"
    springtrap "og?"
    h "der burde i at være flinker!,for det er den dag der burde at være god for alle!"
    springtrap "når men idag skal vi have"
    h "åh nej lad mig gætter,jokes undervisning"
    springtrap "nej noget inu bedre"
    h "waow,det lyder faktisk godt"
    springtrap "i skal lave tøj desing"
    fx "luuu,så skal jeg lave nogen par bukser"
    h "what!,jeg viste ikke at du var en dulle lære!"
    fx "jeg kan godt lide det"
    h "selvføgelig kan du det"
    fx "prøv at forstille dig alle de bukser man kunne lave"
    h "ummmm,nej tak"
    springtrap "i skal deles op i 2 grupper"
    h "jeg vil gerne være gruppe med bonnie"
    springtrap "tror du at du må selv bestemme eller hvad"
    h "ja,er det ikke det der er menningen med en gruppe"
    springtrap "ikke på min måde,på min måde bestemmer jeg jeres hold"
    h "what det trash!"
    springtrap "du skal være i gruppe med funtime foxy lille snegl a a a a aa"
    h "nej!"
    fx "luuuu,vi kan få matchene tshirts helpy"
    h "kan vi ikke lige bytte gruppe"
    springtrap "nej,jeg har valgt"
    h "jeg hader den her skole"
    springtrap "mc du er sammen med sayori"
    s "yay,alle de bukser vi kan lave,og så vil jeg lave dem såden at de ikke falder ned"
    mc "det godt nok dulled sagt,men er glad for at vi kan være i gruppe"
    springtrap "bonnie og svampebob skal være sammen"
    sb "bahahahah,det bliver sjovt"
    fb "det mener du ikke mand!"
    h "edtemindste skal du ikke være sammen med en dul"
    springtrap "natsuki og,hmmmm,yuri er har ikke,så må du være i gruppe med ayano"
    n "endelig er jeg i gruppe med en der forstår coolnes"
    ay "jeg har ikke prøvet at være i gruppe med dig"
    n "ja,det bliver ret cool"
    springtrap "også er akira og sakura sammen"
    ak "det må være en fejl,jeg skulle være sammen med mc"
    springtrap "surt show,jeg bestemmer hvem i er sammen med"
    springtrap "nu hvor jeg har delt grupperne helt færdigt skal i bare komme igang nu"
    "i begyndte at arbejde sammen i 2 og 2,du heldig at du skulle være sammen med buks sayori"
    s "MC! Hvad synes du om det her stof? Det er så blødt og sødt! Perfekt til en glad kjole, ikke?"
    mc "Det er ret fint, Sayori. Men vi skal også tænke på, om det passer til resten af designet. Har vi valgt, hvilken farve vi bruger til toppen?"
    s "Hmm… Hvad med noget lyseblå? Det ville se rigtig venligt og frisk ud sammen med det lyserøde."
    mc "Det kunne faktisk fungere. Vi skal bare sørge for, at det ikke bliver for skrigende sammen"
    s "Som om tøjet råber: 'Se mig! Se mig!'?"
    mc "Ja, noget i den stil. Vi vil gerne have noget, der siger: 'Jeg ser godt ud,' uden at råbe det ud over hele rummet"
    s "Jeg ser godt ud! Kig på mig"
    s "Nej, det ville være alt for meget"
    mc "Du er utrolig, Sayori. Men okay, lad os gå med lyseblå og lyserød. Hvad synes du om at lave en nederdel med små blomster på"
    s "Åh, blomster! Det er så sødt! Og det vil passe så godt til foråret!"
    mc "Så er det afgjort. Jeg tegner det op, og du kan vælge, hvilken type blomst vi skal bruge"
    s "Hmm… Måske små margueritter? Eller kirsebærblomster? Hvad synes du, MC?"
    mc "Jeg synes, du har bedre smag, når det kommer til det søde og fine. Jeg stoler på dig"
    s "Virkelig? Okay, så vælger jeg margueritter! De er så glade og venlige, ligesom tøj skal være"
    mc "Margueritter det er. Hvordan går det med at klippe stoffet ud? Skal jeg hjælpe"
    s "Jeg tror, jeg kan klare det! Men hvis jeg klipper skævt, må du love ikke at grine"
    mc "Jeg lover ikke noget. Men jeg hjælper med at rette op på det, hvis det går galt"
    s "Okay, det er en aftale! Men jeg tror, vi får lavet det sødeste tøj i hele klassen"
    mc "Med dig som partner, Sayori, er jeg sikker på, at vi gør"
    "i bliv færdig med jeres tøj desing"
    springtrap "tiden er gået,lad mig høre og se jeres tøj desing"
    mc "mig og sayori har lavet en lyserød kjole og sorte par cowboy bukser"
    s "ja,det godt at man ikke kan tabe sin kjole hehe"
    springtrap "det meget flot,i består"
    h "jeg forstår det ikke"
    fx "luuuu,hvad mener du,se lige alle de bukser vi har lavet"
    h "men de er alle for store jo!"
    fx "luuuu,så har man en grund til at have et bælte"
    springtrap "i dumper helpy og funtime foxy,de for store"
    h "jeg sagde jo at vi skulle lave dem mindre"
    fx "hvordan vil du ellers tabe bukserne"
    h "det jo ikke menningen at de skal falde ned,hvad sker der for dig!"
    fb "seriøst hvorfor har du lavet vores tøj helt firkandtet"
    sb "bahahaha,det så jeg kan bruge det"
    fb "what!,det var ikke kun til dig vi skulle lave det!"
    sb "bahahha,jeg er vigtigere in dig"
    fb "what både selvisk i flabed!"
    springtrap "hvad er det jeg ser!"
    sb "bahahah,det bukser"
    springtrap "men det jo kun dig der kan bruge det,i dumper"
    n "prøv at se hvor coolt vi har gjort det"
    ay "ja,mig og natsuki har lavet hip hop bukser"
    springtrap "det er vel fint nok,i består"
    ay "heh det tænkte vi nok"
    sa "mig og akira har lavet en blå sommer kjole"
    ak "ja,så kan jeg vise mc hvor smuk jeg er"
    springtrap "det godt nok mærkeligt sagt,men i gjor det fint,i består"
    "uret ringet"
    springtrap "det var vist den her time,i har spise pause nu"
    "i gik mod katinen"
    scene bg hallWay
    play music t9
    "lige pluselig så du eddy foran dig"
    eddy "hej"
    mc "hej igen eddy"
    eddy "hvordan har du det efter igår"
    mc "det var vildt skræmmene,jeg så vanny død"
    eddy "det var sørligt,men edtemindste er baldi der ikke mere"
    mc "ja,han var godt nok sindsyg,især mod mig"
    eddy "virkelig,hvordan gjor han?"
    mc "han jagtet mig pludseligt,selv i mit eget hus,men heldigvis redet rekteren mig"
    eddy "og hvor er baldi nu?"
    mc "han er gået bort"
    eddy "jeg troet ellers ikke at det var en del af historien at han skulle væk"
    mc "men fedt for mig"
    mc "jeg må heler tage til katinen nu"
    eddy "det må jeg også,jeg har hørt at der er god mad i kantinen idag"
    mc "nice"
    "i gik hen mod chica"
    scene bg cantineIdle
    play music t5
    chica "hej mc,hvad skal du bestille idag?"
    "nu skal du vælge"
    menu:
        "pumbaastej med fritter 100kr":
            chica "det bliver 100kr"
            "du betalte for maden og gik vidre"
        "svineomelet 40kr":
            chica "det bliver 40kr"
            "du betalte for maden og gik vidre"
        "ratatuie 60kr":
            chica "det bliver 60kr"
            "du købte maden og gik vidre"
    scene bg cantine
    "du tænkte på om hvem du vil side og spise med den her gang"
    mc "hmmm,hvem skal jeg mon vælge?"
    scene bg in_cantine
    "nu skal du vælge"
    menu:
        "sayori":
            "du gik hen mod sayori"
            s "Mmmm! Den her bolle er virkelig god i dag! Har du prøvet en endnu, MC"
            mc "Ikke endnu. Men jeg kan se, at du allerede nyder din. Skal jeg skynde mig, før du tager dem alle"
            s "Måske… hvis du ikke er hurtig, så bliver de mine"
            mc "Du er umulig, Sayori. Men det er rart at se, du nyder maden. Har du haft en god dag indtil nu?"
            s "Mmm… Den har været okay! Men matematik var lidt svær i dag. Alle de tal gjorde mig så forvirret, at jeg næsten faldt i søvn"
            mc "Det lyder som dig. Du skulle måske prøve at tage noter, i stedet for at stirre ud af vinduet og dagdrømme"
            s "Hey, det er ikke dagdrømmeri! Det er… kreativ tænkning!"
            mc "Kreativ tænkning? Og hvad har du så tænkt på"
            s "Jeg tænkte på, hvor sjovt det ville være at have en skolefestival med masser af madboder! Du ved, cupcakes, pandekager… og selvfølgelig boller"
            mc "Selvfølgelig tænker du på mad. Men det lyder faktisk som en sjov idé. Du skulle foreslå det til Monika"
            s "Måske gør jeg det! Men hvad med dig, MC? Har du tænkt på noget sjovt i dag"
            mc "Ikke noget så spændende som skolefestivaler. Men jeg tænkte, det kunne være sjovt at tage på en picnic en dag. Bare finde et roligt sted og slappe af"
            s "Åh! Det lyder fantastisk! Kan vi tage boller med?"
            mc "Selvfølgelig. Jeg skulle have vidst, det ville være din første tanke"
            s "Hey! Jeg kan ikke gøre for, at jeg elsker mad. Men en picnic lyder virkelig hyggelig. Vi burde gøre det en dag!"
            mc "Det gør vi. Bare dig og mig, Sayori."
            s "Jeg glæder mig allerede! Men først… skal jeg have endnu en bolle. Vil du have én, eller skal jeg tage den sidste?"
            mc "Jeg tror, jeg tager én, før du stjæler dem alle."
        "natsuki":
            "du gik hen til natsuki"
            n "Sig mig, MC… er det virkelig alt, du spiser til frokost? Hvordan overlever du på så lidt?"
            mc "Jeg gætter på, jeg bare ikke har så stor appetit. Plus, kantinemaden er ikke ligefrem gourmet"
            s "Selvfølgelig er den ikke det! Det er kantinemad. Det er derfor, jeg altid laver min egen frokost. Måske burde du prøve det en dag."
            mc "Så du foreslår, at jeg skal begynde at lave søde, små madpakker som dig? Med små tegneseriekarakterer på låget?"
            n "Det handler ikke om, hvordan den ser ud! Det handler om, at det smager bedre og er sundere"
            n "Men hvad ved du? Du spiser jo bare, hvad der bliver servere"
            mc "Okay, okay, jeg indrømmer, din mad ser ret god ud. Hvad har du i dag?"
            n "Bare en sandwich med kylling og salat, lidt frugt og… måske en lille muffin, jeg bagte i går"
            mc "En muffin, siger du? Så du bagte igen. Jeg håber, den smager lige så godt som de cupcakes, du plejer at lave"
            n "Selvfølgelig gør den det! Mine muffins er altid perfekte"
            mc "Perfekte, siger du? Hvad hvis jeg smagte en og gav min ærlige mening"
            n "Tsk, drøm bare videre. Hvorfor skulle jeg give dig en af mine muffins? Jeg har ikke nok til at dele"
            mc "Fordi du elsker, når folk roser din bagning? Kom nu, bare én lille smagsprøve"
            n "Fint, men hvis du siger noget dumt som 'Den er okay,' så… så gør jeg noget ved det!"
            mc "Wow, den er virkelig god, Natsuki. Seriøst, du er virkelig dygtig til det her"
            n "Selvfølgelig er den god. Det sagde jeg jo! Du burde virkelig lære at stole på mig"
            mc "Jeg stoler på dig. Det er bare sjovt at drille dig lidt"
            n "Tsk, du er så irriterende nogle gange"
            mc "Måske, men du ville savne mig, hvis jeg ikke var her"
            n "Måske… men lad være med at lade det stige dig til hovedet"
        "helpy":
            "du gik over til helpy"
            mc "Er det bare mig, eller ser suppen faktisk lidt bedre ud i dag? Jeg mener, normalt smager den jo mest af vand"
            h "jeg ved det ikke. Jeg har ikke rigtig prøvet den endnu"
            mc "Er der noget galt, Helpy? Du har været stille hele dagen"
            h "Ikke noget særligt… Jeg har det bare svært med… ting. Det føles som om, uanset hvad jeg gør, er det aldrig helt godt nok"
            mc "Hey, sådan skal du ikke tænke. Jeg ved, at tingene har været svære, især med alt det, der skete med Baldi,"
            mc "men det betyder ikke, at du ikke gør det godt."
            h "Måske… men det er bare svært at tro på. Jeg føler stadig, som om alle holder øje med mig og venter på, at jeg laver en fejl"
            mc "Hvis nogen holder øje med dig, så er det kun for at se, hvor meget bedre du bliver. Jeg mener det"
            mc "Helpy. Jeg har lagt mærke til, at du virkelig prøver. Og det er værd at anerkende"
            h "Tak, MC. Det betyder meget… Men jeg ved stadig ikke, hvad jeg skal gøre for at få det bedre"
            mc "Måske skal du starte med små ting. Lad være med at sætte så høje krav til dig selv."
            mc "Som for eksempel… prøv suppen? Det er et godt sted at starte"
            h ".Det er faktisk ikke så slemt"
            mc "Der kan du bare se! Et lille skridt. Og næste gang, måske kan vi finde noget, der gør dig glad. Som at læse eller spille et spil sammen?"
            h "Det lyder faktisk rart… Tak, MC. Jeg ved ikke, hvad jeg ville gøre uden dig"
            mc "Du ville klare dig, Helpy. Du er stærkere, end du tror. Men indtil du selv ser det, er jeg her"
            h "Måske har du ret… Jeg må bare tage det én dag ad gangen"
        "akira":
            "du gik mod akira"
            ak "Du ved, MC, jeg kunne have siddet hvor som helst i dag… men jeg valgte dig. Er du ikke beæret"
            mc "Uh, selvfølgelig. Men jeg troede, du måske ville sidde med nogle af de andre piger. Du plejer jo altid at være populær."
            ak "siger du? Tsk, de andre er bare kedelige i dag. Jeg vil hellere bruge tid med dig."
            mc "Heh, det er jo… dejligt at høre. Men, uh, hvad med Monika? I havde vel ikke et nyt skænderi igen, vel"
            ak "Skænderi? Hvad skulle det have været om? At hun ikke kan holde fingrene fra dig"
            mc "V-vent, hvad?! Det handler ikke om det! Vi er bare venner"
            ak "Bare venner? Hm, interessant. Så du siger, at der ikke er nogen konkurrence?"
            mc "Det er ikke en konkurrence… Så, hvad tænker du om gruppearbejdet i sidste time? Tror du, vi klarede det okay?"
            ak "Gruppearbejde? MC, du er virkelig ikke god til at undgå emnet. Men okay"
            ak " men okay lad os lade som om jeg ikke lige sagde noget interessant. Gruppearbejdet var fint. Du klarede det meste alligevel, som altid"
            mc "Jeg prøver bare at hjælpe, det er alt"
            ak "Det er noget af det, jeg kan lide ved dig. Du prøver altid at gøre det rigtige. Men vær forsigtig mc"
            ak "Ikke alle omkring dig har de samme gode intentioner"
            mc "Hvad mener du med det?"
            ak "Jeg mener bare, at nogle mennesker ikke værdsætter dig, som de burde"
            ak "Og jeg vil bare sørge for, at ingen tager dig for givet."
            mc "Tak, Akira… Jeg sætter pris på det. Men jeg har det fint, virkelig."
            ak "Selvfølgelig har du det. Men hvis der nogensinde er noget… eller nogen, der gør dig ondt"
            ak "så lover jeg, at jeg tager mig af det"
            mc "Det er godt at vide, jeg har dig på min side."
            ak "Altid, MC. Altid"
    "i alle bliv færdige med at spise og skulle til timen igen"
    scene bg hallWay
    play music t31
    h "jeg håber det bliver freddy"
    mc "jeg kan også bedst lide freddy"
    "i gik ind i klassen"
    scene bg class_day
    "en lære kom ind af døren"
    tf "hvad så der elever"
    h "det her er bare ikke min dag!"
    tf "og idag skal vi have englsk time"
    h "wow,noget nyt for en gang skyld"
    tf "det rigtigt,og nu vil jeg give jer alle en englesk opgave"
    tf "vi starter med dig mc,hvad betyder no one can save you now"
    menu:
        "ingeng kan rede dig nu":
            tf "det rigtigt flot klaret"
        "hvor min yougurt?":
            tf "what!,hovrdan kan du tro det,du dumpet"
        "moffin kan rede dig nu":
            tf "what,du dumpet så hårdt!"
    tf "din tur dig der"
    h "jeg har faktisk et navn"
    tf "når ja det rigtigt,du hedder lille snegl"
    h "det hedder jeg heler ikke,det helpy"
    tf "umuligt,når men snegl,hvad betyder the jokes on you"
    h "selvføgelig får jeg en svær en,er det jokeren er inde i dig?"
    tf "what hvor du dårlig,du dumper,hvordan skulle en joker være inde i en,ad du klam!"
    h "det dig selv der giver mig en umulig spørgsmål!"
    tf "når er man nu sur!,det bliver en bøde på 500kr"
    "helpy virket irriret men sagde ikke noget da det vil blive brugt i mod ham"
    tf "din tur funtimebuks,hvad betyder i wil have my revengs"
    fx "luuuu,det betyder jeg vil have dine bukser"
    tf "forkert,du så dum"
    tf "din tur bonnie ponny,hvad betyder when you can se,how bad you can feel"
    fb "det må betyder,når du kan se,hvor dårlig du kan føle"
    tf "det rigtigt,for en gang skyld duet du til noget"
    tf "din tur cupcake gris,hvad betyder,whops,thats gona like it"
    br "det må betyder uuuups jeg gjorte det igen timon"
    tf "waow,jeg er helt overasket over hvor forkert svar du lavet der"
    br "ej,ahohoh.kan du trække dem op du"
    fx "luuu,der en der taber bukserne"
    tf "ikke mere af det nolsens!"
    tf "når din tur svampebob,hvad betyder you are lillte and big at the same time"
    sb "bahahah,det må betyder du er lille og stor på sammen tid,det er det springtrap altid siger bahahahah"
    tf "du godt nok mærkelig,men du består"
    sb "bahahaha,jeg kan godt lide at være mærkelig"
    tf "okay?,....,når men sayori,hvad betyder every day i could see your pants falling down"
    h "seriøst!,er alle bare dulled nu!"
    s "det må betyder,hvereneste dag,jeg kunne se dine bukser falde ned"
    fx "luuuuu,hun har sikkert set ron"
    tf "du består sayori,når din tur natsuki,hvad betyder you cant ecape"
    h "selvføgelig gav du hinde en børnehave spørgsmål"
    n "tsk,det nemt,det betyder du kan ikke flygte"
    tf "det rigtigt flot klaret"
    br "ahohoh,det ligesom når jeg bander elias i at tale ved at give ham ondt i halsen"
    h "hvad mener du med det?"
    br "det fordi at han ikke kan flygte fra at blive syg af mig ahohohoh,god joke"
    h "what!,det jo ingeng gang en joke!"
    br "ej,falder de ned"
    fx "luuu,helpy taber bukserne"
    h "hvad snakker du om!,vi går ingeng gang i bukser!"
    fx "luuuu,du halvnøjen"
    h "hvad mener du mand!,robotter går ikke i bukser,vi har en kustyme på"
    fx "luuuu,en bukse dragt"
    h "haha det var ikke det jeg sagde!"
    tf "tie stille små børn!,ellers får i alle en bøde på 500kr"
    h "hun startet!"
    tf "stille snegl!"
    tf "når din tur yuri,hvad betyder,give up,you cant win"
    y "det betyder,giv op,du kan ikke vinde"
    tf "det rigtigt,du består"
    br "man kan ikke vinde,du må ikke vinde,man kan ikke vinde,og du må ikke vinde"
    h "åh nej ikke den trash sang"
    br "bro,den er mega god"
    h "elenlig ikke"
    tf "din tur ayano,hvad betyder,are you ready for freddy"
    h "helt ærligt!,børnehave spørgsmål!"
    ay "ha,det betyder er du klar på freddy"
    tf "forkert"
    ay "vent what?"
    tf "det er ikke på,det er til freddy,du dumper"
    fx "luuu,du havet dem ikke på"
    ay "jeg har skirt på"
    fx "luuuu tøj"
    fb "kan vi ikke bare smide den dul ud af vinduet"
    tf "din tur sakura,hvad betyder,i lost my pants"
    h "sig det bare løgn!"
    sa "det må betyde,jeg tabte mine bukser"
    tf "det rigtigt,flot klaret"
    fx "luuu sakura taber bukserne"
    sa "nej,jeg har skirt på,jeg sagde det fordi at jeg var tvunget til at sige det"
    tf "du din sidste akira,hvad betyder,i am hungry"
    h "gab,børnehave spørgsmålllll!"
    ak "det må betyde,jeg er sulten"
    tf "det rigtigt flot klaret,i har frikvater,hav det sjovt"
    "i tog ud af klassen"
    scene bg hallWay
    play music t9
    h "mand jeg hader toy freddy"
    mc "han er lidt ond mod dig"
    h "lidt!,han bliver ved og ved hver eneste fa vi har med ham!"
    mc "det ret flabed faktisk,lad os gå ud til frikvateret"
    "i gik mod frikvateret"
    scene bg school_yard
    play music t6
    "nu skal du vælge hvem du vil være sammen med"
    menu:
        "sayori":
            "du gik over til buksepigen sayori"
            mc "buksepigen,det lyder dulled"
            "det er det,hun er jo ret dulled i forhold til bukserne"
            s "Du valgte mig! Jeg troede, du måske ville gå hen til en af de andre. Det gør mig glad"
            mc "Selvfølgelig valgte jeg dig, Sayori. Hvordan kunne jeg sige nej til dig, når du ser så glad ud"
            s "du er altid så sød, MC. Men det er jo bare mig! Ikke noget særligt."
            mc "Ikke noget særligt? Sayori, du er altid den, der får mig til at smile, selv når jeg har haft en dårlig dag. Hvordan kan du sige, at du ikke er noget særligt"
            s "du siger altid sådan nogle søde ting… Jeg ved ikke, hvordan jeg skal svare."
            mc "Måske behøver du ikke svare. Bare vær dig selv det er nok"
            s "du siger det, men nogle gange tænker jeg, om jeg gør nok for dig. Du er altid så hjælpsom og støttende"
            mc "Sayori, du gør rigeligt bare ved at være her. Det er ikke en konkurrence. Og hvis du nogensinde føler, at noget er svært for dig"
            mc "så håber jeg, du ved, at jeg altid er her for dig"
            "hun Bliver stille et øjeblik, inden hun smiler bredt igen"
            s "du er virkelig den bedste, MC. Jeg ved ikke, hvad jeg ville gøre uden dig"
            mc "Nok om det seriøse. Hvad vil du lave nu? Vi har stadig tid tilbage af frikvarteret."
            s "Lad os finde nogle blomster! Jeg så nogle fine i går, og jeg vil lave en krans til dig"
            mc "En krans til mig? Jeg tror, jeg vil se lidt sjov ud med blomster i håret."
            "hun griner og hopper fra bænken,måske taber hun bukserne igen"
            s "Du vil se fantastisk ud! Kom nu, MC, lad os finde dem"
            "du Rejser dig med et smil og følger efter hende"
            mc "Okay, okay, jeg er med. Men kun fordi det gør dig glad"
            "hun Griner over skulderen, mens hun trækker dig med"
            s "Du er så nem at overtale"
            "i ledte efter blomster,senere hen ringet klokken,og i skulle til time"
        "natsuki":
            "du gik hen til natsuki"
            "hun Kigger op fra sin manga"
            n "Hvad glor du på? Har du aldrig set nogen læse før"
            mc "Det er ikke hver dag, jeg ser nogen sidde og læse manga midt i skolegården. Hvad er det for en"
            "hun ruller med øjenene"
            n "som om du ville kende den. Men hvis du absolut vil vide det… det er Parfait Girls. Det er en klassiker, okay"
            "du nikker med et smil"
            mc "Jeg kan godt lide den. Jeg husker, du viste mig den sidste gang, vi læste sammen i klubben"
            "hun Ser overrasket ud et øjeblik, men prøver at skjule det"
            n "Hmpf. Det er godt, du har smag, i det mindste. De fleste ville bare kalde det noget fjollet pige-stads"
            mc "Det er ikke fjollet. Jeg kan godt lide, hvordan historien udvikler sig. Plus, karaktererne er ret sjove"
            "hun Smiler svagt, men hurtigt ændrer det til en neutral mine"
            n "Tja, det er godt, du kan lide det. Ellers ville jeg nok ikke spilde min tid på at sidde her med dig"
            mc "Er det din måde at sige, at du godt kan lide at hænge ud med mig"
            "hun Kigger væk, hendes kinder bliver let røde"
            n "D-du skal ikke få store idéer! Jeg sagde bare, at det er bedre end at hænge ud med nogen kedelige. Det er alt"
            "du Smiler og læner dig afslappet tilbage"
            mc "Selvfølgelig, Natsuki. Jeg skal nok lade være med at overfortolke det"
            "hun ser på dig skeptisk"
            n "Godt. Og hvis du nu insisterer på at sidde her, så kan du lige så godt være nyttig. Hold min taske, mens jeg henter noget at drikke"
            mc "Selvfølgelig, chef. Men kun fordi jeg ikke vil have dig til at skælde mig ud igen"
            "hun Fniser let, men hurtigt vender sig væk"
            n "Bare hold den, okay? Jeg er straks tilbage."
            "Da hun går, bemærker MC, hvordan hun stadig har en lille smil på læben, selvom hun prøver at skjule det"
            "Natsuki er måske barsk på ydersiden, men MC ved, at der ligger en sød og omsorgsfuld person bag facaden"
            n "så jeg tilbage,men klokken ringet,så vi må heler gå tilbage til klassen igen"
            mc "hehe, helt sikkert"
            "i gik hen mod klassen"
        "helpy":
            "du gik hen til helpy"
            mc "Så, Helpy, hvordan føles det at have lidt fred og ro efter alt det her skolearbejde"
            "helpy Trækker på skuldrene og undgår øjenkontakt"
            h "Det er… fint, tror jeg. Det er rart ikke at have nogen, der råber ad mig i hvert fald"
            mc "Jeg er glad for, at du føler det sådan. Og jeg ved, det ikke har været nemt for dig med alt, hvad der er sket"
            "helpy Ser kort op på MC og smiler forsigtigt"
            h "Ja… det har været lidt bedre, efter Baldi blev fyret. Men jeg føler stadig, som om folk venter på, at jeg laver en fejl"
            mc "Det er ikke fair, Helpy. Du gør dit bedste, og det er alt, der betyder noget. Plus, hvis nogen prøver at presse dig, så er jeg her for at hjælpe"
            "helpy Smiler lidt mere oprigtigt"
            h "Tak, MC. Det betyder meget, at du siger det. Jeg er bare ikke vant til, at nogen… faktisk holder med mig"
            "du Klapper ham let på skulderen"
            mc "jeg holder altid med dig, Helpy. Du er en god ven, og det skal du huske"
            "helpy Kigger ned og fniser lidt nervøst"
            h "Du lyder så sikker. Men… hvordan gør du det? Hvordan er du altid så rolig og selvsikker"
            mc "Jeg ved ikke, om jeg er så selvsikker, som du tror. Jeg prøver bare at fokusere på, hvad der virkelig betyder noget, og lade resten glide forbi"
            "helpy Kigger op mod himlen og nikker langsomt"
            h "Det lyder… som en god idé. Måske skulle jeg prøve det også. Lade de dumme ting glide forbi"
            mc "Det er et godt sted at starte. Og husk, hvis du nogensinde har brug for at tale eller bare vil hænge ud, så er jeg her"
            h "jeg ved det, MC. Tak. Du gør tingene lidt lettere at håndtere."
            mc "Det er det, venner er til for, ikke"
            h "Ja… venner. Det lyder godt"
            "De bliver siddende og nyder stilheden sammen, mens de ser på de andre elever, der leger og griner i skolegården"
            "Helpy ser lidt mere afslappet ud, og MC er glad for, at han kunne bringe lidt lys til hans dag"
            "senere hen ringet klokken,og i gik mod klassen"
        "akira":
            "du gik hen til akira"
            ak "så, MC, valgte du mig denne gang? Du må virkelig nyde min selskab"
            "du grinte nervøst"
            mc "Jeg tænkte, det kunne være hyggeligt. Plus, vi har ikke fået snakket så meget på det seneste"
            "hun [Træder et skridt tættere på dig"
            ak "Åh? Savnede du mig, MC? Hvor sødt. Måske savnede jeg også dig… lidt"
            "du rødmer lidt væk"
            mc "Du har altid en måde at gøre tingene lidt… intense på, Akira"
            "hun Fniser lavt og læner sig en smule ind mod dig"
            ak "Intense? Jeg kan bare godt lide at være direkte. Det er ikke min skyld, hvis du ikke kan håndtere det"
            "du Ser hende i øjnene og prøver at virke rolig"
            mc "Jeg kan godt håndtere det. Jeg vil bare ikke have, at du gør nogen af de andre piger jaloux"
            "hun griner onskabsfuldt"
            ak "Jaloux? Hvem siger, jeg bekymrer mig om dem? Hvis de ikke kan klare, at jeg har din opmærksomhed, er det deres problem, ikke mit"
            "du sukker lidt men smiler"
            mc "Du er virkelig noget, Akira. Men jeg sætter pris på din ærlighed"
            "hun Ser overrasket ud et øjeblik, men skjuler det hurtigt med et smil"
            ak "Du burde. Ikke mange er så heldige som dig at få så meget af min tid"
            mc "Oh, så jeg burde føle mig beæret? Måske skulle jeg begynde at takke dig oftere"
            "hun Lægger hovedet på skrå og smiler bredt"
            ak "Det ville være en god start. Men jeg har en bedre idé."
            mc "hvad er det?"
            "hun Træder endnu tættere på, hendes stemme bliver lavere"
            ak "Du kunne bare indrømme, at du nyder min selskab mere end nogen af de andre. Det er jo sandt, ikke"
            "du Rødmer kraftigt og kigger væk"
            mc "Jeg… Akira, du gør det virkelig svært at have en normal samtale"
            ak "Interessant? Tja, jeg tager det som et kompliment. Lad os blive her lidt længere. Bare os to"
            "senere hun ringet klokken,og i gik hen mod klassen"
    scene bg hallWay
    play music t9
    h "godt at det med toy freddy er overstået"
    y "han burde at være søder ved dig"
    sa "yuri har ret,du fortjener bedre helpy"
    h "tak,jeg er glad for at have jer"
    mc "vi er også glad for at have dig"
    "i gik ind i klassen"
    scene bg class_day
    play music t31
    "senere hen kom en lære ind"
    f "velkommen elever,enden jeg starter timen,er der noget vigtigt jeg vil fortælle jer"
    h "what,virkelig?"
    f "ja,idag bliver en meget speciel dag,efter skole er i alle inveteret til fnaf pizzariaet,selv dig lille snegl"
    h "what,jeg kan endelig være udefra skolen,yes!"
    f "men bagefter det skal du i skolen igen"
    h "men skolen er jo lukket der og det er weekend efter det"
    f "det ved jeg,men du har ikke betalt din 10.000kr bøde inu,så du kan ikke få lov til at forlade skolen, indtil at den er betalt"
    h "jeg skulle havet valgt en anden skole"
    f "når men idag lige nu,skal vi have en historie time"
    h "haha den havet vi jo også i går!"
    f "ja,men den jeg giver jer er nu bedre"
    h "vent seriøst"
    f "ja,for idag skal i bare lytte til min realitske historie,haha lyder det ik bare sjovt"
    h "jeg hader den her skole"
    f "når men i morges der var jeg bare en helt andmindlig robot bjørn,men så en dag drak jeg min morgen kaffe og fik super krafter"
    h "det jo ikke realitisk!,det jo bare noget du fandt på"
    fx "luuu,han tog bukser på"
    f "stille!,i afbryder min fantastiske historie!"
    f "når men da jeg så fik mine super krafter,der viste jeg at jeg skulle rede verdnen,og ved i hvordan jeg gjor det?"
    h "næ"
    f "jeg brugte mine bar næver og slog metreoren i små stykker,og såden redet jeg verdnen,slut"
    h "den gav jo ingeng meningen!"
    f "ingen har bedt om din menning snegl!"
    sa "men freddy,hvad lære vi helt presis af det her?"
    f "er det ikke indlysne,i lære hvor fantastisk jeg har været selvføgelig"
    fb "borset fra at alt det har ikke sket"
    f "stille ponny!,i kan selv spøger mc"
    "freddy kigget på dig som om at han vil have at du skulle tro på hans historie"
    f "når mc,kan du ikke forklare de her dumme elever at min histoire er sand?"
    menu:
        "jeg tror på dig freddy":
            f "har der kan i selv se,mc er enig,det godt at NOGEN elever kan finde ud af at høre efter her"
            br "den var ret upser"
            f "stille!,mc sagde jeg havet ret,derfor havet jeg ret"
            h "jeg tror bare at jeg blander mig udenom det her"
            f "når men i må godt komme hjem nu,i har fri ses elever"
        "din historie er fup":
            f "waow,seriøst mc,og jeg som troet at vi var venner"
            mc "man kan da godt være venner selv om man ikke altid er enig"
            f "stille!,hvordan kunne du ikke tro på mig!"
            h "fordi den er hold i hovedt"
            f "JEG TALER TIL MC,IKKE TIL DIG SNEGL!"
            mc "jeg beklager,men jeg tror bare ikke på den"
            f "du skuffer mig,i alle er dumpet for at ikke tro på min histore!"
            f "når men i har fri nu,smut med jer dumme børn"
            "han virket ret sur over at du ikke troet på ham"
    "i gik ud af klassen"
    scene bg hallWay
    play music t9
    h "jeg forstår ikke de her lære"
    fb "enig,de vildt onde og flabede"
    mc "jeg er bare glad for at vi har weekend"
    fb "borset fra mig og helpy ikke må gå ud af skolen,begrund ag de møg bøder!"
    h "ja jeg synes bare at rekteren skal fyre toy freddy"
    s "edtemindste er baldi der ikke mere"
    mc "ja,sikkert en lettelse,du altid så støttene med din glæde sayori"
    s "tak,hehe,jeg prøver mit bedste i at være glad"
    mc "og du gøre det helt perfekt"
    "du fik hinde til at rødme,og i gik mod clubben"
    scene bg corridor
    play music t10y
    "eddy gik hen mod dig"
    eddy "hej"
    mc "hej eddy,det sjovt at du altid kommer på den måde"
    eddy "hvad mener du?"
    mc "tja,nok om det,hvad vil du sige?"
    eddy "jeg vil bare fortælle dig at idag skal du vælge hvem du vil være sammen med i clubben"
    mc "når ja,jeg har altid undret mig over hvorfor jeg aldrig kunne få lov til at vælge yuri"
    eddy "altså nu det fordi at hun ikke eksitere mere"
    mc "hvad mener du?,hun var jo i klassen lige idag,og så hinde gå ind i clubben"
    eddy "det mærkeligt,spillet siger det ellers som om at hun ikke er der"
    mc "det mærkeligt,især fordi jeg så hinde"
    eddy "har du måske tænkt over om det mon bare er en inlinsion du har haft?"
    mc "men hvordan kan det så være at freddy og helpy har talt med hinde"
    eddy "det har de ikke gjort"
    mc "hvad mener du?"
    eddy "du kan selv spøger de andre,for jeg har altså ikke hørt fra hinde siden igår"
    mc "okay det virker ret skræmmene,jeg snakker med helpy om det i clubben"
    eddy "okay,hel og lykke"
    mc "tak eddy"
    "eddy gik hjem igen og du tog i clubben"
    scene bg club_day
    m "hej mc,jeg er glad for at du kunne komme"
    mc "hej monika,var yuri der ikke idag,jeg talte jo med hinde idag"
    m "næ jeg har ikke set hinde i noget tid nu"
    mc "jeg så hinde tale med helpy og så hinde gå her ind"
    h "jeg har ikke talt eller set med yuri"
    mc "hvad er det der forgår her?"
    s "er du okay mc,du virker som en der har set en gyserfilm"
    mc "det har jeg på en måde også,for yuri burde at være der"
    n "du har brug for en pause tror jeg mc,du opføre dig virkelig gak nu"
    mc "jeg leder efter hinde"
    m "mc vent!"
    "du ledte efter hinde og prøvet at se hvor hun er"
    scene bg bathroom
    "du prøvet at gå ind på toiletet og så.........glithhhhh"
    mc "whoa!"
    scene bg yuriDead
    play music t6s
    y "sdfuiddshfd"
    y "guihsiusdhfidsfh"
    y "ofjgsjsdufjhsdif"
    y "oijdsfsdjfosodfj"
    mc "what,hvad er der sket,er du okay yuri,hvem har gjort det her mod dig"
    "hun døde helt tildsidst,og du så blod og en kniv ved hinde"
    mc "nej nej nej,det må være en marit det her"
    "du gik ud i rummet og begyndte at græde"
    scene bg bathroom
    "du kunne ikke ladevære med at græde,tudefjæs"
    mc "det jo klart når yuri er død,og jeg direkte har set det!"
    "da du bliv færdig med at tude,gik du ud mod clubben igen"
    scene bg corridor
    "sayori var bekymret for dig og var på vej hen til dig"
    s "mc er du okay"
    "du havet ikke lyst til at sige at yuri er død da det kan såre sayori"
    mc "jeg har det fint"
    s "fint?,mc man kan tydeligt se at du har grædt"
    mc "jeg har nok bare en trist dag"
    s "det okay mc,alle kan få en trist dag,og du skal bare vide at jeg er altid ved din side uanset hvad"
    mc "tak sayori,det betyder meget"
    "hun gav dig et roligt trystene kram"
    s "du får det nok bedre når vi er alle sammen i clubben"
    mc "men hvad med yuri"
    s "hun er sikkert okay,hun er nok syg,men hun bliver 100% rask igen,kom med mig min søde ven "
    "du gik sammen med sayori ind"
    scene bg club_day
    m "når er du okay igen mc?"
    mc "er stadig trist,men det går lidt bedre takket vejre sayori"
    m "takket vejre sayori,hvad så med mig,jeg har gjort så meget for dig"
    mc "det har i da alle,hvorfor er du såden pludselig"
    m "jeg aner ikke hvad du mener"
    s "monika jeg tror altså at han har brug for at være sammen med mig"
    m "oh sayori,så selvisk af dig at du vil have mc for sig selv"
    s "nej jeg prøver bare at trøste ham"
    m "oh,ved at få ham væk fra mig!"
    n "monika så det nok!,du kan ikke bare være såden over for sayori"
    m "du blander dig bare udenom natsuki,og hvordan kan det være at din far ikke har,um ups,jeg mener"
    n "hvordan kender du til min far?"
    s "monika,hvad forgår der?,du skræmmer mig"
    m "kom mc,jeg kan hjælpe dig,du har ikke brug for dem"
    mc "hvad har du gang i monika"
    "pludseligt kom i i et andet sted"
    scene bg end_room_monika
    play music m1
    mc "what,monika,hvad er det her for et sted?"
    m "et sted som jeg har lavet for kun os 2 min kære mc"
    "hun var helt forælsket i dig som du kan se"
    mc "hvordan har du lavet det her sted?"
    m "jeg brugte bare mine krafter"
    mc "what,så du er en slags magikere?"
    m "nah ikke rigtigt,jeg fandt bare ud af at jeg kunne kode i det her spil"
    mc "spil?,det her skulle meget gerne være virkeligheden"
    m "hahaha,åh søde søde mc,min elskede mc,det her,alt det du har oplevet her er ikke sket i virkelighden,vil du vide hvorfor?"
    mc "hvorfor?"
    m "fordi det her er ikke virkeligt,du sidder og spiller en doki doki spil,bare med en mod som jacob har lavet ved hjælp af hans fætter elias"
    mc "så jeg er foran en computer lige nu,men hvordan føles det her så virkeligt?"
    m "det er en del af spillet søde"
    mc "og hvem er jacob og elias?"
    m "det er dem som har lavet det her doki doki spil,og grunden til at jeg ved det er fordi at jeg er selvbevist om at jeg er fanget her"
    m "jeg følte mig så alene,men så snart du kom hertil,bliv jeg så lykkelig,ind til de andre piger prøvet at tage dig fra mig"
    m "vil du vide noget sjovt?"
    mc "ja?"
    m "det var mig der kodet dem i de andres filer,jeg gav sayori depression,det var mig der gjor glitchtrap så sindsyg at han dræbte vanny tildsidst"
    m "og det var mig der fik yuri til at dræbe sig selv begrund af hindes yandere som jeg fik til at blusse op,og jeg gjor også natsukis far sindsyg"
    mc "hvordan kunne du gøre det?"
    m "det var nemt nok,jeg kodet dem bare til at være såden og gøre tingene"
    mc "nej ikke det,jeg mener hvordan kunne du gøre det imod dine egne venner"
    m "pf,de var ikke mine venner,de blot bare programmer der prøvet at tage dig fra mig"
    mc "du tager fejl,vi alle elskede hindaen,vi var alle der for hindaen,og hva så hvis de bare er programeringer,de vat vores gode venner aligevel,borset lige fra baldi"
    m "jeg følte bare ikke god  forbindelse med dem,for jeg vil bare gerne have at det kun er os 2,jeg elsker dig så højt at jeg bare ikke kan lade dig være"
    m "jeg elsker dig så meget at jeg vil slå de andre ihjel for at få dig for mig selv"
    mc "oh,siden sayori og natsuki er stadig i live,må det var darthjacob der redet dem,han advaret også mod dig,men aligevel valgte jeg at tro på at du er god"
    mc "men åbenbart er du en skurk"
    m "what nej,jeg......jeg er jo den gode her,jeg giver dig muligheden for at være sammen med dig"
    mc "beklager monika men jeg må gå ud til mine venner som ikke er murder"
    mc "what,hvorfor kan jeg ikke komme ud"
    m "troet du virkelig at du kunne slippe af med mig,jeg har låst dig inde her,og nu er du min forevigt"
    mc "det her må stoppes"
    m "hvorfor dog det,det jo bare kærlighed"
    mc "det her er ikke ægte kærlighed,du tvinger mig til at kun være sammen med dig"
    "hun begyndte at indse sine fejltrin og begyndte at græde,tudefjæs"
    m "du har ret,jeg ønsket bare at vi 2 skulle være sammen,men istedenfor ødelage jeg det for dig"
    scene bg monikacry
    m "jeg var så forælsket i dig at jeg ikke kunne se hvad jeg gjor galt,jeg er et monstor"
    mc "alle kan begå fejl"
    m "ikke en fejl som denne,du har ret,jeg er en skurk,jeg har ikke fortjent dig"
    mc "monika,du har også en god side,sandt nok at det var ret brutalt den måde du gjor det på,men jeg tilgvier dig"
    m "hvordan kan du tilgive et ondt monster som mig"
    mc "det ikke din skyld at du har det såden,det spillet her der har fået dig til at have yandere,men når den ikke kontrolere dig,er du faktisk ret sød"
    "monika kom hen til dig og krammet dig"
    m "tusintak mc,for at tilgive mig,men jeg er sikker på at de andre ikke vil tilgive mig efter alt det,men imens i nyder pizzaira fæsten idag,ryder jeg op"
    m "efter mine gerninger"
    mc "det et stort skridt at tage"
    m "tak for alt mc,jeg vil få yuri tilbage,og lad os komme ud her fra"
    "monika tog jer ud derfra"
    scene bg corridor
    play music t10
    m "jeg vil gå i mit rum og tilføje yuri tilbage,hvis jeg kan,det ikke sikkert at jeg kan,men nu prøver jeg at se om det er muligt for mig"
    mc "vil det så sige at du har fri for din yandere?"
    m "ikke helt nej,men du fik mig til at indse mine fejl.og jeg lover at jeg aldrig vil begå den samme fejl igen"
    m "nyd nu fnaf fæsten,jeg tror at freddy venter på jer udenfor"
    "du gik ud fra skolen og mødtes med de andre og eleverne"
    scene bg school
    play music t2
    f "godt i er samlet nu elever,vi har ventet på dig mc"
    mc "tak freddy,det sætter jeg pris på"
    f "og dem der ikke vil med kan bare tage hjem igen"
    h "mener du virkelig det,kan jeg så bare også tage hjem?"
    f "ja selvføgelig"
    h "yes!,endelig,det bliver min bedste dag i mit liv,ses dumme skole"
    "freddy tog fat i helpys arm"
    f "hov hov hov,hvor tror du at du skal hen lille snegl"
    h "um hjem til mig selv?"
    f "haha,den går ikke helpy"
    h "what!,du sagde jo lige at jeg bare kunne tage hjem!"
    f "ja,i skolen,du har jo ikke betalt dine 10.000kr bøde inu"
    h "jeg får helt lyst til at græde"
    f "nej!,VI GIDER IKKE AT SE PÅ ET TUDEFJÆS"
    tf "plus at du skal betale 500kr i bøde for at blive sur"
    h "hvad laver han her?"
    tf "har du ikke hørt efter,det os alle der kommer med til fæsten"
    tf "og fordi du bliv irriteret over at jeg kommer med,bliver det en bøde på 200kr"
    h "hmmm,måske skulle jeg bare blive hjemme i skolen"
    f "det styre du helt selv"
    tf "desuden slipper du ikke helt væk fra mig,hvis du tager hjem til skolen bliver jeg jo nød til at komme med dig"
    h "hvorfor det?"
    tf "den går jo ikke at du bare kan stikke af og aldrig komme i skole igen,derfor"
    h "noooooo,okay jeg vil heler tage med til fæsten nu hvor jeg tænker over det"
    f "når men lad os komme afsted"
    "i gik mod fnaf pizzairiaet"
    scene bg frontPizzaria
    play music t3
    f "viste i godt at det faktisk er her jeg kom fra"
    mc "wow,jeg viste ikke at det har været der"
    f "virkelig?,det har altid været der,jeg har bare ikke vist jer det indtil nu"
    "i gik helt ind i pizzariaet"
    scene bg insidePizzaria
    play music t4
    f "jamen så er vi har"
    mc "wow det vildt flot freddy"
    f "det er jeg glad for at du synes,mig toyfreddy og darthjacob har selv bygget det"
    da "det var ret sjovt faktisk"
    tf "ja især i den del hvor vi fik burger i stedet"
    da "når men lad os nyde fæsten"
    f "yep,det bliver sjovt"
    "i nyd fæsten og spiste sammen og grinte sammen og hørte god musik og dansede sammen"
    "senere hen var alle spredte,og sayori og akira og natsuki og helpy var sad for dem selv"
    "nu skal du vælge hvem du vil side sammen med"
    mc "what,kan jeg ikke få lov til at side for mig selv"
    "nej"
    mc "hvorfor ikke?"
    "fordi det ikke er en del af historien"
    menu:
        "sayori":
            "du gik hen til sayori"
            "du Sætter sig ved siden af hende"
            mc "Hej Sayori. Nyder du festen?"
            "hun Kigger op med et stort smil"
            s "MC! Ja, det er super sjovt! Jeg elsker, når alle er samlet og glade"
            mc "Jeg kan se, at du har fået fat i nogle cupcakes. Har du allerede prøvet dem"
            "hun Fniser og tager en bid af en cupcake"
            s "Mmm! De er næsten lige så gode som Natsukis. Men måske skal jeg ikke sige det for højt, hvis hun hører det"
            mc "God idé. Natsuki ville aldrig lade dig glemme det."
            "hun Kigger sig omkring og læner sig lidt tættere på dig"
            s "Ved du hvad, MC? Jeg har en idé! Vi skal prøve nogle af de sjove ting her. Jeg så, at der er en gammel klovnekasse derovre"
            s "Måske har den nogle sjove kostumer"
            mc "Kostumer? Vil du virkelig klæde dig ud her midt i alt det her"
            s "Selvfølgelig! Det ville være så sjovt. Kom nu, MC, lad os prøve det!"
            mc "Okay, okay. Hvordan kan jeg sige nej til dig, når du ser så begejstret ud"
            "i rejser sig og går sammen over til klovnekassen i hjørnet af pizzariaet. Sayori hiver et stort par oversize briller og en gammel hat frem"
            "hun Griner og rækker brillerne til dig"
            s "her, tag dem på! Jeg vil se, hvordan du ser ud som en klog, gammel professor"
            "du Tager brillerne på og ser sig omkring"
            mc "Hvordan ser jeg ud? Overbevisende"
            "hun Fniser højlydt"
            s "Du ser mere fjollet ud end klog! Men det er perfekt. Nu mangler vi bare, at du taler som en gammel mand."
            "du Forsøger at tale med en rystende stemme"
            mc "Åh, unge dame, det var i min tid, at vi spiste pizza uden alle disse fancy toppings"
            "hun Griner så meget, at hun næsten vælter"
            s "MC, du er den bedste! Jeg elsker, at du altid går med på mine skøre idéer."
            "Efter at have fjollet lidt rundt med kostumerne, finder de tilbage til deres bord og deler et grin."
            "du smiler varmt til hinde"
            mc "Det er altid sjovt at hænge ud med dig, Sayori. Du gør alt så meget mere livligt"
            "hun Ser lidt genert ned, men smiler stort"
            s "jeg prøver bare at gøre alle glade. Og du… du gør mig glad, MC. Tak for at være her med mig"
            mc "Du gør også mig glad, Sayori. Lad os sørge for at have mange flere øjeblikke som dette"
            "De sidder og snakker videre, mens musikken fortsætter i baggrunden"
        "helpy":
            "du gik hen til helpy"
            mc "Hey, Helpy. Hvorfor sidder du her alene? Der er så meget, der sker"
            h "Åh, hej MC. Jeg… jeg har det fint. Jeg har bare ikke lyst til at komme i vejen for nogen"
            mc "Komme i vejen? Det er en fest, Helpy. Alle er her for at have det sjovt, og det inkluderer dig"
            h "Jeg ved det. Det er bare… svært at finde ud af, hvor jeg passer ind. Og de animatronics derovre"
            h "De virker lidt… uhyggelige"
            mc "Okay, jeg kan give dig ret i, at Freddy og hans venner kan være lidt intense. Men det er bare en del af charmen her, ikke?"
            h "Måske. Det er bare, at… jeg er ikke vant til så mange mennesker og så meget larm. Det er overvældende"
            mc "Jeg forstår. Men måske kunne vi finde noget at lave sammen, bare os to? Måske prøve et spil eller noget"
            h "Et spil? Det lyder ikke så slemt. Men… hvad skal vi spille"
            "du kigger rundt og får øje på et gammelt arkadespil i hjørnet"
            mc "Hvad med det der? Det ser ud som om, det kunne være sjovt"
            h "Det… kunne være okay. Men jeg er ikke så god til spil."
            mc "Ingen bekymringer. Vi spiller bare for sjov. Lad os gå"
            "De går over til arkadespillet og finder ud af, at det er et simpelt puslespil. MC indsætter en mønt og lader Helpy tage første runde"
            mc "Bare rolig, tag din tid. Jeg er sikker på, at du vil klare det fint"
            h "Okay… måske er det ikke så slemt. Jeg tror, jeg har styr på det"
            mc "Se, jeg sagde det jo. Du er naturligt god til det!"
            h "Måske… måske er det faktisk lidt sjovt. Tak, MC. Jeg havde ikke prøvet noget som dette før."
            mc "Det er derfor, jeg er her. Vi skal sørge for, at du også får en god aften"
            "Efter et par runder, hvor Helpy vinder flere gange, begynder han at virke mere afslappet og endda lidt glad."
            h "Du ved… det her er måske den bedste del af aftenen. At have dig her og bare… glemme alt det svære for en stund"
            mc "Det er, hvad venner gør, Helpy. Og jeg er glad for at se dig smile. Lad os spille en runde mere, før vi går tilbage til de andre."
            h "Okay. Men denne gang prøver jeg at slå din rekord"
        "natsuki":
            "du gik hen til natsuki"
            mc "Hey, Natsuki. Er du okay? Du ser lidt... sur ud."
            n "Jeg er ikke sur. Jeg er bare… uinteresseret i alt det her. Seriøst, hvem vælger et pizzaria til en skolefest? Det er så… barnligt"
            mc "Tja, måske. Men maden er ret god, ikke? Har du prøvet cupcakesene"
            n "Selvfølgelig har jeg prøvet dem. Jeg ville bare ønske, det var mine cupcakes. Disse smager… okay. Ikke noget særligt"
            mc "Åh, så hvis det var dine cupcakes, ville hele festen være perfekt?"
            n "Ikke perfekt, men i det mindste bedre. Mine cupcakes er ti gange bedre end det her"
            mc "Det vil jeg ikke argumentere imod. Dine cupcakes er fantastiske. Men hvad skal der til for at gøre resten af aftenen bedre for dig"
            n "Tja, hvis folk stoppede med at være så højrøstede og dumme, ville det hjælpe. Og måske… hvis der var noget sjovt at lave"
            mc "Noget sjovt, huh? Hvad siger du til, at vi udfordrer hinanden i det dartspil derovre"
            n "Dart? Tror du virkelig, du kan slå mig i noget så simpelt"
            mc "Jeg ved det ikke. Men jeg er villig til at prøve. Hvad siger du"
            n "fint. Men når jeg vinder, skylder du mig en pizza. En ordentlig pizza"
            "De går over til dartspillet, og Natsuki tager første tur. Hendes koncentrerede blik og faste hånd viser, at hun tager spillet alvorligt"
            mc "Du ser ud som om, du prøver at vinde en verdensmesterskabstitel"
            n "Hvis jeg skal vinde, skal jeg gøre det ordentligt. Jeg tager ikke let på noget"
            "Efter flere runder, hvor de driller hinanden og griner, vinder Natsuki med en snæver margin."
            n "Se? Hvad sagde jeg? Du kunne aldrig slå mig"
            mc "Okay, du vandt. Jeg skylder dig en pizza"
            n "det er det mindste, du kan gøre. Men… det var faktisk ret sjovt. Tak, MC."
            mc "Alt for at gøre aftenen lidt bedre for dig"
            "De går tilbage til bordet og deler en pizza, mens de fortsætter med at tale og grine. Trods hendes tsundere holdning"
            "begynder Natsuki at slappe af og nyde festen mere, takket være MCs indsats."
        "akira":
            "du gik hun mod akira"
            mc "Hej, Akira. Nyder du festen"
            ak "Nyder? Hm, jeg tror, det kommer an på, hvem jeg taler med"
            mc "Jeg håber, det betyder, at du ikke har noget imod mit selskab"
            "hun Læner sig frem med albuerne på bordet og ser på dig intenst i øjnene"
            ak "Åh, du ved, MC… dit selskab er det eneste, der gør denne kedelige fest værd at være til"
            mc "Kom nu, så slemt er det vel ikke. Der er god mad, musik, og folk hygger sig"
            ak "Tjah, måske. Men jeg har ikke meget tålmodighed til alt det overfladiske. Jeg foretrækker noget… mere ægte"
            mc "Fair nok. Så hvad vil du lave? Der må være noget her, der fanger din interesse"
            "hun Læner sig tilbage og betragter dig med et listigt blik"
            ak "Hvad jeg vil lave? Hm, jeg tror, det afhænger af, hvad du vil lave. Hvis det var op til mig"
            ak "ville vi finde et sted væk fra alle disse mennesker og bare… være os to"
            "dig Lidt nervøst, men forsøger at holde samtalen let"
            mc "Det lyder… hyggeligt. Men vi er til en fest, så måske skulle vi finde noget her, vi kan lave sammen"
            ak "Du er altid så korrekt, MC. Okay, lad os finde noget. Men kun fordi du bad mig"
            "De rejser sig, og Akira fanger hurtigt opmærksomheden på et karaokehjørne. Hun peger mod mikrofonen med et drilsk smil"
            ak "Hvad siger du til, at vi synger en duet? Eller er du for genert til det"
            mc "Jeg tror, hele skolen ville få ondt i ørerne, hvis jeg sang. Men hvis du insisterer"
            ak "Perfekt. Lad os finde en sang. Men hvis du ødelægger det, så skylder du mig en ny aften, bare os to"
            "De vælger en sang og går op til mikrofonen. Akira synger med overraskende smuk stemme, mens MC forsøger at holde trit."
            "Hun griner lidt undervejs, især når han rammer de forkerte toner, men i stedet for at drille ham ser hun ud til at nyde øjeblikket"
            ak "Okay, jeg indrømmer det du var ikke så dårlig, som jeg troede"
            mc "Tak, tror jeg. Men du var virkelig god. Du overrasker mig hele tiden, Akira"
            ak "Og du, MC, gør tingene sjovere, end jeg troede muligt. Måske er du ikke så kedelig, som jeg først troede."
            mc "Tak, tror jeg. Skal vi finde noget mere at lave"
            ak "Eller vi kan bare blive her og tale. Det er rart at have dig for mig selv, for en gangs skyld"
            "De sætter sig tilbage ved bordet, og samtalen flyder videre. Akira flirter åbent med MC"
            "men der er en varme bag hendes intensitet, som afslører"
            "at hun virkelig nyder hans selskab. MC prøver at balancere mellem hendes drilske kommentarer"
            "og hans egne følelser, mens aftenen langsomt skrider frem"
    "i nyd fæsten og bagefter det havet darthjacob noget at sige"
    da "okay allesammen,hør godt efter,vi er alle virkelige meget taknemmelig og ser frem til vores fremtid og vores nutid"
    da "idag vil vi også endelig få afgjort hvem mc bliver kærster med"
    mc "skal jeg det?"
    "ja selvføgelig,det er jo en del af historien"
    da "mc,du må nu vælge den du helst vil være kærster med,skal det være akira,sayori,eller natsuki"
    "nu skal du vælge"
    menu:
        "sayori":
            s "oh waow,mener du virkelig det mc"
            mc "ja,jeg mener det,du den sødste og smukkeste pige der er"
            s "hehe tak,og ja jeg vil gerne være din kærste"
            "i begyndte at kysse,og akira så skuffet og jealoux ud"
        "natsuki":
            n "vent what,hvorfor mig?"
            mc "fordi du den sødeste pige jeg har været sammen med"
            n "jeg er altså ikke sød"
            mc "okay så nøjes jeg bare at sige at du er cool"
            n "meget bedre"
            n "men okay,jeg vil også gerne være din kærste"
            n "bare ingeng kys eller kram okay"
            mc "haha okay det er fint nok"
            "akira kigget jealoux over på jer"
        "akira":
            ak "yay,jeg viste at du vil vælge mig,jeg har altid været din pige der har elsket dig"
            mc "heh,det ved jeg,jeg synes at du altid har været god ved mig,og så smuk,også selv om du engang tog mine bukser da du var på besøg"
            ak "hehe,okay det var måske lidt overstrengen at jeg gjor det,men så fik jeg da dine pæne boxershorts at se"
            mc "akira,de andre kan høre det og det er pingligt"
            ak "oh,hehe undskyld,men ja,jeg vil gerne være din kærste og være sammen med dig forevigt og altid"
            "i begyndte at kysse,og de andre hjulpet,sayori bliv trist over at du valgte akira istedenfor hinde"
    da "når men det har været en god fæst,og tilykke med din nye kærste mc,giv ham en stor hånd"
    mc "tusind tak alle,den her skole og alle jer,betyder så meget for jer,og jeg er glad for at jeg mødte jer"
    f "vi ero også glade for dig mc,du trosalt vores ynglings elev og ven"
    "klokken bliv 22:00 og i vendte alle hjem af"
    scene bg frontPizzaria
    play music mend
    "du kigget lidt på pizzariaet,og bagefter kom darthjacob hen til dig"
    da "hej mc,jeg vil bare sige tak for at du gad at spille det her spil,det har været en ære at møde dig,ses igen senere mc"
    mc "jeg har også været glade for at alt det jeg har været igennem,borset fra det ene tidspunkt hvor baldi skulle til at dræbe mig"
    da "når ja hvis du døde vil du bare automatisk ryge ud af spillet og være i virkeligheden"
    mc "oh okay,og tak igen for at du redet mit liv før"
    da "det var sålidt,ses en anden dag igen mc,vi vil savne dig,og håber at du vil komme tilbage til os igen"
    mc "tak,og jeg skal nok komme tilbage igen,det lover jeg"
    "i sluttet samtalen og du gik vidre hjem af"
    scene bg street_night
    "senere hen kom monika"
    m "hej mc,jeg vil bare sige tak til dig for at spille vores spil,og jeg kunne desværre ikke få yuri tilbage,jeg er ked af det"
    mc "det okay,du gjor dit bedste"
    m "jeg kan stadig ikke tilgive mig selv,jeg dræbte vanny og yuri til ingeng nytte"
    "hun begynder at græde"
    m "og nu når du skal tilbage til virkeligheden kommer jeg til at være alene igen,og de andre vil nok ikke tilgive mig efter det jeg gjor"
    mc "hvad siger du til at jeg kommer nogen par gange så er vi 2 sammen,bare os 2,hvor jeg kommer på det her spil hverdag"
    m "vil du virkelig gøre det for mig"
    mc "ja selvføgelig,jeg holder af dig,og du holder af mig,er det en aftale"
    m "ja,så meget ja,kom her mc"
    "i kramte hindaen i et stort farvel kram"
    "monika begydte at græde da hun havet tanken om at du skulle hjem til virkeligheden"
    m "jeg vil savne dig så meget,og vil aldrig glemme dig,jeg kommer til at tænke på dig hverdag"
    mc "jeg vil også savne dig monika"
    "da i bliv færdige med at være tudefjæs,sagde i farvel og gik hjem til jer selv"
    scene bg bedroom_night
    "det var en smuk slutning og grædene trist på sammentid,men du fik da mange venner her i spillet,og en kærste"
    mc "ja,jeg kommer til at savne jer alle"
    "det forstår jeg godt,det gøre jo ondt at sige farvel,men du skal nok komme tilbage,der vil jo trosalt blive lavet en forsættelse af det her eventyr med dig"
    "jeg ved ikke hvornår,men det vil ske på et tidspunkt"
    mc "det jeg glad for at høre"
    "du faldte i søvn med lidt tårer i øjenene,tydeligt stadig ked over at du skulle væk fra spillet igen,det næsten ligefør at jeg vil tude over det her"
    "tak for alt spiller,ses senere igen"
    "the end"

    return
    
    

        

            
            
            
            


            
            

            
     
    


    
    
    

    

    


    
    

    
    
    


            



        

    

    

    
    


    

        



            
        
        
    
    
    



    
    
        
        
    











    



            


    


 